from django.urls import path

from . import api_views, warehouse_api
from .fbs_period_views import BillingFbsPeriodInvoiceView, BillingFbsPeriodReportView
from .views import (
    BillingActsView,
    BillingApplicationDetailView,
    BillingApplicationsView,
    BillingAuditView,
    BillingChargesView,
    BillingClientDetailView,
    BillingClientsView,
    BillingDebtsView,
    BillingDisputesView,
    BillingDocumentDraftsView,
    BillingExecutedServicesView,
    BillingExtraServicesView,
    BillingFbsKpUploadView,
    BillingFbsView,
    BillingInvoiceCreateView,
    BillingInvoiceDetailView,
    BillingInvoicesView,
    BillingNotificationsView,
    BillingOverviewView,
    BillingOverdueView,
    BillingPaymentsView,
    BillingPromisesView,
    BillingProcessingReportView,
    BillingReconciliationView,
    BillingReceivingReportView,
    BillingReportView,
    BillingReportsView,
    BillingRequestsView,
    BillingSectionStubView,
    BillingShippingPickReportView,
    BillingStorageView,
    BillingTariffsView,
    BillingUpdView,
)

urlpatterns = [
    path("", BillingOverviewView.as_view(), name="billing-overview"),
    path("dashboard/", BillingOverviewView.as_view(), name="billing-dashboard"),
    path("clients/", BillingClientsView.as_view(), name="billing-clients"),
    path("clients/<int:client_id>/", BillingClientDetailView.as_view(), name="billing-client-detail"),
    path("applications/", BillingApplicationsView.as_view(), name="billing-applications"),
    path("fbs/", BillingFbsView.as_view(), name="billing-fbs"),
    path("fbs/period-report/", BillingFbsPeriodReportView.as_view(), name="billing-fbs-period-report"),
    path("fbs/period-invoice/", BillingFbsPeriodInvoiceView.as_view(), name="billing-fbs-period-invoice"),
    path("fbs/kp-upload/", BillingFbsKpUploadView.as_view(), name="billing-fbs-kp-upload"),
    path("applications/<int:pk>/", BillingApplicationDetailView.as_view(), name="billing-application-detail"),
    path("charges/", BillingChargesView.as_view(), name="billing-charges"),
    path("services/", BillingExecutedServicesView.as_view(), name="billing-services"),
    path("executed-services/", BillingExecutedServicesView.as_view(), name="billing-executed-services"),
    path("receiving-report/", BillingReceivingReportView.as_view(), name="billing-receiving-report"),
    path("processing-report/", BillingProcessingReportView.as_view(), name="billing-processing-report"),
    path("shipping-pick-report/", BillingShippingPickReportView.as_view(), name="billing-shipping-pick-report"),
    path("acts/", BillingActsView.as_view(), name="billing-acts"),
    path("acts/<int:pk>/print/", api_views.act_print, name="billing-act-print"),
    path("report/", BillingReportView.as_view(), name="billing-report"),
    path("invoices/", BillingInvoicesView.as_view(), name="billing-invoices"),
    path("invoices/create/", BillingInvoiceCreateView.as_view(), name="billing-invoice-create"),
    path("invoices/<int:pk>/print/", api_views.invoice_print, name="billing-invoice-print"),
    path("invoices/<int:pk>/", BillingInvoiceDetailView.as_view(), name="billing-invoice-detail"),
    path("storage/", BillingStorageView.as_view(), name="billing-storage"),
    path("tariffs/", BillingTariffsView.as_view(), name="billing-tariffs"),
    path("payments/", BillingPaymentsView.as_view(), name="billing-payments"),
    path("overdue/", BillingOverdueView.as_view(), name="billing-overdue"),
    path("debts/", BillingDebtsView.as_view(), name="billing-debts"),
    path("promises/", BillingPromisesView.as_view(), name="billing-promises"),
    path("reconciliation/", BillingReconciliationView.as_view(), name="billing-reconciliation"),
    path("disputes/", BillingDisputesView.as_view(), name="billing-disputes"),
    path("requests/", BillingRequestsView.as_view(), name="billing-requests"),
    path("extra-services/", BillingExtraServicesView.as_view(), name="billing-extra-services"),
    path("document-drafts/", BillingDocumentDraftsView.as_view(), name="billing-document-drafts"),
    path("upd/", BillingUpdView.as_view(), name="billing-upd"),
    path("documents/", BillingSectionStubView.as_view(), {"section_key": "documents"}, name="billing-documents"),
    path("reports/", BillingReportsView.as_view(), name="billing-reports"),
    path("notifications/", BillingNotificationsView.as_view(), name="billing-notifications"),
    path("audit/", BillingAuditView.as_view(), name="billing-audit"),
    path("api/applications/", api_views.manager_applications, name="billing-api-applications"),
    path("api/sync-applications/", api_views.manager_sync_applications, name="billing-api-sync-applications"),
    path("api/services/", api_views.manager_services, name="billing-api-services"),
    path("api/standard-prices/", api_views.manager_standard_prices, name="billing-api-standard-prices"),
    path("api/client-contracts/", api_views.manager_client_contracts, name="billing-api-client-contracts"),
    path("api/client-contracts/<int:pk>/", api_views.manager_client_contract_detail, name="billing-api-client-contract-detail"),
    path("api/tariff-catalog/", api_views.manager_tariff_catalog, name="billing-api-tariff-catalog"),
    path("api/tariff-versions/", api_views.manager_tariff_versions, name="billing-api-tariff-versions"),
    path("api/tariff-versions/<int:pk>/", api_views.manager_tariff_version_detail, name="billing-api-tariff-version-detail"),
    path("api/tariff-versions/<int:pk>/copy/", api_views.manager_tariff_version_copy, name="billing-api-tariff-version-copy"),
    path("api/tariff-versions/<int:pk>/activate/", api_views.manager_tariff_version_activate, name="billing-api-tariff-version-activate"),
    path("api/tariff-versions/<int:pk>/archive/", api_views.manager_tariff_version_archive, name="billing-api-tariff-version-archive"),
    path("api/tariff-versions/<int:pk>/items/", api_views.manager_tariff_version_items, name="billing-api-tariff-version-items"),
    path("api/tariff-versions/<int:pk>/conditions/", api_views.manager_tariff_version_conditions, name="billing-api-tariff-version-conditions"),
    path("tariff-versions/<int:pk>/download/", api_views.tariff_version_download, name="billing-tariff-version-download"),
    path("api/tariffs/", api_views.manager_tariffs, name="billing-api-tariffs"),
    path("api/tariffs/<int:pk>/", api_views.manager_tariff_detail, name="billing-api-tariff-detail"),
    path("api/applications/<int:pk>/", api_views.manager_application_detail, name="billing-api-application-detail"),
    path("api/applications/<int:pk>/charges/", api_views.manager_application_charges, name="billing-api-application-charges"),
    path(
        "api/applications/<int:pk>/charges/bulk/",
        api_views.manager_application_charges_bulk,
        name="billing-api-charges-bulk",
    ),
    path("api/charges/<int:pk>/", api_views.manager_charge_detail, name="billing-api-charge-detail"),
    path("api/charges/<int:pk>/confirm/", api_views.manager_charge_confirm, name="billing-api-charge-confirm"),
    path("api/charges/<int:pk>/unconfirm/", api_views.manager_charge_unconfirm, name="billing-api-charge-unconfirm"),
    path("api/charges/<int:pk>/exclude/", api_views.manager_charge_exclude, name="billing-api-charge-exclude"),
    path("api/charges/<int:pk>/restore/", api_views.manager_charge_restore, name="billing-api-charge-restore"),
    path("api/charges/<int:pk>/history/", api_views.manager_charge_history, name="billing-api-charge-history"),
    path("api/charges/<int:pk>/recalc/", api_views.manager_charge_recalc, name="billing-api-charge-recalc"),
    path(
        "api/applications/<int:pk>/confirm-charges/",
        api_views.manager_confirm_application_charges,
        name="billing-api-application-confirm-charges",
    ),
    path("api/applications/<int:pk>/calculate/", api_views.manager_calculate_application, name="billing-api-application-calculate"),
    path("api/applications/<int:pk>/acts/", api_views.manager_generate_act, name="billing-api-application-act"),
    path("api/acts/<int:pk>/send/", api_views.manager_send_act, name="billing-api-act-send"),
    path("api/acts/<int:pk>/cancel/", api_views.manager_cancel_act, name="billing-api-act-cancel"),
    path("api/invoices/", api_views.manager_invoices, name="billing-api-invoices"),
    path("api/applications/<int:pk>/invoice/", api_views.manager_create_invoice, name="billing-api-application-invoice"),
    path("api/invoices/from-acts/", api_views.manager_create_invoice_from_acts, name="billing-api-invoice-from-acts"),
    path(
        "api/invoices/from-shipping-applications/",
        api_views.manager_create_invoice_from_shipping_applications,
        name="billing-api-invoice-from-shipping-applications",
    ),
    path("api/invoices/<int:pk>/check/", api_views.manager_check_invoice, name="billing-api-invoice-check"),
    path("api/invoices/<int:pk>/send/", api_views.manager_send_invoice, name="billing-api-invoice-send"),
    path("api/invoices/<int:pk>/payments/", api_views.manager_register_payment, name="billing-api-invoice-payments"),
    path("api/applications/<int:pk>/financial-close/", api_views.manager_financial_close, name="billing-api-financial-close"),
    path(
        "api/applications/<int:pk>/mark-external/",
        api_views.manager_mark_external,
        name="billing-api-mark-external",
    ),
    path(
        "api/applications/<int:pk>/manual-invoice-marker/",
        api_views.manager_manual_invoice_marker,
        name="billing-api-manual-invoice-marker",
    ),
    path(
        "api/applications/manual-invoice-marker/bulk/",
        api_views.manager_manual_invoice_marker_bulk,
        name="billing-api-manual-invoice-marker-bulk",
    ),
    path("api/applications/<int:pk>/storage-day/", api_views.manager_record_storage_day, name="billing-api-storage-day"),
    path("api/applications/<int:pk>/late-storage/", api_views.manager_late_receiving_storage, name="billing-api-late-receiving-storage"),
    path(
        "api/storage/recalculate-open/",
        api_views.manager_recalculate_open_storage,
        name="billing-api-storage-recalculate-open",
    ),
    path("api/storage/days/", api_views.manager_storage_days, name="billing-api-storage-days"),
    path("api/storage/export.xlsx", api_views.manager_storage_export_xlsx, name="billing-api-storage-export-xlsx"),
    path("api/storage/days/<int:pk>/", api_views.manager_storage_day_detail, name="billing-api-storage-day-detail"),
    path("api/extra-services/", api_views.manager_extra_services, name="billing-api-extra-services"),
    path(
        "api/warehouse-services/catalog/",
        warehouse_api.warehouse_service_catalog,
        name="billing-api-warehouse-service-catalog",
    ),
    path(
        "api/warehouse-services/facts/",
        warehouse_api.warehouse_service_facts,
        name="billing-api-warehouse-service-facts",
    ),
    path(
        "api/extra-services/<int:pk>/retry/",
        api_views.manager_extra_service_retry,
        name="billing-api-extra-service-retry",
    ),
    path(
        "api/extra-services/<int:pk>/cancel/",
        api_views.manager_extra_service_cancel,
        name="billing-api-extra-service-cancel",
    ),
    path("api/acts/<int:pk>/submit/", api_views.manager_submit_act, name="billing-api-act-submit"),
    path("api/acts/<int:pk>/return/", api_views.manager_return_act, name="billing-api-act-return"),
    path("api/acts/<int:pk>/accept/", api_views.manager_accept_act, name="billing-api-act-accept"),
    path("api/invoices/<int:pk>/submit/", api_views.manager_submit_invoice, name="billing-api-invoice-submit"),
    path("api/invoices/<int:pk>/return/", api_views.manager_return_invoice, name="billing-api-invoice-return"),
    path("api/invoices/<int:pk>/accept/", api_views.manager_accept_invoice, name="billing-api-invoice-accept"),
    path("api/upd-requests/", api_views.manager_upd_requests, name="billing-api-upd-requests"),
    path("api/audit/", api_views.manager_audit_timeline, name="billing-api-audit"),
    path("api/payments/", api_views.manager_payments_ledger, name="billing-api-payments"),
    path("api/debts/", api_views.manager_debts_summary, name="billing-api-debts"),
    path("api/promises/", api_views.manager_payment_promises, name="billing-api-promises"),
    path("api/promises/<int:pk>/", api_views.manager_payment_promise_detail, name="billing-api-promise-detail"),
    path("api/reconciliation/", api_views.manager_reconciliation_requests, name="billing-api-reconciliation"),
    path(
        "api/reconciliation/<int:pk>/submit/",
        api_views.manager_reconciliation_submit,
        name="billing-api-reconciliation-submit",
    ),
    path("api/discrepancies/", api_views.manager_discrepancies, name="billing-api-discrepancies"),
    path(
        "api/discrepancies/<int:pk>/",
        api_views.manager_discrepancy_detail,
        name="billing-api-discrepancy-detail",
    ),
    path("api/notifications/", api_views.manager_notifications, name="billing-api-notifications"),
    path(
        "api/notifications/<int:pk>/read/",
        api_views.manager_notification_read,
        name="billing-api-notification-read",
    ),
    path(
        "api/notifications/read-all/",
        api_views.manager_notifications_read_all,
        name="billing-api-notifications-read-all",
    ),
]
