# Generated by Django 6.0 on 2026-07-18 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('head_manager', '0004_owncompany_tax_mode'),
        ('sku', '0010_sku_weight_gross_kg_sku_weight_net_kg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLifecycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('accountant_review', 'На проверке бухгалтера'), ('requisites_ready', 'Реквизиты заполнены'), ('tariffs_ready', 'Тарифы заполнены'), ('active', 'Активен'), ('blocked', 'Заблокирован'), ('archived', 'Архивный')], db_index=True, default='draft', max_length=32, verbose_name='Статус')),
                ('client_type', models.CharField(blank=True, choices=[('ip', 'ИП'), ('ooo', 'ООО'), ('self_employed', 'Самозанятый'), ('person', 'Физлицо')], max_length=32, verbose_name='Тип клиента')),
                ('postal_address', models.CharField(blank=True, max_length=512, verbose_name='Почтовый адрес')),
                ('email_documents', models.EmailField(blank=True, max_length=254, verbose_name='Email для документов')),
                ('email_notifications', models.EmailField(blank=True, max_length=254, verbose_name='Email для уведомлений')),
                ('accountant_comment', models.TextField(blank=True, verbose_name='Комментарий бухгалтера')),
                ('commercial_offer_number', models.CharField(blank=True, max_length=128, verbose_name='Номер КП')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='Дата договора')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Активирован')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_client_lifecycles', to=settings.AUTH_USER_MODEL, verbose_name='Кто активировал')),
                ('agency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle', to='sku.agency', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_client_lifecycles', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('serving_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='served_clients', to='head_manager.owncompany', verbose_name='Компания обслуживания FullBox')),
            ],
            options={
                'verbose_name': 'Жизненный цикл клиента',
                'verbose_name_plural': 'Жизненные циклы клиентов',
            },
        ),
        migrations.CreateModel(
            name='ClientChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=128, verbose_name='Поле')),
                ('old_value', models.TextField(blank=True, verbose_name='Было')),
                ('new_value', models.TextField(blank=True, verbose_name='Стало')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountant_change_logs', to='sku.agency')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_accountant_changes', to=settings.AUTH_USER_MODEL)),
                ('lifecycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='accountant.clientlifecycle')),
            ],
            options={
                'verbose_name': 'История изменений клиента',
                'verbose_name_plural': 'История изменений клиентов',
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='clientlifecycle',
            index=models.Index(fields=['status'], name='accountant__status_38ea82_idx'),
        ),
    ]
