from django.urls import path

from . import api_views, views
from .fbs_tariffs import AccountantFbsTariffsView, AccountantGeneralTariffsView

urlpatterns = [
    path("", views.AccountantOverviewView.as_view(), name="accountant-overview"),
    path("investor-preview/", views.AccountantInvestorPreviewView.as_view(), name="accountant-investor-preview"),
    path("clients/", views.AccountantClientsView.as_view(), name="accountant-clients"),
    path("clients/<int:pk>/delete/", views.AccountantClientDeleteView.as_view(), name="accountant-client-delete"),
    path("clients/<int:pk>/", views.AccountantClientDetailView.as_view(), name="accountant-client-detail"),
    path("tariffs/", AccountantGeneralTariffsView.as_view(), name="accountant-tariffs"),
    path("tariffs/catalog/", views.AccountantServicesCatalogView.as_view(), name="accountant-tariffs-catalog"),
    path("tariffs/no-price/", views.AccountantTariffNoPriceView.as_view(), name="accountant-tariffs-no-price"),
    path("logistics/price-list/", views.AccountantLogisticsPriceView.as_view(), name="accountant-logistics-price-list"),
    path("logistics/tariffs/", views.AccountantClientLogisticsTariffsView.as_view(), name="accountant-client-logistics-tariffs"),
    path("logistics/tariffs/<int:pk>/", views.AccountantClientLogisticsTariffDetailView.as_view(), name="accountant-client-logistics-tariff-detail"),
    path("fbs/tariffs/", AccountantFbsTariffsView.as_view(), name="accountant-fbs-tariffs"),
    path("tariffs/<int:pk>/delete/", views.AccountantTariffDeleteView.as_view(), name="accountant-tariff-delete"),
    path("tariffs/<int:pk>/", views.AccountantTariffDetailView.as_view(), name="accountant-tariff-detail"),
    path("contracts/", views.AccountantContractsView.as_view(), name="accountant-contracts"),
    path("history/", views.AccountantHistoryView.as_view(), name="accountant-history"),
    path("tariff-check/", views.AccountantTariffCheckView.as_view(), name="accountant-tariff-check"),
    path("storage/", views.AccountantStorageView.as_view(), name="accountant-storage"),
    path("charges/", views.AccountantChargesView.as_view(), name="accountant-charges"),
    path("charges/adjustments/", views.AccountantChargeAdjustmentsView.as_view(), name="accountant-charge-adjustments"),
    path("own-companies/", views.AccountantOwnCompaniesView.as_view(), name="accountant-own-companies"),
    path("own-companies/new/", views.AccountantOwnCompanyCreateView.as_view(), name="accountant-own-company-create"),
    path("own-companies/<int:pk>/delete/", views.AccountantOwnCompanyDeleteView.as_view(), name="accountant-own-company-delete"),
    path("own-companies/<int:pk>/", views.AccountantOwnCompanyUpdateView.as_view(), name="accountant-own-company-edit"),
    path("carriers/", views.AccountantCarriersView.as_view(), name="accountant-carriers"),
    path("carriers/new/", views.AccountantCarrierCreateView.as_view(), name="accountant-carrier-create"),
    path("carriers/<int:pk>/", views.AccountantCarrierUpdateView.as_view(), name="accountant-carrier-edit"),
    # API
    path("api/clients/", api_views.api_clients, name="accountant-api-clients"),
    path("api/clients/lookup-inn/", api_views.api_client_lookup_inn, name="accountant-api-client-lookup-inn"),
    path("api/clients/lookup-bik/", api_views.api_client_lookup_bik, name="accountant-api-client-lookup-bik"),
    path("api/clients/create/", api_views.api_clients_create, name="accountant-api-clients-create"),
    path("api/clients/<int:pk>/", api_views.api_client_detail, name="accountant-api-client-detail"),
    path("api/clients/<int:pk>/patch/", api_views.api_client_patch, name="accountant-api-client-patch"),
    path("api/clients/<int:pk>/activate/", api_views.api_client_activate, name="accountant-api-client-activate"),
    path("api/clients/<int:pk>/history/", api_views.api_client_history, name="accountant-api-client-history"),
    path("api/services/", api_views.api_services, name="accountant-api-services"),
    path("api/serving-companies/", api_views.api_serving_companies, name="accountant-api-serving-companies"),
    path("api/client-tariffs/", api_views.api_client_tariffs, name="accountant-api-client-tariffs"),
    path("api/client-tariffs/create/", api_views.api_client_tariffs_create, name="accountant-api-client-tariffs-create"),
    path("api/client-tariffs/<int:pk>/", api_views.api_client_tariff_detail, name="accountant-api-client-tariff-detail"),
    path("api/client-tariffs/<int:pk>/patch/", api_views.api_client_tariff_patch, name="accountant-api-client-tariff-patch"),
    path(
        "api/client-tariffs/<int:pk>/apply-price-list/",
        api_views.api_client_tariff_apply_price_list,
        name="accountant-api-client-tariff-apply-price-list",
    ),
    path("api/client-tariffs/<int:pk>/publish/", api_views.api_client_tariff_publish, name="accountant-api-client-tariff-publish"),
    path("api/client-tariffs/<int:pk>/archive/", api_views.api_client_tariff_archive, name="accountant-api-client-tariff-archive"),
    path("api/client-tariffs/<int:pk>/duplicate/", api_views.api_client_tariff_duplicate, name="accountant-api-client-tariff-duplicate"),
    path("api/client-tariffs/<int:pk>/history/", api_views.api_client_tariff_history, name="accountant-api-client-tariff-history"),
    path("api/client-tariffs/<int:pk>/storage-rule/", api_views.api_storage_rule, name="accountant-api-storage-rule"),
    path("api/client-tariffs/<int:pk>/storage-rule/patch/", api_views.api_storage_rule_patch, name="accountant-api-storage-rule-patch"),
    path("api/storage/days/", api_views.api_storage_days, name="accountant-api-storage-days"),
    path("api/storage/days/<int:pk>/", api_views.api_storage_day_detail, name="accountant-api-storage-day-detail"),
    path("api/storage/errors/", api_views.api_storage_errors, name="accountant-api-storage-errors"),
    path("api/storage/errors/<int:pk>/resolve/", api_views.api_storage_error_resolve, name="accountant-api-storage-error-resolve"),
    path("api/storage/periods/", api_views.api_storage_periods, name="accountant-api-storage-periods"),
    path("api/storage/adjustments/", api_views.api_storage_adjustments, name="accountant-api-storage-adjustments"),
    path("api/storage/export.csv", api_views.api_storage_export_csv, name="accountant-api-storage-export"),
    # Новые разделы меню (stub / bridge / alias) — после конкретных маршрутов
    path("<path:section_path>/", views.AccountantSectionView.as_view(), name="accountant-section"),
]
