from django.urls import path

from . import tsd_views
from . import tsd_app
from . import operator_views
from . import controller_views
from . import controller_tote_transfer_views
from . import desktop_print
from . import web_ui
from . import external_issue_views


app_name = "fbs"

urlpatterns = [
    path("controller/tote-transfers/", controller_tote_transfer_views.controller_tote_transfers, name="controller_tote_transfers"),
    path("outbound/", external_issue_views.issue_list, name="external_issues"),
    path("outbound/<int:issue_id>/", external_issue_views.issue_detail, name="external_issue_detail"),
    path("", web_ui.module_status, name="status"),
    path("desktop-print/next/", desktop_print.jobs_next, name="desktop_print_jobs_next"),
    path("desktop-print/presence/", desktop_print.jobs_presence, name="desktop_print_jobs_presence"),
    path("desktop-print/complete/", desktop_print.jobs_complete, name="desktop_print_jobs_complete"),
    path("controller/", controller_views.controller_home, name="controller_home"),
    path(
        "controller/report/",
        controller_views.controller_daily_report,
        name="controller_daily_report",
    ),
    path(
        "controller/check-totes/<int:check_tote_id>/",
        controller_views.controller_check_tote,
        name="controller_check_tote",
    ),
    path(
        "controller/pick-restocks/",
        controller_views.controller_pick_restocks,
        name="controller_pick_restocks",
    ),
    path(
        "controller/scan-events/",
        controller_views.controller_scan_events,
        name="controller_scan_events",
    ),
    path(
        "controller/shift/heartbeat/",
        controller_views.controller_shift_heartbeat,
        name="controller_shift_heartbeat",
    ),
    path("metadata/", web_ui.metadata_control_list, name="metadata_control"),
    path("operator/orders/", operator_views.operator_orders, name="operator_orders"),
    path("operator/queue/", operator_views.operator_queue, name="operator_queue"),
    path(
        "operator/reports/",
        operator_views.operator_order_reports,
        name="operator_order_reports",
    ),
    path(
        "operator/stock-history/",
        operator_views.operator_stock_history,
        name="operator_stock_history",
    ),
    path(
        "operator/stock-history/item/",
        operator_views.operator_stock_item_history,
        name="operator_stock_item_history",
    ),
    path(
        "operator/readiness/",
        operator_views.operator_readiness,
        name="operator_readiness",
    ),
    path("operator/totes/", operator_views.operator_totes, name="operator_totes"),
    path(
        "operator/totes/create/",
        operator_views.operator_tote_create,
        name="operator_tote_create",
    ),
    path(
        "operator/totes/labels/",
        operator_views.operator_tote_labels,
        name="operator_tote_labels",
    ),
    path(
        "operator/totes/<int:cart_id>/update/",
        operator_views.operator_tote_update,
        name="operator_tote_update",
    ),
    path(
        "operator/orders/sync/",
        operator_views.operator_sync_all_orders,
        name="operator_sync_all_orders",
    ),
    path(
        "operator/orders/<int:order_id>/",
        operator_views.operator_order_detail,
        name="operator_order_detail",
    ),
    path("operator/clients/", operator_views.operator_clients, name="operator_clients"),
    path(
        "operator/movements/",
        operator_views.operator_movements,
        name="operator_movements",
    ),
    path(
        "operator/movements/from-receiving/",
        operator_views.operator_movement_from_receiving,
        name="operator_movement_from_receiving",
    ),
    path(
        "operator/movements/from-receiving/create/",
        operator_views.operator_create_movement_from_receiving,
        name="operator_create_movement_from_receiving",
    ),
    path(
        "operator/movements/<int:request_id>/",
        operator_views.operator_movement_detail,
        name="operator_movement_detail",
    ),
    path(
        "operator/movements/<int:request_id>/labels/",
        operator_views.operator_movement_labels,
        name="operator_movement_labels",
    ),
    path(
        "operator/movements/<int:request_id>/approve/",
        operator_views.operator_approve_movement,
        name="operator_approve_movement",
    ),
    path(
        "operator/movements/<int:request_id>/cancel/",
        operator_views.operator_cancel_movement,
        name="operator_cancel_movement",
    ),
    path(
        "operator/movements/<int:request_id>/confirm/",
        operator_views.operator_confirm_movement,
        name="operator_confirm_movement",
    ),
    path(
        "operator/movements/<int:request_id>/pack/",
        operator_views.operator_pack_movement,
        name="operator_pack_movement",
    ),
    path(
        "operator/clients/<int:agency_id>/sync/",
        operator_views.operator_sync_client_orders,
        name="operator_sync_client_orders",
    ),
    path(
        "operator/clients/<int:agency_id>/stock-safety/",
        operator_views.operator_update_client_stock_safety,
        name="operator_update_client_stock_safety",
    ),
    path(
        "operator/clients/<int:agency_id>/",
        operator_views.operator_client_detail,
        name="operator_client_detail",
    ),
    path(
        "operator/profiles/<int:profile_id>/sync/",
        operator_views.operator_sync_profile_orders,
        name="operator_sync_profile_orders",
    ),
    path("operator/waves/", operator_views.operator_waves, name="operator_waves"),
    path(
        "operator/waves/report/",
        operator_views.operator_wave_report,
        name="operator_wave_report",
    ),
    path(
        "operator/waves/prepare/",
        operator_views.operator_prepare_wave,
        name="operator_prepare_wave",
    ),
    path(
        "operator/waves/confirm/",
        operator_views.operator_prepare_wave,
        name="operator_confirm_wave",
    ),
    path(
        "operator/waves/<int:batch_id>/queue-order/",
        operator_views.operator_reorder_wave,
        name="operator_reorder_wave",
    ),
    path(
        "operator/waves/<int:batch_id>/",
        operator_views.operator_wave_detail,
        name="operator_wave_detail",
    ),
    path(
        "operator/problems/",
        operator_views.operator_problems,
        name="operator_problems",
    ),
    path(
        "metadata/orders/<int:order_id>/",
        web_ui.metadata_control_detail,
        name="metadata_control_detail",
    ),
    path(
        "metadata/orders/<int:order_id>/readback/",
        web_ui.metadata_control_readback,
        name="metadata_control_readback",
    ),
    path("tsd/", tsd_views.tsd_home, name="tsd_home"),
    path("tsd/app/version/", tsd_app.tsd_app_version, name="tsd_app_version"),
    path("tsd/app/download/", tsd_app.tsd_app_download, name="tsd_app_download"),
    path("tsd/storekeeper/", tsd_views.tsd_storekeeper, name="tsd_storekeeper"),
    path(
        "tsd/storekeeper/alerts/",
        tsd_views.tsd_storekeeper_alerts,
        name="tsd_storekeeper_alerts",
    ),
    path(
        "tsd/storekeeper/settings/waves/",
        tsd_views.tsd_wave_settings,
        name="tsd_wave_settings",
    ),
    path(
        "tsd/storekeeper/settings/controllers/",
        tsd_views.tsd_controller_settings,
        name="tsd_controller_settings",
    ),
    path(
        "tsd/storekeeper/stock/",
        tsd_views.tsd_storekeeper_stock,
        name="tsd_storekeeper_stock",
    ),
    path(
        "tsd/storekeeper/stock/export/",
        tsd_views.tsd_storekeeper_stock_export,
        name="tsd_storekeeper_stock_export",
    ),
    path("tsd/storekeeper/inventory/", tsd_views.tsd_inventory, name="tsd_inventory"),
    path(
        "tsd/storekeeper/inventory/<int:session_id>/",
        tsd_views.tsd_inventory_detail,
        name="tsd_inventory_detail",
    ),
    path("tsd/storekeeper/handover/", tsd_views.tsd_handover, name="tsd_handover"),
    path(
        "tsd/storekeeper/handover/reports/",
        tsd_views.tsd_handover_reports,
        name="tsd_handover_reports",
    ),
    path(
        "tsd/storekeeper/handover/<int:batch_id>/",
        tsd_views.tsd_handover_detail,
        name="tsd_handover_detail",
    ),
    path(
        "tsd/storekeeper/handover/<int:batch_id>/driver-manifest/",
        tsd_views.tsd_handover_driver_manifest,
        name="tsd_handover_driver_manifest",
    ),
    path(
        "tsd/storekeeper/handover/<int:batch_id>/boxes/<int:box_id>/label/",
        tsd_views.tsd_handover_box_label,
        name="tsd_handover_box_label",
    ),
    path(
        "tsd/storekeeper/handover/<int:batch_id>/supply-label/",
        tsd_views.tsd_handover_supply_label,
        name="tsd_handover_supply_label",
    ),
    path(
        "tsd/storekeeper/handover/<int:batch_id>/ozon-document/<str:document_kind>/",
        tsd_views.tsd_handover_ozon_document,
        name="tsd_handover_ozon_document",
    ),
    path("tsd/storekeeper/demand/", tsd_views.tsd_demand, name="tsd_demand"),
    path(
        "tsd/storekeeper/demand/first-floor-movement/",
        tsd_views.tsd_create_floor_movement,
        name="tsd_create_floor_movement",
    ),
    path(
        "tsd/storekeeper/demand/generate/",
        tsd_views.tsd_generate_plans,
        name="tsd_generate_plans",
    ),
    path("tsd/picking/", tsd_views.tsd_picking, name="tsd_picking"),
    path(
        "tsd/picker/returns/",
        tsd_views.tsd_picker_returns,
        name="tsd_picker_returns",
    ),
    path(
        "tsd/picker/movements/",
        tsd_views.tsd_picker_movements,
        name="tsd_picker_movements",
    ),
    path(
        "tsd/picker/movements/box-to-cell/",
        tsd_views.tsd_picker_move_box_cell,
        name="tsd_picker_move_box_cell",
    ),
    path(
        "tsd/picker/movements/cell-to-cell/",
        tsd_views.tsd_picker_move_cell_cell,
        name="tsd_picker_move_cell_cell",
    ),
    path(
        "tsd/picker/movements/box-to-box/",
        tsd_views.tsd_picker_move_box_box,
        name="tsd_picker_move_box_box",
    ),
    path(
        "tsd/picker/movements/full-box-to-location/",
        tsd_views.tsd_picker_move_full_box,
        name="tsd_picker_move_full_box",
    ),
    path(
        "tsd/picker/movements/pallet-to-location/",
        tsd_views.tsd_picker_move_pallet,
        name="tsd_picker_move_pallet",
    ),
    path(
        "tsd/picker/location/",
        tsd_views.tsd_picker_location,
        name="tsd_picker_location",
    ),
    path(
        "tsd/picking/restocks/<int:request_id>/",
        tsd_views.tsd_pick_restock,
        name="tsd_pick_restock",
    ),
    path(
        "tsd/picking/equipment/bind/",
        tsd_views.tsd_bind_pick_equipment,
        name="tsd_bind_pick_equipment",
    ),
    path(
        "tsd/picking/equipment/clear/",
        tsd_views.tsd_clear_pick_equipment,
        name="tsd_clear_pick_equipment",
    ),
    path(
        "tsd/picking/claim-next/",
        tsd_views.tsd_claim_next_pick_batch,
        name="tsd_claim_next_pick_batch",
    ),
    path("tsd/labels/", tsd_views.tsd_labels, name="tsd_labels"),
    path(
        "tsd/labels/<int:label_id>/file/",
        tsd_views.tsd_label_file,
        name="tsd_label_file",
    ),
    path(
        "tsd/labels/<int:label_id>/",
        tsd_views.tsd_label_detail,
        name="tsd_label_detail",
    ),
    path(
        "tsd/picking/prepare/",
        tsd_views.tsd_prepare_picking,
        name="tsd_prepare_picking",
    ),
    path(
        "tsd/picking/tasks/<int:task_id>/claim/",
        tsd_views.tsd_claim_pick_task,
        name="tsd_claim_pick_task",
    ),
    path(
        "tsd/picking/batches/<int:batch_id>/claim/",
        tsd_views.tsd_claim_pick_batch,
        name="tsd_claim_pick_batch",
    ),
    path(
        "tsd/picking/allocations/<int:allocation_id>/",
        tsd_views.tsd_pick_allocation,
        name="tsd_pick_allocation",
    ),
    path(
        "tsd/picking/batches/<int:batch_id>/verification/",
        tsd_views.tsd_pick_verification,
        name="tsd_pick_verification",
    ),
    path(
        "tsd/picking/allocations/<int:allocation_id>/verification-problem/",
        tsd_views.tsd_pick_verification_problem,
        name="tsd_pick_verification_problem",
    ),
    path(
        "tsd/picking/batches/<int:batch_id>/handover/",
        tsd_views.tsd_pick_handover,
        name="tsd_pick_handover",
    ),
    path(
        "tsd/storekeeper/plans/<int:plan_id>/",
        tsd_views.tsd_storekeeper_plan,
        name="tsd_storekeeper_plan",
    ),
    path(
        "tsd/storekeeper/plans/<int:plan_id>/confirm/",
        tsd_views.tsd_confirm_plan,
        name="tsd_confirm_plan",
    ),
    path(
        "tsd/storekeeper/plans/<int:plan_id>/cancel/",
        tsd_views.tsd_cancel_plan,
        name="tsd_cancel_plan",
    ),
    path(
        "tsd/storekeeper/plans/<int:plan_id>/pack/",
        tsd_views.tsd_pack_plan,
        name="tsd_pack_plan",
    ),
    path("tsd/reachtruck/", tsd_views.tsd_reachtruck, name="tsd_reachtruck"),
    path(
        "tsd/reachtruck/plans/<int:plan_id>/claim/",
        tsd_views.tsd_claim_plan,
        name="tsd_claim_plan",
    ),
    path(
        "tsd/reachtruck/movements/<int:movement_id>/claim/",
        tsd_views.tsd_claim_internal_movement,
        name="tsd_claim_internal_movement",
    ),
    path(
        "tsd/reachtruck/movements/<int:movement_id>/",
        tsd_views.tsd_internal_movement,
        name="tsd_internal_movement",
    ),
    path(
        "tsd/reachtruck/allocations/<int:allocation_id>/",
        tsd_views.tsd_allocation,
        name="tsd_allocation",
    ),
]
