# Generated by Django 6.0 on 2026-06-04 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_agentcontext_and_event_context'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='agentcommand',
            index=models.Index(fields=['status', 'agent_id', 'created_at'], name='agent_agent_status_f70c90_idx'),
        ),
        migrations.AddIndex(
            model_name='agentevent',
            index=models.Index(fields=['context_id', 'event_type', 'id'], name='agent_agent_context_76f92f_idx'),
        ),
        migrations.AddIndex(
            model_name='agentevent',
            index=models.Index(fields=['agent_id', 'event_type', 'id'], name='agent_agent_agent_i_0399eb_idx'),
        ),
    ]
