# Generated by Django 6.0 on 2026-08-25 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0005_deviceagent_token_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agentevent",
            name="client_event_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name="agentevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_event_id", ""), _negated=True),
                fields=("agent_id", "client_event_id"),
                name="uniq_agent_client_event_id",
            ),
        ),
    ]
