# Generated by Django 6.0 on 2026-08-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0010_warehousecontainer_dimensions_weight'),
        ('sku', '0010_sku_weight_gross_kg_sku_weight_net_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousereserve',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousereserve',
            name='lot_code',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='warehousestocksnapshot',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousestocksnapshot',
            name='lot_code',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddIndex(
            model_name='warehousestocksnapshot',
            index=models.Index(fields=['agency', 'expiry_date'], name='warehouse_s_agency__e0c141_idx'),
        ),
    ]
