# Generated by Django 6.0 on 2026-09-06 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0015_employee_qr_login'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HrDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HR-отдел',
                'verbose_name_plural': 'HR-отделы',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HrEmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=160, verbose_name='Должность')),
                ('personnel_number', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Табельный номер')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_profiles', to='hr.hrdepartment', verbose_name='Отдел')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_profile', to='employees.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'HR-карточка сотрудника',
                'verbose_name_plural': 'HR-карточки сотрудников',
                'ordering': ('department__name', 'employee__full_name'),
            },
        ),
        migrations.CreateModel(
            name='HrEmployeePayRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(db_index=True, verbose_name='Действует с')),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True, verbose_name='Действует по')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Почасовая ставка')),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Месячный оклад')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Основание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_pay_rates', to='employees.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Ставка сотрудника',
                'verbose_name_plural': 'Ставки сотрудников',
                'ordering': ('employee_id', '-effective_from', '-id'),
                'constraints': [models.UniqueConstraint(fields=('employee', 'effective_from'), name='hr_unique_employee_rate_start'), models.CheckConstraint(condition=models.Q(('hourly_rate__gte', 0)), name='hr_hourly_rate_nonnegative'), models.CheckConstraint(condition=models.Q(('monthly_salary__gte', 0)), name='hr_monthly_salary_nonnegative'), models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='hr_rate_period_valid')],
            },
        ),
        migrations.CreateModel(
            name='HrPayrollAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(db_index=True, help_text='Первый день месяца', verbose_name='Месяц')),
                ('kind', models.CharField(choices=[('accrual', 'Дополнительное начисление'), ('premium', 'Премия'), ('contract_payment', 'Выплата по договору'), ('bonus', 'Бонус'), ('deduction', 'Удержание')], max_length=32, verbose_name='Вид')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Подтверждено')], db_index=True, default='draft', max_length=16, verbose_name='Статус')),
                ('description', models.CharField(max_length=255, verbose_name='Основание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_hr_payroll_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='Подтвердил')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hr_payroll_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_payroll_adjustments', to='employees.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Корректировка расчёта',
                'verbose_name_plural': 'Корректировки расчёта',
                'ordering': ('-month', 'employee__full_name', 'kind', 'id'),
                'indexes': [models.Index(fields=['month', 'status', 'employee'], name='hr_adjust_month_status_emp_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='hr_payroll_adjustment_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='HrPayrollAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление'), ('approve', 'Подтверждение'), ('export', 'Экспорт')], max_length=16, verbose_name='Действие')),
                ('object_type', models.CharField(max_length=64, verbose_name='Тип объекта')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name='ID объекта')),
                ('month', models.DateField(blank=True, db_index=True, null=True, verbose_name='Месяц')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Изменения')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_payroll_audit_events', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_payroll_audit_events', to='employees.employee', verbose_name='Сотрудник отчёта')),
            ],
            options={
                'verbose_name': 'Событие журнала расчёта',
                'verbose_name_plural': 'Журнал расчёта',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['month', 'created_at'], name='hr_audit_month_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='HrTimesheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(db_index=True, verbose_name='Дата')),
                ('planned_minutes', models.PositiveIntegerField(default=0, verbose_name='План, минут')),
                ('worked_minutes', models.PositiveIntegerField(default=0, verbose_name='Отработано, минут')),
                ('late_minutes', models.PositiveIntegerField(default=0, verbose_name='Опоздание, минут')),
                ('internship_minutes', models.PositiveIntegerField(default=0, verbose_name='Стажировка, минут')),
                ('source', models.CharField(choices=[('manual', 'Вручную'), ('import', 'Импорт')], default='manual', max_length=16, verbose_name='Источник')),
                ('source_key', models.CharField(blank=True, max_length=128, verbose_name='Ключ источника')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_timesheet_entries', to='employees.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Строка табеля',
                'verbose_name_plural': 'Строки табеля',
                'ordering': ('-work_date', 'employee__full_name'),
                'indexes': [models.Index(fields=['work_date', 'employee'], name='hr_timesheet_date_emp_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'work_date'), name='hr_unique_employee_timesheet_day'), models.CheckConstraint(condition=models.Q(('internship_minutes__lte', models.F('worked_minutes'))), name='hr_internship_within_worked')],
            },
        ),
    ]
