# Generated by Django 6.0 on 2026-07-19 15:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # На проде leaf shipping = 0011_shipping_discrepancy_state (без 0012–0014).
        ('shipping', '0011_shipping_discrepancy_state'),
        ('sku', '0010_sku_weight_gross_kg_sku_weight_net_kg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivingDistributionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiving_order_id', models.CharField(db_index=True, help_text='PR-… из audit.OrderAuditEntry, без отдельной модели приёмки', max_length=64, unique=True, verbose_name='Номер головной приёмки')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлена'), ('returned', 'Возвращена на исправление'), ('confirmed', 'Подтверждена'), ('awaiting_receiving', 'Ожидает приемки'), ('receiving', 'Приемка начата'), ('partial', 'Принята частично'), ('done', 'Принята полностью'), ('discrepancy', 'Есть расхождения'), ('closed', 'Закрыта'), ('cancelled', 'Отменена')], db_index=True, default='draft', max_length=32, verbose_name='Статус плана')),
                ('client_request_id', models.CharField(blank=True, db_index=True, default='', help_text='Защита от повторной отправки формы', max_length=64, verbose_name='Идемпотентный ключ формы')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('eta_at', models.DateTimeField(blank=True, null=True, verbose_name='Плановое прибытие')),
                ('expected_units', models.PositiveIntegerField(default=0, verbose_name='Заявлено единиц')),
                ('expected_boxes', models.PositiveIntegerField(default=0, verbose_name='Примерно коробов')),
                ('expected_pallets', models.PositiveIntegerField(default=0, verbose_name='Примерно палет')),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=64, verbose_name='Машина')),
                ('driver_name', models.CharField(blank=True, default='', max_length=128, verbose_name='Водитель')),
                ('driver_phone', models.CharField(blank=True, default='', max_length=64, verbose_name='Телефон')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiving_distribution_plans', to='sku.agency', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receiving_distribution_plans', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'План приёмки с распределением',
                'verbose_name_plural': 'Планы приёмки с распределением',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ReceivingDistributionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(db_index=True, max_length=128, verbose_name='Артикул')),
                ('barcode', models.CharField(blank=True, default='', max_length=128, verbose_name='Штрихкод')),
                ('name', models.CharField(blank=True, default='', max_length=512, verbose_name='Наименование')),
                ('size', models.CharField(blank=True, default='', max_length=128, verbose_name='Размер / характеристика')),
                ('qty_total', models.PositiveIntegerField(verbose_name='Общее количество')),
                ('comment', models.CharField(blank=True, default='', max_length=512, verbose_name='Комментарий')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving_distribution_items', to='sku.sku', verbose_name='SKU')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='receiving_distribution.receivingdistributionplan', verbose_name='План')),
            ],
            options={
                'verbose_name': 'Товар плана распределения',
                'verbose_name_plural': 'Товары плана распределения',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReceivingDistributionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=64, verbose_name='Действие')),
                ('role', models.CharField(blank=True, default='', max_length=64, verbose_name='Роль')),
                ('object_type', models.CharField(blank=True, default='', max_length=64, verbose_name='Тип объекта')),
                ('object_id', models.CharField(blank=True, default='', max_length=64, verbose_name='ID объекта')),
                ('old_value', models.JSONField(blank=True, default=dict)),
                ('new_value', models.JSONField(blank=True, default=dict)),
                ('reason', models.CharField(blank=True, default='', max_length=512, verbose_name='Причина')),
                ('source', models.CharField(blank=True, default='', max_length=64, verbose_name='Источник')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving_distribution_events', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='receiving_distribution.receivingdistributionplan', verbose_name='План')),
            ],
            options={
                'verbose_name': 'Событие распределения',
                'verbose_name_plural': 'События распределения',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ReceivingDistributionDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('kind', models.CharField(choices=[('marketplace', 'Маркетплейс'), ('storage_fullbox', 'Хранение FullBox'), ('other', 'Другое')], default='marketplace', max_length=32, verbose_name='Тип')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Название направления')),
                ('marketplace_name', models.CharField(blank=True, default='', max_length=64, verbose_name='Маркетплейс (текст)')),
                ('destination_warehouse', models.CharField(blank=True, default='', max_length=255, verbose_name='Склад назначения')),
                ('cluster', models.CharField(blank=True, default='', max_length=128, verbose_name='Кластер')),
                ('supply_number', models.CharField(blank=True, default='', max_length=128, verbose_name='Номер поставки')),
                ('slot_date', models.DateField(blank=True, null=True, verbose_name='Дата поставки')),
                ('slot_time', models.CharField(blank=True, default='', max_length=64, verbose_name='Таймслот')),
                ('delivery_type', models.CharField(blank=True, default='', max_length=32, verbose_name='Способ доставки')),
                ('expected_units', models.PositiveIntegerField(default=0, verbose_name='Заявлено единиц')),
                ('expected_boxes', models.PositiveIntegerField(default=0, verbose_name='Коробов')),
                ('expected_pallets', models.PositiveIntegerField(default=0, verbose_name='Палет')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Вес, кг')),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Объём, м³')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('awaiting_receiving', 'Ожидает приемки'), ('receiving', 'Принимается'), ('partial', 'Принято частично'), ('done', 'Принято полностью'), ('discrepancy', 'Есть расхождения'), ('ready_to_ship', 'Готово к отгрузке'), ('in_logistics', 'Передано логисту'), ('shipped', 'Отгружено'), ('cancelled', 'Отменено')], db_index=True, default='awaiting_receiving', max_length=32, verbose_name='Статус направления')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving_distribution_directions', to='sku.market', verbose_name='Маркетплейс')),
                ('shipping_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving_distribution_directions', to='shipping.shippingorder', verbose_name='Связанная отгрузка')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='receiving_distribution.receivingdistributionplan', verbose_name='План')),
            ],
            options={
                'verbose_name': 'Направление распределения',
                'verbose_name_plural': 'Направления распределения',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReceivingDistributionAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(verbose_name='Количество по направлению')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='receiving_distribution.receivingdistributiondirection', verbose_name='Направление')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='receiving_distribution.receivingdistributionitem', verbose_name='Товар')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='receiving_distribution.receivingdistributionplan', verbose_name='План')),
            ],
            options={
                'verbose_name': 'Распределение по направлению',
                'verbose_name_plural': 'Распределения по направлениям',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='receivingdistributionplan',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id', ''), _negated=True), fields=('agency', 'client_request_id'), name='uniq_rd_plan_agency_client_request'),
        ),
        migrations.AddConstraint(
            model_name='receivingdistributionitem',
            constraint=models.UniqueConstraint(fields=('plan', 'sku_code'), name='uniq_rd_item_plan_sku'),
        ),
        migrations.AddConstraint(
            model_name='receivingdistributionallocation',
            constraint=models.UniqueConstraint(fields=('item', 'direction'), name='uniq_rd_alloc_item_direction'),
        ),
        migrations.AddConstraint(
            model_name='receivingdistributionallocation',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='rd_alloc_qty_positive'),
        ),
    ]
