"""
Django settings for fullbox project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import json
import os
from pathlib import Path
from urllib.parse import urlsplit, urlunsplit

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file(path: Path) -> None:
    if not path.exists():
        return
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except OSError:
        return
    for line in lines:
        raw = line.strip()
        if not raw or raw.startswith("#") or "=" not in raw:
            continue
        key, value = raw.split("=", 1)
        key = key.strip()
        value = value.strip()
        if not key or key in os.environ:
            continue
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
            value = value[1:-1]
        os.environ[key] = value


for env_path in (
    Path(os.environ["FULLBOX_ENV_FILE"]) if os.environ.get("FULLBOX_ENV_FILE") else None,
    BASE_DIR.parent / ".env",
    BASE_DIR / ".env",
):
    if env_path is not None:
        _load_env_file(env_path)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    'django-insecure-b4cpck9y1ko7ok3$qx^z8vt%rt0*de^@rd%oorc%_8*3&a^l*s',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() == "true"
try:
    SLOW_REQUEST_LOG_SECONDS = float(os.environ.get("SLOW_REQUEST_LOG_SECONDS", "1.5"))
except (TypeError, ValueError):
    SLOW_REQUEST_LOG_SECONDS = 1.5

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")
    if host.strip()
]


def _build_csrf_trusted_origins(raw: str) -> list[str]:
    origins: list[str] = []
    for item in raw.split(","):
        value = item.strip()
        if not value:
            continue
        if value.startswith("http://") or value.startswith("https://"):
            origins.append(value)
            continue
        # Behind TLS nginx / CDN we only need https; include http for bare local hosts.
        if value in {"127.0.0.1", "localhost"}:
            origins.append(f"http://{value}")
        origins.append(f"https://{value}")
    return origins


CSRF_TRUSTED_ORIGINS = _build_csrf_trusted_origins(
    os.environ.get("CSRF_TRUSTED_ORIGINS", ",".join(ALLOWED_HOSTS))
)
# Trust X-Forwarded-Proto from nginx so CSRF/cookie Secure flags match HTTPS.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = os.environ.get("USE_X_FORWARDED_HOST", "true").lower() == "true"
CSRF_COOKIE_SECURE = os.environ.get("CSRF_COOKIE_SECURE", "true").lower() == "true"
SESSION_COOKIE_SECURE = os.environ.get("SESSION_COOKIE_SECURE", "true").lower() == "true"
CSRF_COOKIE_SAMESITE = os.environ.get("CSRF_COOKIE_SAMESITE", "Lax")
SESSION_COOKIE_SAMESITE = os.environ.get("SESSION_COOKIE_SAMESITE", "Lax")
AI_SUPPORT_DIAGNOSTICS_ENABLED = (
    os.environ.get("AI_SUPPORT_DIAGNOSTICS_ENABLED", "false").lower() == "true"
)
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "").strip()
AI_SUPPORT_OPENAI_MODEL = os.environ.get("AI_SUPPORT_OPENAI_MODEL", "").strip()
AI_SUPPORT_OPENAI_BASE_URL = os.environ.get(
    "AI_SUPPORT_OPENAI_BASE_URL", "https://api.openai.com/v1"
).strip()
try:
    AI_SUPPORT_OPENAI_TIMEOUT_SECONDS = max(
        int(os.environ.get("AI_SUPPORT_OPENAI_TIMEOUT_SECONDS", "45")),
        10,
    )
except (TypeError, ValueError):
    AI_SUPPORT_OPENAI_TIMEOUT_SECONDS = 45
AGENT_SHARED_TOKEN = os.environ.get("FULLBOX_AGENT_TOKEN", "")
AGENT_LEGACY_ALLOWED_NETWORKS = tuple(
    value.strip()
    for value in os.environ.get(
        "AGENT_LEGACY_ALLOWED_NETWORKS",
        "192.168.1.0/24,127.0.0.0/8,::1/128",
    ).split(",")
    if value.strip()
)
AGENT_ENROLLMENT_TTL_SECONDS = int(os.environ.get("AGENT_ENROLLMENT_TTL_SECONDS", "600"))
AGENT_COMMAND_DELIVERY_LEASE_SECONDS = int(
    os.environ.get("AGENT_COMMAND_DELIVERY_LEASE_SECONDS", "60")
)
USE_OTG_REACHTRUCK_PLANNER = os.environ.get("USE_OTG_REACHTRUCK_PLANNER", "False").lower() == "true"
try:
    REACHTRUCK_INVENTORY_LEASE_SECONDS = max(
        int(os.environ.get("REACHTRUCK_INVENTORY_LEASE_SECONDS", "1200")),
        60,
    )
except (TypeError, ValueError):
    REACHTRUCK_INVENTORY_LEASE_SECONDS = 1200



def _json_object_env(name: str) -> dict:
    raw = os.environ.get(name, "").strip()
    if not raw:
        return {}
    try:
        value = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"{name} must contain a valid JSON object") from exc
    if not isinstance(value, dict):
        raise RuntimeError(f"{name} must contain a JSON object")
    return value


FBS_MODULE_ENABLED = os.environ.get("FBS_MODULE_ENABLED", "False").lower() == "true"
FBS_ORDER_PULL_ENABLED = os.environ.get("FBS_ORDER_PULL_ENABLED", "False").lower() == "true"
FBS_STATUS_PULL_ENABLED = os.environ.get("FBS_STATUS_PULL_ENABLED", "False").lower() == "true"
FBS_OUTBOX_ENABLED = os.environ.get("FBS_OUTBOX_ENABLED", "False").lower() == "true"
FBS_WAREHOUSE_WRITES_ENABLED = os.environ.get("FBS_WAREHOUSE_WRITES_ENABLED", "False").lower() == "true"
FBS_MARKING_PUSH_ENABLED = os.environ.get("FBS_MARKING_PUSH_ENABLED", "False").lower() == "true"
FBS_STOCK_PUSH_ENABLED = os.environ.get("FBS_STOCK_PUSH_ENABLED", "False").lower() == "true"
FBS_BILLING_ENABLED = os.environ.get("FBS_BILLING_ENABLED", "False").lower() == "true"
FBS_STOCK_CLAIM_SECONDS = int(os.environ.get("FBS_STOCK_CLAIM_SECONDS", "30"))
FBS_OZON_STOCK_MIN_INTERVAL_SECONDS = int(
    os.environ.get("FBS_OZON_STOCK_MIN_INTERVAL_SECONDS", "120")
)
FBS_STOCK_CATALOG_RETRY_SECONDS = int(
    os.environ.get("FBS_STOCK_CATALOG_RETRY_SECONDS", "600")
)
FBS_STOCK_CATALOG_BATCH_LIMIT = int(
    os.environ.get("FBS_STOCK_CATALOG_BATCH_LIMIT", "50")
)
FBS_ZONE_CODE = os.environ.get("FBS_ZONE_CODE", "FBS").strip().upper() or "FBS"
FBS_MARKETPLACE_CREDENTIALS = _json_object_env("FBS_MARKETPLACE_CREDENTIALS")
FBS_LABEL_ROOT = Path(
    os.environ.get("FBS_LABEL_ROOT", str(BASE_DIR / "private_media" / "fbs_labels"))
).expanduser()


# Application definition

INSTALLED_APPS = [
    "channels",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "widget_tweaks",
    "client_cabinet",
    "developer_cabinet",
    "audit",
    "sku",
    "processing_app",
    "processing_reachtruck",
    "orders",
    "receiving_distribution",
    "receiving_cz",
    "processing_cz",
    "shipping",
    "logistics",
    "employees",
    "hr",
    "head_manager",
    "warehouse_goods.apps.WarehouseGoodsConfig",
    "processing_head",
    "processing_worker",
    "reachtruck",
    "otg_reachtruck",
    "reachtruck_free",
    "reachtruck_box_move",
    "inventory.apps.InventoryConfig",
    "reachtruck_inventory.apps.ReachtruckInventoryConfig",
    "super_car",
    "todo",
    "market_sync",
    "fbs.apps.FbsConfig",
    "wms_new.apps.WmsNewConfig",
    "teammanager",
    "billing",
    "accountant",
    "sklad",
    "stockmap",
    "labels",
    "marking",
    "agent",
    "ai_support.apps.AiSupportConfig",
    "revisor",
]

MOYSKLAD_BILLING_ENABLED = os.environ.get("MOYSKLAD_BILLING_ENABLED", "False").lower() == "true"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'fullbox.middleware.SlowRequestLoggingMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'fullbox.middleware.LoginRateLimitMiddleware',
    'ai_support.middleware.EmployeeAiSupportAnnouncementMiddleware',
    'fullbox.middleware.AuthenticatedIdleTimeoutMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fullbox.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'teammanager.context.team_cabinet',
                'todo.context_processors.task_attention',
            ],
        },
    },
]

WSGI_APPLICATION = 'fullbox.wsgi.application'
ASGI_APPLICATION = 'fullbox.asgi.application'

REDIS_URL = os.environ.get("REDIS_URL", "").strip()


def _redis_cache_location(redis_url: str) -> str:
    explicit_url = os.environ.get("REDIS_CACHE_URL", "").strip()
    if explicit_url:
        return explicit_url
    if not redis_url:
        return ""
    try:
        parsed = urlsplit(redis_url)
        if parsed.scheme not in {"redis", "rediss"}:
            return redis_url
        database = int(parsed.path.strip("/") or 0)
        return urlunsplit(parsed._replace(path=f"/{database + 1}"))
    except (TypeError, ValueError):
        return redis_url


REDIS_CACHE_URL = _redis_cache_location(REDIS_URL)
FULLBOX_REALTIME_ENABLED = os.environ.get("FULLBOX_REALTIME_ENABLED", "true").lower() == "true"
FULLBOX_REALTIME_AGENT_IDS = {
    value.strip()
    for value in os.environ.get("FULLBOX_REALTIME_AGENT_IDS", "").split(",")
    if value.strip()
}

if REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [REDIS_URL],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }

if REDIS_CACHE_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_CACHE_URL,
            "KEY_PREFIX": "fullbox",
            "TIMEOUT": 300,
            "OPTIONS": {
                "socket_connect_timeout": 1,
                "socket_timeout": 2,
            },
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "fullbox-local",
        }
    }


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

db_name = os.environ.get("DB_NAME")
db_user = os.environ.get("DB_USER")
db_password = os.environ.get("DB_PASSWORD")
db_host = os.environ.get("DB_HOST", "127.0.0.1")
db_port = os.environ.get("DB_PORT", "5432")
try:
    db_conn_max_age = max(0, min(int(os.environ.get("DB_CONN_MAX_AGE", "60")), 3600))
except (TypeError, ValueError):
    db_conn_max_age = 60
try:
    db_work_mem_mb = max(4, min(int(os.environ.get("DB_WORK_MEM_MB", "16")), 64))
except (TypeError, ValueError):
    db_work_mem_mb = 16

if db_name and db_user and db_password:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': db_name,
            'USER': db_user,
            'PASSWORD': db_password,
            'HOST': db_host,
            'PORT': db_port,
            'CONN_MAX_AGE': db_conn_max_age,
            'CONN_HEALTH_CHECKS': True,
            'OPTIONS': {
                'options': f'-c work_mem={db_work_mem_mb}MB',
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

LOGIN_URL = "/login/"
FBS_QR_LOGIN_ALLOWED_IPS = tuple(
    value.strip()
    for value in os.environ.get("FBS_QR_LOGIN_ALLOWED_IPS", "192.168.1.1").split(",")
    if value.strip()
)
AUTHENTICATED_IDLE_TIMEOUT_SECONDS = int(
    os.environ.get("AUTHENTICATED_IDLE_TIMEOUT_SECONDS", "1800")
)
LOGIN_RATE_LIMIT_WINDOW_SECONDS = int(
    os.environ.get("LOGIN_RATE_LIMIT_WINDOW_SECONDS", "600")
)
LOGIN_RATE_LIMIT_IP_FAILURES = int(
    os.environ.get("LOGIN_RATE_LIMIT_IP_FAILURES", "30")
)
LOGIN_RATE_LIMIT_USERNAME_FAILURES = int(
    os.environ.get("LOGIN_RATE_LIMIT_USERNAME_FAILURES", "10")
)
CSRF_FAILURE_VIEW = "fullbox.views.csrf_failure"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Крупные заявки на приёмку (сотни строк) шлют 9+ полей на позицию.
# Дефолт Django = 1000 → TooManyFieldsSent / HTTP 400 при сохранении.
DATA_UPLOAD_MAX_NUMBER_FIELDS = int(
    os.environ.get("DATA_UPLOAD_MAX_NUMBER_FIELDS", "50000")
)

JOURNAL_REMOTE_URL = os.environ.get("JOURNAL_REMOTE_URL", "").strip()
JOURNAL_REMOTE_CACHE_SECONDS = int(
    os.environ.get("JOURNAL_REMOTE_CACHE_SECONDS", "300")
)
PRINT_AGENT_TOKEN = os.environ.get("PRINT_AGENT_TOKEN", "").strip()
_fullbox_agent_setup_path = Path(
    os.environ.get(
        "FULLBOX_AGENT_SETUP_PATH",
        str(BASE_DIR / "private_releases" / "Fullbox.Agent.Setup.exe"),
    )
).expanduser()
if not _fullbox_agent_setup_path.is_absolute():
    _fullbox_agent_setup_path = BASE_DIR / _fullbox_agent_setup_path
FULLBOX_AGENT_SETUP_PATH = _fullbox_agent_setup_path

_fullbox_tsd_apk_path = Path(
    os.environ.get(
        "FULLBOX_TSD_APK_PATH",
        str(BASE_DIR / "private_releases" / "Fullbox-TSD.apk"),
    )
).expanduser()
if not _fullbox_tsd_apk_path.is_absolute():
    _fullbox_tsd_apk_path = BASE_DIR / _fullbox_tsd_apk_path
FULLBOX_TSD_APK_PATH = _fullbox_tsd_apk_path
try:
    FULLBOX_TSD_VERSION_CODE = max(1, int(os.environ.get("FULLBOX_TSD_VERSION_CODE", "2")))
except (TypeError, ValueError):
    FULLBOX_TSD_VERSION_CODE = 2
FULLBOX_TSD_VERSION_NAME = os.environ.get("FULLBOX_TSD_VERSION_NAME", "1.1.0-debug").strip()
FULLBOX_TSD_APPLICATION_ID = os.environ.get(
    "FULLBOX_TSD_APPLICATION_ID", "ru.fullbox.tsd.debug"
).strip()
FULLBOX_TSD_UPDATE_REQUIRED = os.environ.get(
    "FULLBOX_TSD_UPDATE_REQUIRED", "false"
).lower() == "true"
WAREHOUSE_TEMP_NOMENCLATURE_ENABLED = False

# Telegram-уведомления по чатам (односторонние, сотрудникам)
TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "").strip()
TELEGRAM_BOT_USERNAME = os.environ.get("TELEGRAM_BOT_USERNAME", "").strip()
TELEGRAM_WEBHOOK_SECRET = os.environ.get("TELEGRAM_WEBHOOK_SECRET", "").strip()
TELEGRAM_CHATS_ALERT_CHAT_ID = os.environ.get("TELEGRAM_CHATS_ALERT_CHAT_ID", "").strip()
FULLBOX_LK_BASE_URL = os.environ.get("FULLBOX_LK_BASE_URL", "").strip()
FULLBOX_CHATS_ENABLED = os.environ.get("FULLBOX_CHATS_ENABLED", "true").lower() == "true"
