# Generated by Django 6.0 on 2026-07-18 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_charge_tariff_snapshot"),
        ("head_manager", "0004_owncompany_tax_mode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="billingservice",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "Услуга биллинга",
                "verbose_name_plural": "Услуги биллинга",
            },
        ),
        migrations.AddField(
            model_name="applicationcharge",
            name="own_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="billing_charges",
                to="head_manager.owncompany",
                verbose_name="Компания обслуживания FullBox",
            ),
        ),
        migrations.AddField(
            model_name="applicationcharge",
            name="price_source",
            field=models.CharField(
                blank=True,
                default="client_tariff",
                max_length=64,
                verbose_name="Источник цены (код)",
            ),
        ),
        migrations.AddField(
            model_name="applicationcharge",
            name="vat_type_snapshot",
            field=models.CharField(blank=True, max_length=32, verbose_name="Формат НДС (снимок)"),
        ),
        migrations.AddField(
            model_name="billingservice",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="billing_services",
                to="billing.tariffcategory",
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="billingservice",
            name="default_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=14,
                null=True,
                verbose_name="Цена по умолчанию",
            ),
        ),
        migrations.AddField(
            model_name="billingservice",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="billingservice",
            name="sort_order",
            field=models.PositiveIntegerField(default=100, verbose_name="Порядок сортировки"),
        ),
        migrations.AddField(
            model_name="billingservice",
            name="used_in_billing",
            field=models.BooleanField(default=True, verbose_name="Используется в биллинге"),
        ),
    ]
