# Generated by Django 6.0 on 2026-07-18 12:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_clientinvoice_linked_acts'),
        ('sku', '0010_sku_weight_gross_kg_sku_weight_net_kg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta_volume_l', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=16, verbose_name='Корр. объём, л')),
                ('delta_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Корр. сумма')),
                ('reason', models.CharField(choices=[('bad_dims', 'Неверные габариты'), ('bad_qty', 'Ошибка в количестве'), ('bad_placement', 'Ошибка размещения'), ('bad_tariff', 'Неверный тариф'), ('client_agreement', 'Договорённость с клиентом'), ('free_storage', 'Бесплатное хранение'), ('tech_failure', 'Технический сбой'), ('compensation', 'Компенсация'), ('other', 'Иная причина')], default='other', max_length=32, verbose_name='Причина')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На согласовании'), ('approved', 'Согласовано'), ('rejected', 'Отклонено'), ('applied', 'Применено')], db_index=True, default='draft', max_length=16, verbose_name='Статус')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Корректировка хранения',
                'verbose_name_plural': 'Корректировки хранения',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StorageBillingError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('no_dims', 'Нет габаритов'), ('zero_dims', 'Нулевые габариты'), ('volume_too_large', 'Подозрительно большой объём'), ('volume_too_small', 'Подозрительно маленький объём'), ('no_tariff', 'Нет тарифа'), ('multi_tariff', 'Несколько тарифов'), ('double_count', 'Двойной учёт'), ('negative_stock', 'Отрицательный остаток'), ('after_ship', 'Начисление после отгрузки'), ('before_receive', 'Начисление до приёмки'), ('closed_period', 'Изменение закрытого периода'), ('volume_spike', 'Резкое изменение объёма'), ('wms_mismatch', 'Расхождение WMS и биллинга'), ('other', 'Прочее')], db_index=True, max_length=32, verbose_name='Тип')),
                ('severity', models.CharField(choices=[('info', 'Инфо'), ('warn', 'Предупреждение'), ('error', 'Ошибка')], default='error', max_length=16, verbose_name='Критичность')),
                ('day', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата')),
                ('sku_code', models.CharField(blank=True, max_length=128, verbose_name='SKU')),
                ('pallet_code', models.CharField(blank=True, max_length=128, verbose_name='Палета')),
                ('box_code', models.CharField(blank=True, max_length=128, verbose_name='Короб')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Детали')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ошибка биллинга хранения',
                'verbose_name_plural': 'Ошибки биллинга хранения',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StorageBillingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('month', models.PositiveIntegerField(verbose_name='Месяц')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('closing', 'Закрывается'), ('closed', 'Закрыт')], db_index=True, default='open', max_length=16, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Итого без НДС')),
                ('total_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='НДС')),
                ('checklist', models.JSONField(blank=True, default=dict, verbose_name='Чек-лист закрытия')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Период биллинга хранения',
                'verbose_name_plural': 'Периоды биллинга хранения',
                'ordering': ['-year', '-month', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StorageCalculationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_mode', models.CharField(choices=[('liter_day', 'За 1 литр в сутки'), ('liter_month', 'За 1 литр в месяц'), ('m3_day', 'За 1 м³ в сутки'), ('m3_month', 'За 1 м³ в месяц'), ('pallet_day', 'За палетоместо в сутки'), ('pallet_month', 'За палетоместо в месяц'), ('custom', 'Индивидуальная схема')], default='pallet_day', max_length=32, verbose_name='Способ тарификации')),
                ('month_mode', models.CharField(choices=[('calendar_prorate', 'Пропорционально календарным дням'), ('full_month', 'Полная стоимость за месяц'), ('avg_daily_volume', 'По среднесуточному объёму'), ('max_volume', 'По максимальному объёму за месяц')], default='calendar_prorate', max_length=32, verbose_name='Месячный режим')),
                ('day_counting', models.CharField(choices=[('include_both', 'День приёмки и отгрузки включаются'), ('include_receive', 'День приёмки включается'), ('include_ship', 'День отгрузки включается'), ('exclude_receive', 'День приёмки не включается'), ('exclude_ship', 'День отгрузки не включается'), ('after_placement', 'После размещения в ячейку'), ('after_free_period', 'После бесплатного периода')], default='include_both', max_length=32, verbose_name='Учёт дней')),
                ('free_period_type', models.CharField(choices=[('none', 'Без бесплатного периода'), ('hours', 'Часы'), ('calendar_days', 'Календарные дни'), ('work_days', 'Рабочие дни'), ('until_event', 'До события'), ('until_processing_done', 'До завершения обработки партии')], default='none', max_length=32, verbose_name='Бесплатный период')),
                ('free_period_value', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=12, verbose_name='Значение бесплатного периода')),
                ('volume_level', models.CharField(choices=[('unit', 'По единице товара'), ('box', 'По коробу'), ('pallet', 'По палете'), ('place', 'По занимаемому месту')], default='pallet', max_length=16, verbose_name='Уровень объёма')),
                ('space_coefficient_default', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=10, verbose_name='Коэффициент хранения по умолчанию')),
                ('rounding_mode', models.CharField(choices=[('none', 'Без округления'), ('liter', 'До целого литра'), ('10_l', 'До 10 литров'), ('50_l', 'До 50 литров'), ('100_l', 'До 100 литров'), ('0.01_m3', 'До 0,01 м³'), ('0.1_m3', 'До 0,1 м³'), ('1_m3', 'До 1 м³'), ('ceil', 'Всегда в большую сторону'), ('math', 'Математическое округление')], default='none', max_length=16, verbose_name='Округление объёма')),
                ('min_billable_volume', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=16, verbose_name='Мин. тарифицируемый объём')),
                ('min_amount_day', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Мин. сумма за день')),
                ('min_amount_month', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Мин. сумма за месяц')),
                ('missing_dims_policy', models.CharField(choices=[('skip', 'Не начислять'), ('fallback_tariff', 'Резервный тариф'), ('error_only', 'Только ошибка')], default='error_only', max_length=32, verbose_name='Нет габаритов')),
                ('snapshot_hour', models.PositiveSmallIntegerField(default=23, verbose_name='Час снимка (локальное время склада)')),
                ('timezone_name', models.CharField(default='Europe/Moscow', max_length=64, verbose_name='Часовой пояс склада')),
                ('accountant_comment', models.TextField(blank=True, verbose_name='Комментарий бухгалтера')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Правило расчёта хранения',
                'verbose_name_plural': 'Правила расчёта хранения',
            },
        ),
        migrations.CreateModel(
            name='StorageSnapshotLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Код SKU')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Наименование')),
                ('barcode', models.CharField(blank=True, max_length=128, verbose_name='Штрихкод')),
                ('box_code', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Короб')),
                ('pallet_code', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Палета')),
                ('zone_code', models.CharField(blank=True, max_length=64, verbose_name='Зона')),
                ('cell_code', models.CharField(blank=True, max_length=128, verbose_name='Ячейка')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=14, verbose_name='Количество')),
                ('length_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длина, мм')),
                ('width_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина, мм')),
                ('height_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота, мм')),
                ('unit_volume_l', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=16, verbose_name='Объём ед., л')),
                ('total_volume_l', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=16, verbose_name='Объём всего, л')),
                ('total_volume_m3', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=16, verbose_name='Объём всего, м³')),
                ('coefficient', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=10, verbose_name='Коэффициент')),
                ('billable_volume_l', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=16, verbose_name='Тариф. объём, л')),
                ('billable_volume_m3', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=16, verbose_name='Тариф. объём, м³')),
                ('volume_level', models.CharField(blank=True, max_length=16, verbose_name='Уровень')),
                ('dims_source', models.CharField(blank=True, max_length=64, verbose_name='Источник размеров')),
                ('status', models.CharField(choices=[('ok', 'OK'), ('no_dims', 'Нет габаритов')], db_index=True, default='ok', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Строка снимка хранения',
                'verbose_name_plural': 'Строки снимков хранения',
                'ordering': ['id'],
            },
        ),



















        migrations.AddField(
            model_name='billingstorageday',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Сумма без НДС'),
        ),
        migrations.AddField(
            model_name='billingstorageday',
            name='billable_volume_l',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=16, verbose_name='Тариф. объём, л'),
        ),
        migrations.AddField(
            model_name='billingstorageday',
            name='billable_volume_m3',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=16, verbose_name='Тариф. объём, м³'),
        ),
        migrations.AddField(
            model_name='billingstorageday',
            name='billing_mode',
            field=models.CharField(blank=True, max_length=32, verbose_name='Способ тарификации'),
        ),
        migrations.AddField(
            model_name='billingstorageday',
            name='box_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Коробов'),
        ),
        migrations.AddField(
            model_name='billingstorageday',
            name='coefficient_applied',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=10, verbose_name='Коэффициент'),
        ),
        migrations.AddField(
            model_name='billingstorageday',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Аудит расчёта'),
        ),
        migrations.AddField(
            model_name='billingstorageday',
            name='physical_volume_l',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=16, verbose_name='Физ. объём, л'),
        ),
        migrations.AddField(
            model_name='billingstorageday',
            name='physical_volume_m3',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=16, verbose_name='Физ. объём, м³'),
        ),
        migrations.AddField(
            model_name='billingstorageday',
            name='sku_unit_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Единиц товара'),
        ),
        migrations.AddField(
            model_name='billingstorageday',
            name='status',
            field=models.CharField(choices=[('preliminary', 'Предварительное'), ('calculated', 'Рассчитано'), ('needs_review', 'Требует проверки'), ('confirmed', 'Подтверждено'), ('in_invoice', 'Включено в счёт'), ('cancelled', 'Отменено')], db_index=True, default='preliminary', max_length=32, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='billingstorageday',
            name='tariff_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_days', to='billing.clienttariffversion', verbose_name='Редакция тарифа'),
        ),
        migrations.AddField(
            model_name='billingstorageday',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='НДС'),
        ),
        migrations.AddField(
            model_name='storageadjustment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_storage_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storageadjustment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_adjustments', to='sku.agency', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='storageadjustment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_storage_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storageadjustment',
            name='source_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_adjustments', to='billing.applicationcharge', verbose_name='Исходное начисление'),
        ),
        migrations.AddField(
            model_name='storageadjustment',
            name='source_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='billing.billingstorageday', verbose_name='Исходный день'),
        ),
        migrations.AddField(
            model_name='storagebillingerror',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_billing_errors', to='sku.agency', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='storagebillingerror',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_storage_billing_errors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storagebillingerror',
            name='storage_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errors', to='billing.billingstorageday'),
        ),
        migrations.AddField(
            model_name='storagebillingperiod',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_billing_periods', to='sku.agency', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='storagebillingperiod',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_storage_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storagebillingperiod',
            name='legal_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storage_billing_legal_periods', to='sku.agency', verbose_name='Юрлицо клиента'),
        ),
        migrations.AddField(
            model_name='storageadjustment',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='billing.storagebillingperiod', verbose_name='Период'),
        ),
        migrations.AddField(
            model_name='storagecalculationrule',
            name='tariff_version',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_rule', to='billing.clienttariffversion', verbose_name='Редакция тарифов'),
        ),
        migrations.AddField(
            model_name='billingstorageday',
            name='calculation_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_days', to='billing.storagecalculationrule', verbose_name='Правило расчёта'),
        ),
        migrations.AddIndex(
            model_name='billingstorageday',
            index=models.Index(fields=['status', 'day'], name='billing_bil_status_a687ed_idx'),
        ),
        migrations.AddField(
            model_name='storagesnapshotline',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.billingstorageday', verbose_name='День хранения'),
        ),
        migrations.AddField(
            model_name='storagesnapshotline',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_snapshot_lines', to='sku.sku', verbose_name='SKU'),
        ),
        migrations.AddIndex(
            model_name='storagebillingerror',
            index=models.Index(fields=['client', 'error_type', 'resolved_at'], name='billing_sto_client__eb405a_idx'),
        ),
        migrations.AddIndex(
            model_name='storagebillingerror',
            index=models.Index(fields=['day', 'severity'], name='billing_sto_day_c81b02_idx'),
        ),
        migrations.AddConstraint(
            model_name='storagebillingperiod',
            constraint=models.UniqueConstraint(fields=('client', 'legal_entity', 'year', 'month'), name='uniq_storage_billing_period'),
        ),
        migrations.AddIndex(
            model_name='storagesnapshotline',
            index=models.Index(fields=['day', 'status'], name='billing_sto_day_id_bdecc4_idx'),
        ),
        migrations.AddIndex(
            model_name='storagesnapshotline',
            index=models.Index(fields=['sku_code'], name='billing_sto_sku_cod_012f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='storagesnapshotline',
            index=models.Index(fields=['pallet_code'], name='billing_sto_pallet__e99f6e_idx'),
        ),
    ]
