# Generated by Django 6.0 on 2026-07-26
from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0022_client_invoice_supplier_snapshot"),
        ("sku", "0010_sku_weight_gross_kg_sku_weight_net_kg"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogisticsPriceLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("marketplace", models.CharField(choices=[("wb", "Wildberries"), ("ozon", "Ozon"), ("other", "Другое направление")], default="other", max_length=16, verbose_name="Маркетплейс")),
                ("warehouse_name", models.CharField(max_length=255, verbose_name="Склад / направление")),
                ("pickup_days", models.CharField(blank=True, max_length=128, verbose_name="Дни забора")),
                ("delivery_days", models.CharField(blank=True, max_length=128, verbose_name="Дни сдачи")),
                ("price_per_pallet", models.DecimalField(decimal_places=2, max_digits=14, verbose_name="Цена за паллету")),
                ("minimum_pallets", models.PositiveIntegerField(default=1, verbose_name="От паллет")),
                ("discount_percent", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5, verbose_name="Скидка, %")),
                ("comment", models.CharField(blank=True, max_length=255, verbose_name="Комментарий")),
                ("sort_order", models.PositiveIntegerField(default=100, verbose_name="Порядок")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активно")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name": "Строка прайса логистики", "verbose_name_plural": "Прайс логистики", "ordering": ["marketplace", "sort_order", "warehouse_name"]},
        ),
        migrations.CreateModel(
            name="ClientLogisticsTariff",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Название редакции")),
                ("version_number", models.PositiveIntegerField(default=1, verbose_name="Номер версии")),
                ("status", models.CharField(choices=[("draft", "Черновик"), ("active", "Действует"), ("archived", "Архив")], db_index=True, default="draft", max_length=16, verbose_name="Статус")),
                ("valid_from", models.DateField(default=django.utils.timezone.localdate, verbose_name="Действует с")),
                ("valid_to", models.DateField(blank=True, null=True, verbose_name="Действует до")),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="logistics_tariffs", to="sku.agency", verbose_name="Клиент")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_client_logistics_tariffs", to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name": "Редакция логистического тарифа клиента", "verbose_name_plural": "Редакции логистических тарифов клиентов", "ordering": ["client", "-valid_from", "-version_number"]},
        ),
        migrations.CreateModel(
            name="ClientLogisticsTariffItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("marketplace", models.CharField(choices=[("wb", "Wildberries"), ("ozon", "Ozon"), ("other", "Другое направление")], default="other", max_length=16, verbose_name="Маркетплейс")),
                ("warehouse_name", models.CharField(max_length=255, verbose_name="Склад / направление")),
                ("pickup_days", models.CharField(blank=True, max_length=128, verbose_name="Дни забора")),
                ("delivery_days", models.CharField(blank=True, max_length=128, verbose_name="Дни сдачи")),
                ("price_per_pallet", models.DecimalField(decimal_places=2, max_digits=14, verbose_name="Цена клиента за паллету")),
                ("minimum_pallets", models.PositiveIntegerField(default=1, verbose_name="От паллет")),
                ("discount_percent", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5, verbose_name="Скидка, %")),
                ("comment", models.CharField(blank=True, max_length=255, verbose_name="Комментарий")),
                ("sort_order", models.PositiveIntegerField(default=100, verbose_name="Порядок")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активно")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_line", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="client_tariff_items", to="billing.logisticspriceline", verbose_name="Строка основного прайса")),
                ("tariff", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="billing.clientlogisticstariff", verbose_name="Редакция тарифа")),
            ],
            options={"verbose_name": "Строка логистического тарифа клиента", "verbose_name_plural": "Строки логистических тарифов клиентов", "ordering": ["marketplace", "sort_order", "warehouse_name"]},
        ),
        migrations.AddIndex(model_name="logisticspriceline", index=models.Index(fields=["marketplace", "is_active"], name="billing_log_marketp_e9a926_idx")),
        migrations.AddIndex(model_name="clientlogisticstariff", index=models.Index(fields=["client", "status"], name="billing_cli_client__6d6531_idx")),
        migrations.AddConstraint(model_name="clientlogisticstariff", constraint=models.UniqueConstraint(fields=("client", "version_number"), name="uniq_client_logistics_tariff_version")),
        migrations.AddIndex(model_name="clientlogisticstariffitem", index=models.Index(fields=["tariff", "is_active"], name="billing_cli_tariff__39ebd2_idx")),
    ]
