# Generated by Django 6.0 on 2026-07-26
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("billing", "0023_logistics_price_lists")]

    operations = [
        migrations.AddField(
            model_name="applicationcharge",
            name="client_logistics_tariff",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="charges", to="billing.clientlogisticstariff", verbose_name="Редакция логистического тарифа"),
        ),
        migrations.AddField(
            model_name="applicationcharge",
            name="client_logistics_tariff_item",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="charges", to="billing.clientlogisticstariffitem", verbose_name="Направление логистического тарифа"),
        ),
    ]
