# Generated by Django 6.0 on 2026-07-18 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_super_car_role_and_user'),
        ('logistics', '0002_logisticstrip_carrier'),
        # Prod leaf is shipping.0011_shipping_discrepancy_state (локальные 0012–0014 не выкатываем).
        ('shipping', '0011_shipping_discrepancy_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRoutingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ready_for_routing', 'Готова к маршрутизации'), ('needs_clarification', 'Требуется уточнение'), ('routed', 'Рейс назначен'), ('in_transit', 'В пути'), ('delivered', 'Доставка завершена')], db_index=True, default='ready_for_routing', max_length=32)),
                ('reason_code', models.CharField(blank=True, choices=[('no_address', 'Отсутствует адрес'), ('bad_time_window', 'Неверное временное окно'), ('no_volume', 'Не указан объём'), ('no_weight', 'Не указан вес'), ('no_contacts', 'Отсутствуют контакты'), ('goods_not_ready', 'Товар не готов'), ('no_documents', 'Отсутствуют документы'), ('special_vehicle', 'Требуется специальный транспорт'), ('other', 'Другое')], default='', max_length=32)),
                ('reason_text', models.TextField(blank=True, default='')),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_resolves', to='employees.employee', verbose_name='Снял уточнение')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_returns', to='employees.employee', verbose_name='Вернул на уточнение')),
                ('shipping_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='routing_state', to='shipping.shippingorder', verbose_name='Заявка на отгрузку')),
            ],
            options={
                'verbose_name': 'Статус маршрутизации отгрузки',
                'verbose_name_plural': 'Статусы маршрутизации отгрузок',
                'indexes': [models.Index(fields=['status', '-updated_at'], name='logistics_s_status_092e18_idx')],
            },
        ),
    ]
