# Generated by Django 6.0 on 2026-07-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_shipping_routing_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticstrip',
            name='max_pallets',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Макс. паллет'),
        ),
        migrations.AddField(
            model_name='logisticstrip',
            name='max_volume_m3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Вместимость, м³'),
        ),
        migrations.AddField(
            model_name='logisticstrip',
            name='max_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Грузоподъёмность, кг'),
        ),
    ]
