# Generated by Django 6.0 on 2026-07-18 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_super_car_role_and_user'),
        ('logistics', '0004_trip_capacity_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticstrip',
            name='edit_version',
            field=models.PositiveIntegerField(
                db_index=True,
                default=1,
                help_text='Optimistic lock: увеличивается при каждом сохранении рейса',
                verbose_name='Версия редактирования',
            ),
        ),
        migrations.AddField(
            model_name='logisticstrip',
            name='editing_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='logistics_trips_editing',
                to='employees.employee',
                verbose_name='Сейчас на карточке',
            ),
        ),
        migrations.AddField(
            model_name='logisticstrip',
            name='editing_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Активность на карточке'),
        ),
        migrations.AddField(
            model_name='logisticstrip',
            name='last_edited_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='logistics_trips_last_edited',
                to='employees.employee',
                verbose_name='Последний редактор',
            ),
        ),
    ]
