# Generated by Django 6.0 on 2026-05-14 08:09

import django.db.models.deletion
import processing_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing_app', '0006_processingprintjob_copies_count'),
        ('sku', '0010_sku_weight_gross_kg_sku_weight_net_kg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingOrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=64, verbose_name='Номер заявки')),
                ('file', models.FileField(upload_to=processing_app.models.processing_attachment_upload_to, verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_order_attachments', to='sku.agency', verbose_name='Клиент')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_order_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Кто загрузил')),
            ],
            options={
                'verbose_name': 'Файл заявки на обработку',
                'verbose_name_plural': 'Файлы заявок на обработку',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['order_id', 'uploaded_at'], name='processing__order_i_0bbf92_idx'), models.Index(fields=['agency', 'order_id'], name='processing__agency__98cc0e_idx')],
            },
        ),
    ]
