# Generated by Django 6.0 on 2026-06-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing_app', '0008_processingcontainercodesequence'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='processingprintjob',
            index=models.Index(fields=['status', 'agent', 'created_at'], name='processing__status_622cce_idx'),
        ),
        migrations.AddIndex(
            model_name='processingprintjob',
            index=models.Index(fields=['agent', 'status', 'updated_at'], name='processing__agent_dde0ec_idx'),
        ),
    ]
