# Generated by Django 6.0 on 2026-08-25 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_employee_driver_role'),
        ('processing_app', '0011_split_container_code_sequences'),
        ('sku', '0010_sku_weight_gross_kg_sku_weight_net_kg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingWorkEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=96, unique=True)),
                ('operation_type', models.CharField(choices=[('operation_completed', 'Операция обработки завершена'), ('box_formed', 'Короб сформирован')], max_length=32)),
                ('order_id', models.CharField(db_index=True, max_length=64)),
                ('employee_name', models.CharField(blank=True, max_length=255)),
                ('operation_key', models.CharField(blank=True, max_length=128)),
                ('operation_label', models.CharField(blank=True, max_length=255)),
                ('card_id', models.CharField(blank=True, max_length=128)),
                ('container_code', models.CharField(blank=True, max_length=128)),
                ('units', models.PositiveIntegerField(default=0)),
                ('boxes', models.PositiveIntegerField(default=0)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_work_events', to='sku.agency')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_work_events', to='employees.employee')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_processing_work_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['employee', 'occurred_at'], name='processing__employe_9efb91_idx'), models.Index(fields=['operation_type', 'occurred_at'], name='processing__operati_b72020_idx'), models.Index(fields=['order_id', 'operation_type'], name='processing__order_i_a89b1f_idx')],
            },
        ),
    ]
