# Generated by Django 6.0 on 2026-07-15 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0011_shippingorder_parent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='shippingorder',
            new_name='shipping_sh_parent__f9f12b_idx',
            old_name='shipping_sh_parent__7a1c2d_idx',
        ),
    ]
