# Generated by Django 6.0 on 2026-07-15 10:31
# Prod branch dependency adjusted to 0012_shippingreservationunit.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0012_shippingreservationunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingorder',
            name='distribution_status',
            field=models.CharField(blank=True, choices=[('empty', 'Не заполнено'), ('partial', 'Заполнено частично'), ('complete', 'Заполнено полностью'), ('mismatch', 'Есть расхождения')], default='', help_text='Кэш статуса распределения по конечным складам (только Ozon).', max_length=16, verbose_name='Статус распределения Ozon'),
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='supply_number',
            field=models.CharField(blank=True, default='', help_text='Номер поставки маркетплейса; для Ozon. WB продолжает использовать wb_supply_barcode.', max_length=128, verbose_name='Номер поставки (Ozon)'),
        ),
        migrations.CreateModel(
            name='ShippingDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.CharField(max_length=255, verbose_name='Конечный склад')),
                ('warehouse_code', models.CharField(blank=True, default='', max_length=100, verbose_name='Код склада Ozon')),
                ('region', models.CharField(blank=True, default='', max_length=255, verbose_name='Регион')),
                ('address', models.TextField(blank=True, default='', verbose_name='Адрес')),
                ('planned_units', models.PositiveIntegerField(default=0, verbose_name='Единиц (план)')),
                ('planned_boxes', models.PositiveIntegerField(default=0, verbose_name='Коробов (план)')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='shipping.shippingorder', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Конечный склад Ozon',
                'verbose_name_plural': 'Конечные склады Ozon',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShippingDestinationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipping.shippingdestination', verbose_name='Конечный склад')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_items', to='shipping.shippingorderitem', verbose_name='Позиция заявки')),
            ],
            options={
                'verbose_name': 'Распределение позиции Ozon',
                'verbose_name_plural': 'Распределения позиций Ozon',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='shippingdestination',
            index=models.Index(fields=['order', 'sort_order'], name='shipping_sh_order_i_5360ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='shippingdestination',
            constraint=models.UniqueConstraint(fields=('order', 'warehouse_name'), name='shipping_destination_unique_name_per_order'),
        ),
        migrations.AddIndex(
            model_name='shippingdestinationitem',
            index=models.Index(fields=['order_item', 'destination'], name='shipping_sh_order_i_cde46f_idx'),
        ),
        migrations.AddConstraint(
            model_name='shippingdestinationitem',
            constraint=models.UniqueConstraint(fields=('destination', 'order_item'), name='shipping_destination_item_unique'),
        ),
    ]
