# Generated by Django 6.0 on 2026-07-18 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0011_shipping_discrepancy_state'),
        ('shipping', '0013_ozon_destinations_distribution'),
    ]

    operations = [
    ]
