# Generated by Django 6.0 on 2026-07-14 07:44

import client_cabinet.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sku', '0010_sku_weight_gross_kg_sku_weight_net_kg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=64, verbose_name='Номер заявки')),
                ('file', models.FileField(upload_to=client_cabinet.models.other_attachment_upload_to, verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_request_attachments', to='sku.agency', verbose_name='Клиент')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_request_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Кто загрузил')),
            ],
            options={
                'verbose_name': 'Файл прочей заявки',
                'verbose_name_plural': 'Файлы прочих заявок',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['order_id', 'uploaded_at'], name='client_cabi_order_i_cf5f23_idx'), models.Index(fields=['agency', 'order_id'], name='client_cabi_agency__0ecbb3_idx')],
            },
        ),
    ]
