# Generated by Django 6.0 on 2026-07-14 08:00

import client_cabinet.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_cabinet', '0001_other_request_attachments'),
        ('sku', '0010_sku_weight_gross_kg_sku_weight_net_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFinanceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_kind', models.CharField(choices=[('invoice', 'Счёт'), ('upd', 'УПД'), ('act', 'Акт')], default='invoice', max_length=16, verbose_name='Тип')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('number', models.CharField(blank=True, max_length=64, verbose_name='Номер')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('issued', 'Выставлен'), ('paid', 'Оплачен'), ('cancelled', 'Отменён')], default='issued', max_length=16, verbose_name='Статус')),
                ('period', models.CharField(blank=True, help_text='YYYY-MM', max_length=7, verbose_name='Период')),
                ('issued_at', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('order_type', models.CharField(blank=True, max_length=32, verbose_name='Тип заявки')),
                ('order_id', models.CharField(blank=True, max_length=64, verbose_name='Номер заявки')),
                ('external_url', models.CharField(blank=True, max_length=512, verbose_name='Внешняя ссылка')),
                ('file', models.FileField(blank=True, null=True, upload_to=client_cabinet.models.finance_document_upload_to, verbose_name='Файл')),
                ('note', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_documents', to='sku.agency', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Финансовый документ',
                'verbose_name_plural': 'Финансовые документы',
                'ordering': ['-issued_at', '-id'],
                'indexes': [models.Index(fields=['agency', 'doc_kind', 'issued_at'], name='client_cabi_agency__44b394_idx'), models.Index(fields=['agency', 'period'], name='client_cabi_agency__477e01_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClientServiceCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('storage', 'Хранение'), ('receiving', 'Приёмка'), ('shipping', 'Отгрузка'), ('extra', 'Доп. услуги')], default='extra', max_length=16, verbose_name='Тип услуги')),
                ('description', models.CharField(max_length=512, verbose_name='Описание')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Сумма')),
                ('period', models.CharField(blank=True, help_text='YYYY-MM', max_length=7, verbose_name='Период')),
                ('charged_at', models.DateField(blank=True, null=True, verbose_name='Дата начисления')),
                ('status', models.CharField(choices=[('open', 'Открыто'), ('invoiced', 'В счёте'), ('paid', 'Оплачено'), ('cancelled', 'Отменено')], default='open', max_length=16, verbose_name='Статус')),
                ('order_type', models.CharField(blank=True, max_length=32, verbose_name='Тип заявки')),
                ('order_id', models.CharField(blank=True, max_length=64, verbose_name='Номер заявки')),
                ('source_key', models.CharField(blank=True, db_index=True, help_text='Идемпотентный ключ автосоздания (например shipping-tn:12)', max_length=128, verbose_name='Ключ источника')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_charges', to='sku.agency', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Начисление услуги',
                'verbose_name_plural': 'Начисления услуг',
                'ordering': ['-charged_at', '-id'],
                'indexes': [models.Index(fields=['agency', 'period', 'service_type'], name='client_cabi_agency__a921c0_idx'), models.Index(fields=['agency', 'status'], name='client_cabi_agency__4002e9_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_key', ''), _negated=True), fields=('agency', 'source_key'), name='client_cabinet_charge_unique_source')],
            },
        ),
    ]
