# Generated by Django 6.0 on 2026-07-14 08:52

import client_cabinet.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_cabinet', '0002_finance_billing'),
        ('sku', '0010_sku_weight_gross_kg_sku_weight_net_kg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_role', models.CharField(choices=[('client', 'Клиент'), ('staff', 'FullBox')], default='client', max_length=16, verbose_name='Роль автора')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('is_read_by_client', models.BooleanField(default=False, verbose_name='Прочитано клиентом')),
                ('is_read_by_staff', models.BooleanField(default=False, verbose_name='Прочитано сотрудником')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='sku.agency', verbose_name='Клиент')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Сообщение чата ЛК',
                'verbose_name_plural': 'Сообщения чата ЛК',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClientChatAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=client_cabinet.models.chat_attachment_upload_to, verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='client_cabinet.clientchatmessage', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Вложение чата ЛК',
                'verbose_name_plural': 'Вложения чата ЛК',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('status', 'Статус'), ('comment', 'Комментарий'), ('finance', 'Финансы'), ('chat', 'Чат'), ('system', 'Система')], default='system', max_length=16, verbose_name='Тип')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('detail_url', models.CharField(blank=True, max_length=512, verbose_name='Ссылка')),
                ('priority', models.CharField(default='normal', max_length=16, verbose_name='Приоритет')),
                ('source_key', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Ключ источника')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитано в')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lk_notifications', to='sku.agency', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Уведомление ЛК',
                'verbose_name_plural': 'Уведомления ЛК',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='clientchatmessage',
            index=models.Index(fields=['agency', 'created_at'], name='client_cabi_agency__5e55d1_idx'),
        ),
        migrations.AddIndex(
            model_name='clientchatmessage',
            index=models.Index(fields=['agency', 'author_role', 'is_read_by_client'], name='client_cabi_agency__a60bf5_idx'),
        ),
        migrations.AddIndex(
            model_name='clientnotification',
            index=models.Index(fields=['agency', 'is_read', 'created_at'], name='client_cabi_agency__658870_idx'),
        ),
        migrations.AddIndex(
            model_name='clientnotification',
            index=models.Index(fields=['agency', 'notif_type'], name='client_cabi_agency__ff6761_idx'),
        ),
        migrations.AddConstraint(
            model_name='clientnotification',
            constraint=models.UniqueConstraint(condition=models.Q(('source_key', ''), _negated=True), fields=('agency', 'source_key'), name='client_cabinet_notification_unique_source'),
        ),
    ]
