# Generated by Django 6.0 on 2026-07-19 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_general_threads(apps, schema_editor):
    Agency = apps.get_model("sku", "Agency")
    ChatThread = apps.get_model("client_cabinet", "ChatThread")
    ClientChatMessage = apps.get_model("client_cabinet", "ClientChatMessage")

    agency_ids = set(ClientChatMessage.objects.values_list("agency_id", flat=True).distinct())
    for agency_id in agency_ids:
        if not agency_id:
            continue
        agency = Agency.objects.filter(pk=agency_id).first()
        if not agency:
            continue
        name = (getattr(agency, "short_name", None) or getattr(agency, "agn_name", None) or f"Клиент {agency_id}")
        thread, _ = ChatThread.objects.get_or_create(
            agency_id=agency_id,
            kind="client_general",
            defaults={"title": f"Клиент — FullBox · {name}"[:255]},
        )
        qs = ClientChatMessage.objects.filter(agency_id=agency_id, thread_id__isnull=True)
        last = qs.order_by("-created_at", "-id").first()
        qs.update(thread_id=thread.id, visibility="client")
        if last and last.created_at:
            ChatThread.objects.filter(pk=thread.id).update(last_message_at=last.created_at)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('client_cabinet', '0004_agency_portal_member'),
        ('sku', '0010_sku_weight_gross_kg_sku_weight_net_kg'),
        ('todo', '0008_taskpanelsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('client_general', 'Клиент — FullBox'), ('order_client', 'Чат заявки (клиент)'), ('order_internal', 'Внутренний чат заявки'), ('task', 'Чат задачи'), ('manual', 'Ручной чат')], db_index=True, max_length=32, verbose_name='Тип')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('order_type', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Тип заявки')),
                ('order_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Номер заявки')),
                ('is_archived', models.BooleanField(db_index=True, default=False, verbose_name='Архив')),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Последнее сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Чат-тред',
                'verbose_name_plural': 'Чат-треды',
                'ordering': ['-last_message_at', '-updated_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='clientchatmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Удалено'),
        ),
        migrations.AddField(
            model_name='clientchatmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отредактировано'),
        ),
        migrations.AddField(
            model_name='clientchatmessage',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Помечено удалённым'),
        ),
        migrations.AddField(
            model_name='clientchatmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='client_cabinet.clientchatmessage', verbose_name='Ответ на'),
        ),
        migrations.AddField(
            model_name='clientchatmessage',
            name='visibility',
            field=models.CharField(choices=[('client', 'Видно клиенту'), ('internal', 'Только FullBox'), ('system', 'Системное')], db_index=True, default='client', max_length=16, verbose_name='Видимость'),
        ),
        migrations.AlterField(
            model_name='clientchatmessage',
            name='author_role',
            field=models.CharField(choices=[('client', 'Клиент'), ('staff', 'FullBox'), ('system', 'Система')], default='client', max_length=16, verbose_name='Роль автора'),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to='sku.agency', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chat_threads', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_threads', to='todo.task', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='clientchatmessage',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='client_cabinet.chatthread', verbose_name='Тред'),
        ),
        migrations.AddIndex(
            model_name='clientchatmessage',
            index=models.Index(fields=['thread', 'created_at'], name='client_cabi_thread__ae796a_idx'),
        ),
        migrations.AddIndex(
            model_name='clientchatmessage',
            index=models.Index(fields=['thread', 'is_read_by_staff', 'author_role'], name='client_cabi_thread__e8eb2a_idx'),
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['agency', 'kind', 'is_archived'], name='client_cabi_agency__0449ff_idx'),
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['order_type', 'order_id'], name='client_cabi_order_t_4af372_idx'),
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['agency', 'last_message_at'], name='client_cabi_agency__108057_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatthread',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'client_general')), fields=('agency',), name='uniq_chat_thread_client_general'),
        ),
        migrations.AddConstraint(
            model_name='chatthread',
            constraint=models.UniqueConstraint(condition=models.Q(('kind__in', ['order_client', 'order_internal']), models.Q(('order_id', ''), _negated=True)), fields=('agency', 'kind', 'order_type', 'order_id'), name='uniq_chat_thread_order_kind'),
        ),
        migrations.RunPython(backfill_general_threads, noop_reverse),
    ]
