# Generated by Django 6.0 on 2026-07-19 19:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_cabinet', '0005_chat_threads_module'),
        ('sku', '0010_sku_weight_gross_kg_sku_weight_net_kg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=16, verbose_name='Реакция')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Реакция на сообщение',
                'verbose_name_plural': 'Реакции на сообщения',
            },
        ),
        migrations.CreateModel(
            name='ChatMessageReadReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Прочтение сообщения',
                'verbose_name_plural': 'Прочтения сообщений',
            },
        ),
        migrations.CreateModel(
            name='ChatNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound_enabled', models.BooleanField(default=True, verbose_name='Звук')),
                ('sound_muted_until', models.DateTimeField(blank=True, null=True, verbose_name='Звук выключен до')),
                ('browser_notifications', models.BooleanField(default=False, verbose_name='Браузерные уведомления')),
                ('notify_client_messages', models.BooleanField(default=True, verbose_name='Сообщения клиентов')),
                ('notify_internal', models.BooleanField(default=True, verbose_name='Внутренние сообщения')),
                ('notify_mentions', models.BooleanField(default=True, verbose_name='Упоминания')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки уведомлений чата',
                'verbose_name_plural': 'Настройки уведомлений чата',
            },
        ),
        migrations.AddField(
            model_name='chatthread',
            name='conversation_status',
            field=models.CharField(choices=[('new', 'Новый'), ('needs_staff', 'Требует ответа FullBox'), ('wait_client', 'Ожидается ответ клиента'), ('wait_warehouse', 'Ожидается ответ склада'), ('in_progress', 'В работе'), ('resolved', 'Решён'), ('closed', 'Закрыт'), ('archived', 'Архив')], db_index=True, default='new', max_length=32, verbose_name='Статус обращения'),
        ),
        migrations.AddField(
            model_name='clientchatmessage',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Доставлено'),
        ),
        migrations.AddField(
            model_name='clientchatmessage',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Idempotency key'),
        ),
        migrations.AddField(
            model_name='clientchatmessage',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='UUID'),
        ),
        migrations.AddIndex(
            model_name='clientchatmessage',
            index=models.Index(fields=['thread', 'idempotency_key'], name='client_cabi_thread__474785_idx'),
        ),
        migrations.AddConstraint(
            model_name='clientchatmessage',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('idempotency_key', ''), _negated=True), ('thread__isnull', False)), fields=('thread', 'author', 'idempotency_key'), name='uniq_chat_msg_idempotency'),
        ),
        migrations.AddField(
            model_name='chatmessagereaction',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='client_cabinet.clientchatmessage', verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='chatmessagereaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='chatmessagereadreceipt',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='client_cabinet.clientchatmessage', verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='chatmessagereadreceipt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_read_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='chatnotificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_notification_pref', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='chatmessagereaction',
            index=models.Index(fields=['message', 'emoji'], name='client_cabi_message_c1746c_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatmessagereaction',
            constraint=models.UniqueConstraint(fields=('message', 'user', 'emoji'), name='uniq_chat_reaction'),
        ),
        migrations.AddIndex(
            model_name='chatmessagereadreceipt',
            index=models.Index(fields=['user', 'read_at'], name='client_cabi_user_id_1faefc_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessagereadreceipt',
            index=models.Index(fields=['message', 'read_at'], name='client_cabi_message_372cb7_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatmessagereadreceipt',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='uniq_chat_read_receipt'),
        ),
    ]
