# Generated by Django 6.0 on 2026-07-20 09:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_categories(apps, schema_editor):
    OtherRequestCategory = apps.get_model("client_cabinet", "OtherRequestCategory")
    seed = [
        ("remark", "Перемаркировка", "warehouse", 24, False, False, True, 10),
        ("recount", "Пересчет товара", "warehouse", 24, False, True, True, 20),
        ("find_goods", "Поиск товара", "warehouse", 12, False, False, False, 30),
        ("defect_check", "Проверка брака", "warehouse", 24, False, True, True, 40),
        ("photo", "Фото товара", "warehouse", 12, True, False, True, 50),
        ("inventory", "Инвентаризация", "warehouse", 48, True, True, True, 60),
        ("stock_check", "Проверка остатков", "warehouse", 12, False, False, False, 70),
        ("repack", "Изменение упаковки", "packing", 24, False, True, True, 80),
        ("documents", "Подготовка документов", "managers", 24, False, True, False, 90),
        ("move_goods", "Перемещение товара", "warehouse", 24, False, True, True, 100),
        ("marking_check", "Проверка маркировки", "warehouse", 24, False, False, True, 110),
        ("clarify", "Уточнение данных", "managers", 24, False, False, False, 120),
        ("measure_size", "Измерить размер", "warehouse", 24, False, False, True, 130),
        ("courier_box", "Подготовить короб курьеру", "packing", 12, False, False, True, 140),
        ("photo_video", "Фото / видео товара", "warehouse", 12, False, False, True, 150),
        ("custom", "Другое", "warehouse", 24, False, False, True, 160),
    ]
    for code, title, dept, sla, photo, qty, paid, order in seed:
        OtherRequestCategory.objects.get_or_create(
            code=code,
            defaults={
                "title": title,
                "default_department": dept,
                "default_sla_hours": sla,
                "require_result_photo": photo,
                "require_qty": qty,
                "can_be_paid": paid,
                "sort_order": order,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('client_cabinet', '0011_chat_ai_foundation'),
        ('employees', '0009_super_car_role_and_user'),
        ('sku', '0010_sku_weight_gross_kg_sku_weight_net_kg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('public_number', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Номер')),
                ('category_code', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Код категории')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('awaiting_manager', 'Ожидает менеджера'), ('need_client_info', 'Требуется уточнение'), ('approved', 'Подтверждена менеджером'), ('awaiting_department', 'Ожидает принятия подразделением'), ('in_progress', 'В работе'), ('paused', 'Приостановлена'), ('done_by_department', 'Выполнена подразделением'), ('awaiting_manager_check', 'Ожидает проверки менеджером'), ('rework', 'Возвращена на доработку'), ('closed', 'Закрыта'), ('cancelled', 'Отменена'), ('rejected', 'Отклонена')], db_index=True, default='draft', max_length=32, verbose_name='Статус')),
                ('department', models.CharField(choices=[('warehouse', 'Склад'), ('processing', 'Обработка'), ('packing', 'Упаковка / короба'), ('logistics', 'Логистика'), ('managers', 'Менеджеры'), ('accounting', 'Бухгалтерия'), ('it', 'IT'), ('other', 'Другое')], db_index=True, default='warehouse', max_length=32, verbose_name='Подразделение')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('urgent', 'Срочный')], db_index=True, default='normal', max_length=16, verbose_name='Приоритет')),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Плановый срок')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало работы')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое выполнение')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Закрыта')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Отменена')),
                ('pause_reason', models.TextField(blank=True, verbose_name='Причина приостановки')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='Причина отмены')),
                ('reject_reason', models.TextField(blank=True, verbose_name='Причина отклонения')),
                ('rework_reason', models.TextField(blank=True, verbose_name='Причина возврата')),
                ('result_outcome', models.CharField(blank=True, max_length=64, verbose_name='Итог выполнения')),
                ('result_comment', models.TextField(blank=True, verbose_name='Комментарий исполнителя')),
                ('result_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Факт. количество')),
                ('result_unit', models.CharField(blank=True, max_length=32, verbose_name='Ед. изм.')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Платная задача')),
                ('billing_service_code', models.CharField(blank=True, max_length=64, verbose_name='Код услуги')),
                ('billing_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Кол-во услуги')),
                ('billing_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма')),
                ('billing_status', models.CharField(blank=True, max_length=32, verbose_name='Статус начисления')),
                ('internal_note', models.TextField(blank=True, verbose_name='Внутренний комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Другая заявка',
                'verbose_name_plural': 'Другие заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OtherRequestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('default_department', models.CharField(blank=True, default='warehouse', max_length=32, verbose_name='Подразделение по умолчанию')),
                ('default_sla_hours', models.PositiveIntegerField(default=24, verbose_name='Типовой срок SLA, ч')),
                ('require_result_photo', models.BooleanField(default=False, verbose_name='Нужно фото результата')),
                ('require_result_file', models.BooleanField(default=False, verbose_name='Нужен файл результата')),
                ('require_qty', models.BooleanField(default=False, verbose_name='Нужно количество')),
                ('can_be_paid', models.BooleanField(default=True, verbose_name='Может быть платной')),
                ('default_billing_service_code', models.CharField(blank=True, max_length=64, verbose_name='Услуга биллинга по умолчанию')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категория другой заявки',
                'verbose_name_plural': 'Категории других заявок',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='OtherRequestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('client', 'Клиенту'), ('internal', 'Внутренний')], db_index=True, default='internal', max_length=16, verbose_name='Видимость')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Комментарий другой заявки',
                'verbose_name_plural': 'Комментарии других заявок',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OtherRequestLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('receiving', 'Приёмка'), ('processing', 'Обработка'), ('shipping', 'Отгрузка'), ('trip', 'Рейс'), ('sku', 'Артикул'), ('barcode', 'ШК товара'), ('box', 'Короб'), ('pallet', 'Палета'), ('cell', 'Ячейка'), ('supply', 'Поставка'), ('other', 'Другое')], max_length=32, verbose_name='Тип связи')),
                ('object_key', models.CharField(max_length=128, verbose_name='Ключ объекта')),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('url', models.CharField(blank=True, max_length=512, verbose_name='Ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Связанный объект другой заявки',
                'verbose_name_plural': 'Связанные объекты других заявок',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='otherrequestattachment',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Файл другой заявки', 'verbose_name_plural': 'Файлы других заявок'},
        ),
        migrations.AddField(
            model_name='otherrequestattachment',
            name='file_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Размер, байт'),
        ),
        migrations.AddField(
            model_name='otherrequestattachment',
            name='purpose',
            field=models.CharField(choices=[('client', 'Файл клиента'), ('internal', 'Внутренний файл'), ('result', 'Результат выполнения')], db_index=True, default='client', max_length=16, verbose_name='Назначение'),
        ),
        migrations.AddField(
            model_name='otherrequest',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_requests', to='sku.agency', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='otherrequest',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_requests_assigned', to='employees.employee', verbose_name='Ответственный'),
        ),
        migrations.AddField(
            model_name='otherrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='otherrequest',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_requests_managed', to='employees.employee', verbose_name='Менеджер клиента'),
        ),
        migrations.AddField(
            model_name='otherrequestattachment',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='client_cabinet.otherrequest', verbose_name='Заявка'),
        ),
        migrations.AddField(
            model_name='otherrequest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='client_cabinet.otherrequestcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='otherrequestcomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_request_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otherrequestcomment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='client_cabinet.otherrequest'),
        ),
        migrations.AddField(
            model_name='otherrequestlink',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='client_cabinet.otherrequest'),
        ),
        migrations.AddIndex(
            model_name='otherrequest',
            index=models.Index(fields=['status', 'due_at'], name='client_cabi_status_2a4a84_idx'),
        ),
        migrations.AddIndex(
            model_name='otherrequest',
            index=models.Index(fields=['agency', 'status'], name='client_cabi_agency__25952a_idx'),
        ),
        migrations.AddIndex(
            model_name='otherrequest',
            index=models.Index(fields=['department', 'status'], name='client_cabi_departm_6cb527_idx'),
        ),
        migrations.AddIndex(
            model_name='otherrequest',
            index=models.Index(fields=['assignee', 'status'], name='client_cabi_assigne_5e09df_idx'),
        ),
        migrations.RunPython(seed_categories, migrations.RunPython.noop),
    ]
