from django.urls import path, include

from .views import (
    OrdersDetailView,
    OrdersHomeView,
    OrdersOtherDetailView,
    OrdersPackingView,
    PackingDetailView,
    ReceivingActView,
    ReceivingFlowView,
    PlacementActView,
    receiving_attachment_download,
    receiving_shipping_return_order_search,
    receiving_flow_box_action,
    receiving_flow_pallet_placement_permission,
    receiving_flow_container_code,
    receiving_flow_rebind_box_code,
    receiving_flow_set_item_weight,
    export_receiving_flow_current_xlsx,
    download_receiving_template,
    download_sku_upload_template,
    download_receiving_act_doc,
    export_receiving_result_xlsx,
    download_receiving_act_marking_xlsx,
    download_receiving_act_mx1,
    print_receiving_act,
    print_receiving_act_mx1,
    confirm_receiving_act_client,
    dispute_receiving_act_client,
    sign_receiving_act_manager,
    sign_receiving_act_storekeeper,
)
from .receiving_tsd import (
    receiving_tsd_asset,
    receiving_tsd_claim,
    receiving_tsd_close_box,
    receiving_tsd_close_pallet,
    receiving_tsd_complete,
    receiving_tsd_detail,
    receiving_tsd_event,
    receiving_tsd_open_box,
    receiving_tsd_print_agents,
    receiving_tsd_print_label,
    receiving_tsd_queue,
    receiving_tsd_scan,
    receiving_tsd_set_marking_mode,
    receiving_tsd_set_goods_type,
    receiving_tsd_set_location,
)
from .receiving_tsd_corrections import receiving_tsd_correct_box

urlpatterns = [
    path('', OrdersHomeView.as_view(), name='orders-journal'),
    path('receiving/', OrdersHomeView.as_view(), {'tab': 'receiving'}, name='orders-receiving'),
    path('receiving/tsd/', receiving_tsd_queue, name='orders-receiving-tsd-queue'),
    path('receiving/tsd/assets/<str:asset_name>/', receiving_tsd_asset, name='orders-receiving-tsd-asset'),
    path('receiving/<str:order_id>/tsd/', receiving_tsd_detail, name='orders-receiving-tsd-detail'),
    path('receiving/<str:order_id>/tsd/claim/', receiving_tsd_claim, name='orders-receiving-tsd-claim'),
    path('receiving/<str:order_id>/tsd/goods-type/', receiving_tsd_set_goods_type, name='orders-receiving-tsd-set-goods-type'),
    path('receiving/<str:order_id>/tsd/box/open/', receiving_tsd_open_box, name='orders-receiving-tsd-open-box'),
    path('receiving/<str:order_id>/tsd/box/close/', receiving_tsd_close_box, name='orders-receiving-tsd-close-box'),
    path('receiving/<str:order_id>/tsd/box/correct/', receiving_tsd_correct_box, name='orders-receiving-tsd-correct-box'),
    path('receiving/<str:order_id>/tsd/pallet/close/', receiving_tsd_close_pallet, name='orders-receiving-tsd-close-pallet'),
    path('receiving/<str:order_id>/tsd/print-agents/', receiving_tsd_print_agents, name='orders-receiving-tsd-print-agents'),
    path('receiving/<str:order_id>/tsd/print/', receiving_tsd_print_label, name='orders-receiving-tsd-print-label'),
    path('receiving/<str:order_id>/tsd/location/', receiving_tsd_set_location, name='orders-receiving-tsd-set-location'),
    path('receiving/<str:order_id>/tsd/complete/', receiving_tsd_complete, name='orders-receiving-tsd-complete'),
    path('receiving/<str:order_id>/tsd/scan/', receiving_tsd_scan, name='orders-receiving-tsd-scan'),
    path('receiving/<str:order_id>/tsd/marking-mode/', receiving_tsd_set_marking_mode, name='orders-receiving-tsd-set-marking-mode'),
    path('receiving/<str:order_id>/tsd/event/', receiving_tsd_event, name='orders-receiving-tsd-event'),
    path('receiving/<str:order_id>/', OrdersDetailView.as_view(), name='orders-receiving-detail'),
    path(
        'receiving/<str:order_id>/shipping-return-orders/',
        receiving_shipping_return_order_search,
        name='orders-receiving-shipping-return-orders',
    ),
    path(
        'receiving/<str:order_id>/attachments/<int:attachment_id>/',
        receiving_attachment_download,
        name='orders-receiving-attachment-download',
    ),
    path('receiving/<str:order_id>/act/', ReceivingActView.as_view(), name='orders-receiving-act'),
    path('receiving/<str:order_id>/cz-flow/', include('receiving_cz.urls')),
    path('receiving/<str:order_id>/flow/', ReceivingFlowView.as_view(), name='orders-receiving-flow'),
    path('receiving/<str:order_id>/flow/box-action/', receiving_flow_box_action, name='orders-receiving-flow-box-action'),
    path(
        'receiving/<str:order_id>/flow/pallet-placement-permission/',
        receiving_flow_pallet_placement_permission,
        name='orders-receiving-flow-pallet-placement-permission',
    ),
    path('receiving/<str:order_id>/flow/container-code/', receiving_flow_container_code, name='orders-receiving-flow-container-code'),
    path('receiving/<str:order_id>/flow/rebind-box-code/', receiving_flow_rebind_box_code, name='orders-receiving-flow-rebind-box-code'),
    path('receiving/<str:order_id>/flow/item-weight/', receiving_flow_set_item_weight, name='orders-receiving-flow-item-weight'),
    path('receiving/<str:order_id>/flow/export/', export_receiving_flow_current_xlsx, name='orders-receiving-flow-export'),
    path('receiving/<str:order_id>/placement/', PlacementActView.as_view(), name='orders-receiving-placement'),
    path('receiving/<str:order_id>/export/', export_receiving_result_xlsx, name='orders-receiving-export'),
    path('receiving/<str:order_id>/act/document/', download_receiving_act_doc, name='orders-receiving-act-doc'),
    path('receiving/<str:order_id>/act/chz.xlsx', download_receiving_act_marking_xlsx, name='orders-receiving-act-chz'),
    path('receiving/<str:order_id>/act/print/', print_receiving_act, name='orders-receiving-act-print'),
    path('receiving/<str:order_id>/act/client/confirm/', confirm_receiving_act_client, name='orders-receiving-act-client-confirm'),
    path('receiving/<str:order_id>/act/client/dispute/', dispute_receiving_act_client, name='orders-receiving-act-client-dispute'),
    path('receiving/<str:order_id>/act/sign/storekeeper/', sign_receiving_act_storekeeper, name='orders-receiving-act-sign-storekeeper'),
    path('receiving/<str:order_id>/act/sign/manager/', sign_receiving_act_manager, name='orders-receiving-act-sign-manager'),
    path('receiving/<str:order_id>/act/mx1/', download_receiving_act_mx1, name='orders-receiving-act-mx1'),
    path('receiving/<str:order_id>/act/mx1/print/', print_receiving_act_mx1, name='orders-receiving-act-mx1-print'),
    path('packing/', OrdersPackingView.as_view(), {'tab': 'packing'}, name='orders-packing'),
    path('packing/<str:order_id>/', PackingDetailView.as_view(), name='orders-packing-detail'),
    path('processing/', include('processing_app.urls')),
    path('shipping/', OrdersHomeView.as_view(), {'tab': 'shipping'}, name='orders-shipping'),
    path('other/', OrdersHomeView.as_view(), {'tab': 'other'}, name='orders-other'),
    path('other/<str:order_id>/', OrdersOtherDetailView.as_view(), name='orders-other-detail'),
    path('templates/receiving/', download_receiving_template, name='orders-template-receiving'),
    path('templates/sku-upload/', download_sku_upload_template, name='orders-template-sku-upload'),
]
