# Generated by Django 6.0 on 2026-07-10 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sklad', '0010_warehousecontainer_dimensions_weight'),
        ('sku', '0010_sku_weight_gross_kg_sku_weight_net_kg'),
        ('todo', '0008_taskpanelsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxMoveOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('selecting', 'Выбор коробов'), ('destination', 'Выбор паллеты назначения'), ('verifying', 'Проверка паллеты назначения'), ('done', 'Выполнено'), ('done_with_discrepancy', 'Выполнено с расхождениями'), ('canceled', 'Отменено')], default='selecting', max_length=32)),
                ('source_pallet_code', models.CharField(blank=True, max_length=128)),
                ('source_location_label', models.CharField(blank=True, max_length=255)),
                ('source_location_scan_code', models.CharField(blank=True, max_length=64)),
                ('destination_pallet_code', models.CharField(blank=True, max_length=128)),
                ('destination_location_label', models.CharField(blank=True, max_length=255)),
                ('destination_location_scan_code', models.CharField(blank=True, max_length=64)),
                ('selected_boxes', models.JSONField(blank=True, default=list)),
                ('destination_expected_boxes', models.JSONField(blank=True, default=list)),
                ('destination_scanned_boxes', models.JSONField(blank=True, default=list)),
                ('discrepancies', models.JSONField(blank=True, default=list)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reachtruck_box_move_operations', to='sku.agency')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reachtruck_box_move_operations', to=settings.AUTH_USER_MODEL)),
                ('manager_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='box_move_operations', to='todo.task')),
                ('warehouse_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='box_move_operations', to='sklad.warehouseoperation')),
            ],
            options={
                'db_table': 'reachtruck_box_move_operation',
                'indexes': [models.Index(fields=['status', 'created_at'], name='reachtruck__status_14036d_idx'), models.Index(fields=['driver', 'status'], name='reachtruck__driver__b10257_idx'), models.Index(fields=['source_pallet_code'], name='reachtruck__source__eb698f_idx'), models.Index(fields=['destination_pallet_code'], name='reachtruck__destina_a1eafe_idx')],
            },
        ),
    ]
