# Generated by Django 6.0 on 2026-03-14 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sku', '0008_agency_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_type', models.CharField(choices=[('receiving', 'Приемка'), ('processing', 'Обработка'), ('manual', 'Ручной запрос')], default='manual', max_length=16)),
                ('context_id', models.CharField(blank=True, max_length=64)),
                ('requested_by_role', models.CharField(blank=True, max_length=32)),
                ('requested_by_name', models.CharField(blank=True, max_length=255)),
                ('destination_zone', models.CharField(default='PR', max_length=16)),
                ('destination_row', models.PositiveIntegerField(blank=True, null=True)),
                ('destination_section', models.PositiveIntegerField(blank=True, null=True)),
                ('destination_tier', models.PositiveIntegerField(blank=True, null=True)),
                ('destination_cell', models.PositiveIntegerField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('normal', 'Обычный'), ('high', 'Высокий'), ('urgent', 'Срочно')], default='normal', max_length=16)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('created', 'Создан'), ('planned', 'Спланирован'), ('in_progress', 'В работе'), ('partial', 'Частично выполнен'), ('done', 'Выполнен'), ('blocked', 'Заблокирован'), ('canceled', 'Отменен')], default='created', max_length=16)),
                ('planning_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='super_car_move_requests', to='sku.agency')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='super_car_move_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запрос ричтрака',
                'verbose_name_plural': 'Запросы ричтрака',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoveRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(blank=True, max_length=64)),
                ('barcode', models.CharField(blank=True, max_length=64)),
                ('goods_type', models.CharField(blank=True, max_length=32)),
                ('qty_requested', models.PositiveIntegerField(default=0)),
                ('qty_planned', models.PositiveIntegerField(default=0)),
                ('qty_done', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='super_car.moverequest')),
            ],
            options={
                'verbose_name': 'Строка запроса ричтрака',
                'verbose_name_plural': 'Строки запросов ричтрака',
            },
        ),
        migrations.CreateModel(
            name='MoveTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet_code', models.CharField(max_length=128)),
                ('from_zone', models.CharField(blank=True, max_length=16)),
                ('from_row', models.PositiveIntegerField(blank=True, null=True)),
                ('from_section', models.PositiveIntegerField(blank=True, null=True)),
                ('from_tier', models.PositiveIntegerField(blank=True, null=True)),
                ('from_cell', models.PositiveIntegerField(blank=True, null=True)),
                ('to_zone', models.CharField(blank=True, max_length=16)),
                ('to_row', models.PositiveIntegerField(blank=True, null=True)),
                ('to_section', models.PositiveIntegerField(blank=True, null=True)),
                ('to_tier', models.PositiveIntegerField(blank=True, null=True)),
                ('to_cell', models.PositiveIntegerField(blank=True, null=True)),
                ('move_mode', models.CharField(choices=[('pallet_full', 'Паллета целиком'), ('box_full', 'Короба целиком'), ('box_partial', 'Частичный отбор')], default='pallet_full', max_length=16)),
                ('qty_planned', models.PositiveIntegerField(default=0)),
                ('qty_done', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('created', 'Создано'), ('in_progress', 'В работе'), ('done', 'Выполнено'), ('canceled', 'Отменено'), ('failed', 'Ошибка')], default='created', max_length=16)),
                ('assigned_to_name', models.CharField(blank=True, max_length=255)),
                ('legacy_order_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='super_car_tasks', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='super_car.moverequest')),
            ],
            options={
                'verbose_name': 'Задание ричтрака',
                'verbose_name_plural': 'Задания ричтрака',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='moverequest',
            index=models.Index(fields=['context_type', 'context_id'], name='super_car_m_context_b6d161_idx'),
        ),
        migrations.AddIndex(
            model_name='moverequest',
            index=models.Index(fields=['status', 'priority'], name='super_car_m_status_9fc6cd_idx'),
        ),
        migrations.AddIndex(
            model_name='moverequest',
            index=models.Index(fields=['agency', 'status'], name='super_car_m_agency__9d5f0d_idx'),
        ),
        migrations.AddIndex(
            model_name='moverequestitem',
            index=models.Index(fields=['request', 'sku_code'], name='super_car_m_request_90d792_idx'),
        ),
        migrations.AddIndex(
            model_name='moverequestitem',
            index=models.Index(fields=['barcode'], name='super_car_m_barcode_2b14e6_idx'),
        ),
        migrations.AddIndex(
            model_name='movetask',
            index=models.Index(fields=['request', 'status'], name='super_car_m_request_efce50_idx'),
        ),
        migrations.AddIndex(
            model_name='movetask',
            index=models.Index(fields=['status', 'created_at'], name='super_car_m_status_c9e654_idx'),
        ),
        migrations.AddIndex(
            model_name='movetask',
            index=models.Index(fields=['pallet_code', 'status'], name='super_car_m_pallet__6f9d38_idx'),
        ),
    ]
