# Generated by Django 6.0 on 2026-08-17 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0014_employee_fbs_controller_role'),
        ('sku', '0010_sku_weight_gross_kg_sku_weight_net_kg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WmsNewSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('done', 'Завершена'), ('failed', 'Ошибка')], default='running', max_length=16)),
                ('imported', models.PositiveIntegerField(default=0)),
                ('updated', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wms_new_sync_run',
                'ordering': ('-started_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='WmsNewOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_order_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('source_profile_id', models.BigIntegerField(blank=True, null=True)),
                ('marketplace', models.CharField(blank=True, max_length=32)),
                ('integration_name', models.CharField(blank=True, max_length=128)),
                ('external_order_id', models.CharField(max_length=128)),
                ('delivery_type', models.CharField(blank=True, max_length=128)),
                ('tracking_number', models.CharField(blank=True, max_length=128)),
                ('warehouse_code', models.CharField(default='MSK', max_length=64)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('awaiting_stock', 'Ожидает товар'), ('reserved', 'Зарезервирован'), ('queued', 'В очереди сборки'), ('picking', 'Собирается'), ('picked', 'Отобран'), ('ready', 'Готов к передаче'), ('handed_over', 'Передан'), ('done', 'Выполнен'), ('cancelled', 'Отменен'), ('return_pending', 'Ожидается возврат'), ('returned', 'Возвращен'), ('exception', 'Исключение')], default='new', max_length=32)),
                ('source_status', models.CharField(blank=True, max_length=64)),
                ('ordered_at', models.DateTimeField(blank=True, null=True)),
                ('cutoff_at', models.DateTimeField(blank=True, null=True)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('availability_state', models.CharField(default='unavailable', max_length=32)),
                ('availability_snapshot', models.JSONField(blank=True, default=list)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('is_manual', models.BooleanField(default=False)),
                ('pilot_revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wms_new_orders', to='sku.agency')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wms_new_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wms_new_order',
                'ordering': ('-source_created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='WmsNewOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_item_id', models.BigIntegerField(blank=True, null=True)),
                ('external_line_id', models.CharField(max_length=128)),
                ('external_sku', models.CharField(blank=True, max_length=128)),
                ('barcode', models.CharField(blank=True, max_length=64)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('requirements', models.JSONField(blank=True, default=dict)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wms_new.wmsneworder')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wms_new_order_items', to='sku.sku')),
            ],
            options={
                'db_table': 'wms_new_order_item',
                'ordering': ('order_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WmsNewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=64)),
                ('entity_type', models.CharField(max_length=64)),
                ('source_key', models.CharField(max_length=128)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('pilot_revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wms_new_records', to='sku.agency')),
            ],
            options={
                'db_table': 'wms_new_record',
            },
        ),
        migrations.CreateModel(
            name='WmsNewTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_task_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('workflow_type', models.CharField(choices=[('acceptance', 'Прием поставки'), ('processing', 'Обработка товара'), ('shipment', 'Отгрузка товара'), ('other', 'Прочие задачи')], default='other', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('blocked', 'Приостановлена'), ('done', 'Выполнена')], default='new', max_length=32)),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Средний'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='normal', max_length=16)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('is_manual', models.BooleanField(default=False)),
                ('pilot_revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wms_new_tasks', to='sku.agency')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wms_new_tasks', to='employees.employee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wms_new_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wms_new_task',
                'ordering': ('status', 'due_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='WmsNewWave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('in_progress', 'В работе'), ('verification', 'На проверке'), ('done', 'Завершена'), ('cancelled', 'Отменена')], default='queued', max_length=32)),
                ('planned_orders', models.PositiveIntegerField(default=0)),
                ('planned_units', models.PositiveIntegerField(default=0)),
                ('picked_units', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wms_new_waves', to='sku.agency')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wms_new_waves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wms_new_wave',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='WmsNewWaveOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wave_orders', to='wms_new.wmsneworder')),
                ('wave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wave_orders', to='wms_new.wmsnewwave')),
            ],
            options={
                'db_table': 'wms_new_wave_order',
                'ordering': ('sequence', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WmsNewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.BigIntegerField()),
                ('action', models.CharField(max_length=64)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wms_new_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wms_new_event',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['entity_type', 'entity_id', 'created_at'], name='wms_new_eve_entity__a559d1_idx'), models.Index(fields=['action', 'created_at'], name='wms_new_eve_action_82dd8b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='wmsneworder',
            index=models.Index(fields=['status', 'source_created_at'], name='wms_new_ord_status_829b8f_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsneworder',
            index=models.Index(fields=['agency', 'status'], name='wms_new_ord_agency__9039c3_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsneworder',
            index=models.Index(fields=['marketplace', 'status'], name='wms_new_ord_marketp_68e5d1_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsneworder',
            index=models.Index(fields=['external_order_id'], name='wms_new_ord_externa_fb7750_idx'),
        ),
        migrations.AddConstraint(
            model_name='wmsneworderitem',
            constraint=models.UniqueConstraint(fields=('order', 'external_line_id'), name='uniq_wms_new_order_line'),
        ),
        migrations.AddIndex(
            model_name='wmsnewrecord',
            index=models.Index(fields=['module', 'entity_type', 'status'], name='wms_new_rec_module_499771_idx'),
        ),
        migrations.AddConstraint(
            model_name='wmsnewrecord',
            constraint=models.UniqueConstraint(fields=('module', 'entity_type', 'source_key'), name='uniq_wms_new_shadow_record'),
        ),
        migrations.AddIndex(
            model_name='wmsnewtask',
            index=models.Index(fields=['workflow_type', 'status'], name='wms_new_tas_workflo_d1fa36_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsnewtask',
            index=models.Index(fields=['agency', 'status'], name='wms_new_tas_agency__a6dd2b_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsnewtask',
            index=models.Index(fields=['assigned_to', 'status'], name='wms_new_tas_assigne_cc9195_idx'),
        ),
        migrations.AddConstraint(
            model_name='wmsnewwaveorder',
            constraint=models.UniqueConstraint(fields=('wave', 'order'), name='uniq_wms_new_wave_order'),
        ),
    ]
