# Generated by Django 6.0 on 2026-08-17 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0010_sku_weight_gross_kg_sku_weight_net_kg'),
        ('wms_new', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WmsNewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_sku_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('article', models.CharField(max_length=128)),
                ('barcode', models.CharField(blank=True, max_length=64)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('color', models.CharField(blank=True, max_length=64)),
                ('size', models.CharField(blank=True, max_length=64)),
                ('category', models.CharField(blank=True, max_length=128)),
                ('weight_grams', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('width_cm', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('depth_cm', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('height_cm', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('marking_required', models.BooleanField(default=False)),
                ('marking_count', models.PositiveIntegerField(default=0)),
                ('stock_on_hand', models.PositiveIntegerField(default=0)),
                ('stock_free', models.PositiveIntegerField(default=0)),
                ('fbo_reserved', models.PositiveIntegerField(default=0)),
                ('fbs_reserved', models.PositiveIntegerField(default=0)),
                ('internal_reserved', models.PositiveIntegerField(default=0)),
                ('expected_qty', models.PositiveIntegerField(default=0)),
                ('is_bundle', models.BooleanField(default=False)),
                ('internal_notes', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('is_manual', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('pilot_revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wms_new_products', to='sku.agency')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wms_new_products', to=settings.AUTH_USER_MODEL)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_products', to='wms_new.wmsnewproduct')),
            ],
            options={
                'db_table': 'wms_new_product',
                'ordering': ('id',),
                'indexes': [models.Index(fields=['agency', 'article'], name='wms_new_pro_agency__1c7f8b_idx'), models.Index(fields=['barcode'], name='wms_new_pro_barcode_16e37f_idx'), models.Index(fields=['category', 'is_archived'], name='wms_new_pro_categor_b2ff6e_idx'), models.Index(fields=['stock_on_hand', 'stock_free'], name='wms_new_pro_stock_o_741e35_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_archived', False)), fields=('agency', 'article'), name='uniq_wms_new_product_article')],
            },
        ),
    ]
