# Generated by Django 6.0 on 2026-08-17 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0010_sku_weight_gross_kg_sku_weight_net_kg'),
        ('wms_new', '0002_wmsnewproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='WmsNewAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_order_key', models.CharField(max_length=128, unique=True)),
                ('task_number', models.CharField(blank=True, max_length=128)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('received_qty', models.PositiveIntegerField(default=0)),
                ('expected_qty', models.PositiveIntegerField(default=0)),
                ('acceptance_type', models.CharField(choices=[('scan', 'Сканирование'), ('manual', 'Ручной ввод')], default='manual', max_length=16)),
                ('status', models.CharField(choices=[('created', 'Создана'), ('in_progress', 'В работе'), ('done', 'Завершена'), ('cancelled', 'Отменена')], default='created', max_length=16)),
                ('source_status', models.CharField(blank=True, max_length=128)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('pilot_revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wms_new_acceptances', to='sku.agency')),
            ],
            options={
                'db_table': 'wms_new_acceptance',
                'ordering': ('-source_created_at', '-id'),
                'indexes': [models.Index(fields=['agency', 'status'], name='wms_new_acc_agency__a8b7a6_idx'), models.Index(fields=['status', 'source_created_at'], name='wms_new_acc_status_b4dabf_idx')],
            },
        ),
    ]
