# Generated by Django 6.0 on 2026-08-18 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0010_sku_weight_gross_kg_sku_weight_net_kg'),
        ('wms_new', '0003_wmsnewacceptance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WmsNewMarkingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('article', models.CharField(blank=True, max_length=128)),
                ('barcode', models.CharField(blank=True, max_length=128)),
                ('code_type', models.CharField(choices=[('unit', 'КИЗ товара'), ('group', 'Код групповой упаковки')], default='unit', max_length=16)),
                ('code', models.TextField(unique=True)),
                ('source', models.CharField(choices=[('scan', 'Сканер'), ('import', 'Импорт'), ('manual', 'Ручной ввод')], default='manual', max_length=16)),
                ('received_reference', models.CharField(blank=True, max_length=128)),
                ('retired_reference', models.CharField(blank=True, max_length=128)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('print_count', models.PositiveIntegerField(default=0)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('is_returned', models.BooleanField(default=False)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('pilot_revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wms_new_marking_codes', to='sku.agency')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wms_new_marking_codes', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marking_codes', to='wms_new.wmsnewproduct')),
            ],
            options={
                'db_table': 'wms_new_marking_code',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['agency', 'product'], name='wms_new_mar_agency__d24650_idx'), models.Index(fields=['retired_at', 'printed_at'], name='wms_new_mar_retired_910de7_idx'), models.Index(fields=['source', 'created_at'], name='wms_new_mar_source_08e099_idx')],
            },
        ),
    ]
