# Generated by Django 6.0 on 2026-08-18 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms_new', '0004_wmsnewmarkingcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WmsNewExtraFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_definition_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('code', models.SlugField(allow_unicode=True, max_length=96, unique=True)),
                ('field_type', models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('boolean', 'Да/нет'), ('date', 'Дата')], default='text', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('options', models.JSONField(blank=True, default=list)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('pilot_revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wms_new_extra_fields', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wms_new_extra_field_definition',
                'ordering': ('sort_order', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WmsNewExtraFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_value_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('value', models.JSONField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('pilot_revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='wms_new.wmsnewextrafielddefinition')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extra_field_values', to='wms_new.wmsnewproduct')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_wms_new_extra_field_values', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wms_new_extra_field_value',
                'ordering': ('definition_id', 'product_id'),
            },
        ),
        migrations.AddIndex(
            model_name='wmsnewextrafielddefinition',
            index=models.Index(fields=['is_active', 'field_type'], name='wms_new_ext_is_acti_bf310d_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsnewextrafieldvalue',
            index=models.Index(fields=['product', 'definition'], name='wms_new_ext_product_1fddaa_idx'),
        ),
        migrations.AddConstraint(
            model_name='wmsnewextrafieldvalue',
            constraint=models.UniqueConstraint(fields=('definition', 'product'), name='uniq_wms_new_extra_field_value'),
        ),
    ]
