# Generated by Django 6.0 on 2026-08-18 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_employee_fbs_controller_role'),
        ('fbs', '0037_workstation_controller_shift'),
        ('sku', '0010_sku_weight_gross_kg_sku_weight_net_kg'),
        ('wms_new', '0005_wmsnewextrafielddefinition_wmsnewextrafieldvalue_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WmsNewInventorySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_session_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('number', models.CharField(max_length=64, unique=True)),
                ('scope_type', models.CharField(choices=[('all', 'Весь склад'), ('agency', 'Партнер'), ('cell', 'Ячейка'), ('pallet', 'Паллета'), ('box', 'Короб'), ('product', 'Товар')], max_length=16)),
                ('mode', models.CharField(choices=[('audit', 'Контрольный пересчет'), ('drain', 'После завершения операций'), ('immediate', 'Немедленная блокировка WMS NEW')], default='audit', max_length=16)),
                ('scan_mode', models.CharField(choices=[('kiz', 'По КИЗам'), ('barcode', 'По штрихкодам')], default='barcode', max_length=16)),
                ('status', models.CharField(choices=[('planned', 'Запланирована'), ('draining', 'Ожидает завершения операций'), ('counting', 'Первый пересчет'), ('recount', 'Повторный пересчет'), ('approval', 'Ожидает утверждения'), ('done', 'Завершена'), ('cancelled', 'Отменена')], default='planned', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('pilot_revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wms_new_inventory_sessions', to='sku.agency')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_wms_new_inventory_sessions', to=settings.AUTH_USER_MODEL)),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wms_new_inventory_sessions', to='fbs.fbsbox')),
                ('cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wms_new_inventory_sessions', to='fbs.fbsstoragecell')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wms_new_inventory_sessions', to=settings.AUTH_USER_MODEL)),
                ('first_counter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_wms_new_inventory_sessions', to='employees.employee')),
                ('pallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wms_new_inventory_sessions', to='fbs.fbspallet')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_sessions', to='wms_new.wmsnewproduct')),
                ('second_counter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_wms_new_inventory_sessions', to='employees.employee')),
            ],
            options={
                'db_table': 'wms_new_inventory_session',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='WmsNewInventoryLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_new_operations', models.BooleanField(default=True)),
                ('block_execution', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_lock', to='wms_new.wmsnewinventorysession')),
            ],
            options={
                'db_table': 'wms_new_inventory_lock',
            },
        ),
        migrations.CreateModel(
            name='WmsNewInventoryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_line_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('source_balance_id', models.BigIntegerField(blank=True, null=True)),
                ('location_code', models.CharField(blank=True, max_length=128)),
                ('cell_code', models.CharField(blank=True, max_length=64)),
                ('pallet_code', models.CharField(blank=True, max_length=128)),
                ('box_code', models.CharField(blank=True, max_length=128)),
                ('sku_code', models.CharField(max_length=128)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('barcode', models.CharField(blank=True, max_length=128)),
                ('marking_code', models.CharField(blank=True, max_length=256)),
                ('expected_qty', models.PositiveIntegerField(default=0)),
                ('first_count_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('second_count_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('final_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('approved_delta', models.IntegerField(default=0)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wms_new_inventory_lines', to='sku.agency')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_lines', to='wms_new.wmsnewproduct')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='wms_new.wmsnewinventorysession')),
            ],
            options={
                'db_table': 'wms_new_inventory_line',
                'ordering': ('location_code', 'box_code', 'sku_code', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WmsNewInventoryScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_scan_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('count_round', models.PositiveSmallIntegerField(choices=[(1, 'Первый'), (2, 'Повторный')])),
                ('scan_code', models.CharField(max_length=256)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wms_new_inventory_scans', to='employees.employee')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='wms_new.wmsnewinventoryline')),
            ],
            options={
                'db_table': 'wms_new_inventory_scan',
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['line', 'count_round'], name='wms_new_inv_line_id_9cc613_idx'), models.Index(fields=['scan_code'], name='wms_new_inv_scan_co_eb5022_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='wms_new_inventory_scan_qty_gt_zero')],
            },
        ),
        migrations.AddIndex(
            model_name='wmsnewinventorysession',
            index=models.Index(fields=['status', 'created_at'], name='wms_new_inv_status_bd439f_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsnewinventorysession',
            index=models.Index(fields=['agency', 'status'], name='wms_new_inv_agency__227e8e_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsnewinventorysession',
            index=models.Index(fields=['scope_type', 'status'], name='wms_new_inv_scope_t_87676e_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsnewinventorylock',
            index=models.Index(fields=['is_active', 'block_new_operations'], name='wms_new_inv_is_acti_c58451_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsnewinventorylock',
            index=models.Index(fields=['is_active', 'block_execution'], name='wms_new_inv_is_acti_b83d1b_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsnewinventoryline',
            index=models.Index(fields=['session', 'product'], name='wms_new_inv_session_66d397_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsnewinventoryline',
            index=models.Index(fields=['barcode'], name='wms_new_inv_barcode_632ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsnewinventoryline',
            index=models.Index(fields=['marking_code'], name='wms_new_inv_marking_6e2d37_idx'),
        ),
        migrations.AddConstraint(
            model_name='wmsnewinventoryline',
            constraint=models.UniqueConstraint(fields=('session', 'source_balance_id'), name='uniq_wms_new_inventory_balance'),
        ),
    ]
