# Generated by Django 6.0 on 2026-08-18 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0011_live_snapshot_query_indexes'),
        ('sku', '0010_sku_weight_gross_kg_sku_weight_net_kg'),
        ('wms_new', '0006_wmsnewinventorysession_wmsnewinventorylock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WmsNewBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_container_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('code', models.CharField(max_length=128)),
                ('source_parent_container_id', models.BigIntegerField(blank=True, null=True)),
                ('parent_code', models.CharField(blank=True, max_length=128)),
                ('location_code', models.CharField(blank=True, max_length=128)),
                ('zone_code', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('merged', 'Объединен'), ('split', 'Разделен'), ('archived', 'Архив')], default='active', max_length=16)),
                ('gross_weight_g', models.PositiveIntegerField(blank=True, null=True)),
                ('width_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('height_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('depth_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('sku_count', models.PositiveIntegerField(default=0)),
                ('stock_on_hand', models.PositiveIntegerField(default=0)),
                ('stock_free', models.PositiveIntegerField(default=0)),
                ('reserved_qty', models.PositiveIntegerField(default=0)),
                ('marking_count', models.PositiveIntegerField(default=0)),
                ('source_context_type', models.CharField(blank=True, max_length=32)),
                ('source_context_id', models.CharField(blank=True, max_length=64)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('is_manual', models.BooleanField(default=False)),
                ('pilot_revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wms_new_boxes', to='sku.agency')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wms_new_boxes', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wms_new_boxes', to='sklad.warehouselocation')),
            ],
            options={
                'db_table': 'wms_new_box',
                'ordering': ('code', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WmsNewBoxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_snapshot_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('sku_code', models.CharField(max_length=128)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('size', models.CharField(blank=True, max_length=64)),
                ('barcode', models.CharField(blank=True, max_length=128)),
                ('goods_type', models.CharField(blank=True, max_length=64)),
                ('marking_code', models.CharField(blank=True, max_length=256)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('available_qty', models.PositiveIntegerField(default=0)),
                ('reserved_qty', models.PositiveIntegerField(default=0)),
                ('warehouse_state_code', models.CharField(blank=True, max_length=64)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('pilot_revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wms_new_box_items', to='sku.agency')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wms_new.wmsnewbox')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='box_items', to='wms_new.wmsnewproduct')),
            ],
            options={
                'db_table': 'wms_new_box_item',
                'ordering': ('sku_code', 'size', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='wmsnewbox',
            index=models.Index(fields=['agency', 'status'], name='wms_new_box_agency__b6a0bc_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsnewbox',
            index=models.Index(fields=['location', 'status'], name='wms_new_box_locatio_6746e5_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsnewbox',
            index=models.Index(fields=['zone_code', 'status'], name='wms_new_box_zone_co_10bf02_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsnewbox',
            index=models.Index(fields=['stock_on_hand', 'status'], name='wms_new_box_stock_o_4e95e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='wmsnewbox',
            constraint=models.UniqueConstraint(fields=('agency', 'code'), name='uniq_wms_new_box_code'),
        ),
        migrations.AddIndex(
            model_name='wmsnewboxitem',
            index=models.Index(fields=['box', 'sku_code'], name='wms_new_box_box_id_64924f_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsnewboxitem',
            index=models.Index(fields=['product', 'box'], name='wms_new_box_product_7b0cd9_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsnewboxitem',
            index=models.Index(fields=['barcode'], name='wms_new_box_barcode_a2d029_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsnewboxitem',
            index=models.Index(fields=['marking_code'], name='wms_new_box_marking_54f8ac_idx'),
        ),
    ]
