# Generated by Django 6.0 on 2026-08-18 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0011_live_snapshot_query_indexes'),
        ('sku', '0010_sku_weight_gross_kg_sku_weight_net_kg'),
        ('wms_new', '0012_wmsnewbundlecomponent_wmsnewbundlestock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WmsNewMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_event_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('article', models.CharField(blank=True, max_length=128)),
                ('action', models.CharField(choices=[('adjustment', 'Изменение остатка'), ('receipt', 'Поступление товара'), ('writeoff', 'Списание'), ('movement', 'Перемещение')], max_length=16)),
                ('source_location_name', models.CharField(blank=True, max_length=255)),
                ('target_location_name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('balance_after', models.IntegerField(default=0)),
                ('boxes_count', models.PositiveIntegerField(default=0)),
                ('information', models.TextField(blank=True)),
                ('source_event_type', models.CharField(blank=True, max_length=64)),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('occurred_at', models.DateTimeField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_manual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wms_new_movements', to=settings.AUTH_USER_MODEL)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wms_new_movements', to='sku.agency')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='wms_new.wmsnewproduct')),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wms_new_movements_from', to='sklad.warehouselocation')),
                ('target_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wms_new_movements_to', to='sklad.warehouselocation')),
            ],
            options={
                'db_table': 'wms_new_movement',
                'ordering': ('-occurred_at', '-id'),
                'indexes': [models.Index(fields=['agency', 'action', 'occurred_at'], name='wms_new_mov_agency__6a44b6_idx'), models.Index(fields=['product', 'occurred_at'], name='wms_new_mov_product_d9539b_idx'), models.Index(fields=['source_location', 'occurred_at'], name='wms_new_mov_source__fad279_idx'), models.Index(fields=['target_location', 'occurred_at'], name='wms_new_mov_target__1707f5_idx')],
            },
        ),
    ]
