# Generated by Django 6.0 on 2026-08-18 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0010_sku_weight_gross_kg_sku_weight_net_kg'),
        ('wms_new', '0013_wmsnewmovement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WmsNewLogisticsManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_trip_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('sent', 'Отправлен'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='new', max_length=16)),
                ('logistics_company', models.CharField(blank=True, max_length=255)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('total_weight_g', models.PositiveIntegerField(default=0)),
                ('departure_airport', models.CharField(blank=True, max_length=128)),
                ('destination_airport', models.CharField(blank=True, max_length=128)),
                ('expected_arrival_date', models.DateField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('is_manual', models.BooleanField(default=False)),
                ('pilot_revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wms_new_logistics_manifests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wms_new_logistics_manifest',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='WmsNewLogisticsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_shipping_order_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('number', models.CharField(max_length=128, unique=True)),
                ('tracking_number', models.CharField(blank=True, max_length=128)),
                ('source_type', models.CharField(choices=[('shipping', 'Fullbox'), ('fbs', 'FBS'), ('manual', 'Ручная')], max_length=16)),
                ('source_label', models.CharField(blank=True, max_length=128)),
                ('weight_g', models.PositiveIntegerField(default=0)),
                ('width_mm', models.PositiveIntegerField(default=0)),
                ('height_mm', models.PositiveIntegerField(default=0)),
                ('depth_mm', models.PositiveIntegerField(default=0)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('unmeasured', 'Не измерен'), ('no_dimensions', 'Нет габаритов'), ('error', 'Ошибка'), ('carrier_cancelled', 'Отменён в ТК')], default='unmeasured', max_length=24)),
                ('delivery_status', models.CharField(blank=True, max_length=128)),
                ('error_text', models.TextField(blank=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('is_manual', models.BooleanField(default=False)),
                ('pilot_revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wms_new_logistics_orders', to='sku.agency')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wms_new_logistics_orders', to=settings.AUTH_USER_MODEL)),
                ('source_fbs_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logistics_order', to='wms_new.wmsneworder')),
                ('source_fbs_shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logistics_orders', to='wms_new.wmsnewshipment')),
            ],
            options={
                'db_table': 'wms_new_logistics_order',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='WmsNewLogisticsPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=128, unique=True)),
                ('tracking_number', models.CharField(blank=True, max_length=128)),
                ('carrier_code', models.CharField(choices=[('tanais', 'TANAIS'), ('gbs', 'GBS'), ('manual', 'Ручная'), ('cdek', 'СДЭК'), ('russian_post', 'Почта России')], max_length=32)),
                ('delivery_service', models.CharField(max_length=128)),
                ('warehouse_code', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('sent', 'Отправлено')], default='new', max_length=16)),
                ('weight_g', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wms_new_logistics_packages', to=settings.AUTH_USER_MODEL)),
                ('manifest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='wms_new.wmsnewlogisticsmanifest')),
            ],
            options={
                'db_table': 'wms_new_logistics_package',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='WmsNewLogisticsPackageOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='package_link', to='wms_new.wmsnewlogisticsorder')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_orders', to='wms_new.wmsnewlogisticspackage')),
            ],
            options={
                'db_table': 'wms_new_logistics_package_order',
                'ordering': ('package_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WmsNewLogisticsRouteRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_service', models.CharField(max_length=128, unique=True)),
                ('international_carrier', models.CharField(blank=True, max_length=32)),
                ('local_carrier', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_wms_new_logistics_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wms_new_logistics_route_rule',
                'ordering': ('delivery_service',),
            },
        ),
        migrations.AddIndex(
            model_name='wmsnewlogisticsmanifest',
            index=models.Index(fields=['status', 'created_at'], name='wms_new_log_status_fb68cf_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsnewlogisticsorder',
            index=models.Index(fields=['status', 'created_at'], name='wms_new_log_status_db3553_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsnewlogisticsorder',
            index=models.Index(fields=['source_type', 'created_at'], name='wms_new_log_source__a82380_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsnewlogisticsorder',
            index=models.Index(fields=['tracking_number'], name='wms_new_log_trackin_dffce8_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsnewlogisticspackage',
            index=models.Index(fields=['carrier_code', 'status'], name='wms_new_log_carrier_ad7308_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsnewlogisticspackage',
            index=models.Index(fields=['manifest', 'status'], name='wms_new_log_manifes_0753cf_idx'),
        ),
    ]
