# Generated by Django 6.0 on 2026-08-18 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0011_live_snapshot_query_indexes'),
        ('sku', '0010_sku_weight_gross_kg_sku_weight_net_kg'),
        ('wms_new', '0014_wmsnewlogisticsmanifest_wmsnewlogisticsorder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WmsNewDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('document_type', models.CharField(choices=[('receipt', 'Приход'), ('writeoff', 'Расход')], max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('posted', 'Проведен'), ('cancelled', 'Отменен')], default='draft', max_length=16)),
                ('basis', models.CharField(blank=True, max_length=255)),
                ('warehouse_name', models.CharField(default='Основной склад', max_length=128)),
                ('comment', models.TextField(blank=True)),
                ('internal_comment', models.TextField(blank=True)),
                ('sku_count', models.PositiveIntegerField(default=0)),
                ('unit_count', models.PositiveIntegerField(default=0)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('is_manual', models.BooleanField(default=False)),
                ('pilot_revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wms_new_documents', to='sku.agency')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wms_new_documents', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_wms_new_documents', to=settings.AUTH_USER_MODEL)),
                ('source_acceptance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='wms_new.wmsnewacceptance')),
                ('source_shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='wms_new.wmsnewshipment')),
            ],
            options={
                'db_table': 'wms_new_document',
                'ordering': ('-source_created_at', '-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='WmsNewDocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('article', models.CharField(blank=True, max_length=128)),
                ('barcode', models.CharField(blank=True, max_length=128)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('source_line_key', models.CharField(blank=True, max_length=160)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wms_new.wmsnewdocument')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wms_new_document_items', to='sklad.warehouselocation')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_items', to='wms_new.wmsnewproduct')),
            ],
            options={
                'db_table': 'wms_new_document_item',
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='wmsnewdocument',
            index=models.Index(fields=['document_type', 'status', 'source_created_at'], name='wms_new_doc_documen_a53aa2_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsnewdocument',
            index=models.Index(fields=['agency', 'document_type', 'status'], name='wms_new_doc_agency__e38fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsnewdocumentitem',
            index=models.Index(fields=['document', 'product'], name='wms_new_doc_documen_39fa3d_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsnewdocumentitem',
            index=models.Index(fields=['document', 'article'], name='wms_new_doc_documen_d65652_idx'),
        ),
    ]
