# Generated by Django 6.0 on 2026-08-18 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0010_sku_weight_gross_kg_sku_weight_net_kg'),
        ('wms_new', '0016_wmsnewmarketplacestock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WmsNewInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, unique=True)),
                ('invoice_type', models.CharField(choices=[('services', 'Счет на услуги'), ('balance', 'Счет на пополнение баланса')], default='services', max_length=16)),
                ('requisites', models.CharField(blank=True, max_length=255)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('ready', 'Готовый счет'), ('cancelled', 'Отменен')], default='draft', max_length=16)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('pilot_revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wms_new_invoices', to='sku.agency')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wms_new_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wms_new_invoice',
                'ordering': ('-invoice_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='WmsNewBillingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('task', 'Задача'), ('storage', 'Хранение'), ('fbs', 'FBS')], max_length=16)),
                ('source_key', models.CharField(max_length=160)),
                ('title', models.CharField(max_length=255)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('marketplace', models.CharField(blank=True, max_length=64)),
                ('integration', models.CharField(blank=True, max_length=128)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('unpriced', 'Не протарифицировано'), ('priced', 'Протарифицировано, не в счете'), ('invoiced', 'В счете'), ('archived', 'Архив')], default='unpriced', max_length=16)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('pilot_revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wms_new_billing_items', to='sku.agency')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wms_new_billing_items', to=settings.AUTH_USER_MODEL)),
                ('source_shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_items', to='wms_new.wmsnewshipment')),
                ('source_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_items', to='wms_new.wmsnewtask')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='wms_new.wmsnewinvoice')),
            ],
            options={
                'db_table': 'wms_new_billing_item',
                'ordering': ('-occurred_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='WmsNewPartnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('wb_products_enabled', models.BooleanField(default=False)),
                ('wb_orders_enabled', models.BooleanField(default=False)),
                ('ozon_products_enabled', models.BooleanField(default=False)),
                ('ozon_orders_enabled', models.BooleanField(default=False)),
                ('requisites', models.CharField(blank=True, max_length=255)),
                ('is_manual', models.BooleanField(default=False)),
                ('pilot_revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wms_new_partner_profiles', to=settings.AUTH_USER_MODEL)),
                ('source_agency', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wms_new_partner_profile', to='sku.agency')),
            ],
            options={
                'db_table': 'wms_new_partner_profile',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WmsNewPrimaryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, unique=True)),
                ('document_type', models.CharField(choices=[('act', 'Акт'), ('goods_invoice', 'Товарная накладная')], default='act', max_length=24)),
                ('period', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('ready', 'Готов')], default='ready', max_length=16)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wms_new_primary_documents', to='sku.agency')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wms_new_primary_documents', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_documents', to='wms_new.wmsnewinvoice')),
            ],
            options={
                'db_table': 'wms_new_primary_document',
                'ordering': ('-period', 'agency_id', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='wmsnewinvoice',
            index=models.Index(fields=['agency', 'status'], name='wms_new_inv_agency__051123_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsnewinvoice',
            index=models.Index(fields=['status', 'due_date'], name='wms_new_inv_status_8f2a04_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsnewbillingitem',
            index=models.Index(fields=['kind', 'status', 'agency'], name='wms_new_bil_kind_9aedb8_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsnewbillingitem',
            index=models.Index(fields=['invoice', 'status'], name='wms_new_bil_invoice_87daee_idx'),
        ),
        migrations.AddConstraint(
            model_name='wmsnewbillingitem',
            constraint=models.UniqueConstraint(fields=('kind', 'source_key'), name='uniq_wms_new_billing_source'),
        ),
        migrations.AddIndex(
            model_name='wmsnewpartnerprofile',
            index=models.Index(fields=['is_active', 'name'], name='wms_new_par_is_acti_f495e5_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsnewprimarydocument',
            index=models.Index(fields=['period', 'document_type'], name='wms_new_pri_period_5ad05a_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsnewprimarydocument',
            index=models.Index(fields=['agency', 'period'], name='wms_new_pri_agency__338f57_idx'),
        ),
    ]
