# Generated by Django 6.0 on 2026-08-19 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0010_sku_weight_gross_kg_sku_weight_net_kg'),
        ('wms_new', '0017_wmsnewinvoice_wmsnewbillingitem_wmsnewpartnerprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wmsnewwave',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wms_new_waves', to='sku.agency'),
        ),
        migrations.CreateModel(
            name='WmsNewWavePickLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подбор'), ('picking', 'Подбирается'), ('picked', 'Подобран'), ('shortage', 'Недостача'), ('skipped', 'Пропущен'), ('cancelled', 'Отменен')], default='pending', max_length=16)),
                ('planned_quantity', models.PositiveIntegerField(default=1)),
                ('picked_quantity', models.PositiveIntegerField(default=0)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wave_pick_lines', to='wms_new.wmsneworder')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wave_pick_lines', to='wms_new.wmsneworderitem')),
                ('picked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picked_wms_new_lines', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wave_pick_lines', to='wms_new.wmsnewproduct')),
                ('wave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_lines', to='wms_new.wmsnewwave')),
            ],
            options={
                'db_table': 'wms_new_wave_pick_line',
                'ordering': ('sequence', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WmsNewWaveAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reserved', 'Зарезервировано'), ('picking', 'Подбирается'), ('picked', 'Подобрано'), ('shortage', 'Недостача'), ('skipped', 'Пропущено'), ('released', 'Резерв снят'), ('cancelled', 'Отменено')], default='reserved', max_length=16)),
                ('source_box_code', models.CharField(blank=True, max_length=128)),
                ('source_place_code', models.CharField(blank=True, max_length=128)),
                ('source_place_name', models.CharField(blank=True, max_length=255)),
                ('reserved_quantity', models.PositiveIntegerField(default=0)),
                ('picked_quantity', models.PositiveIntegerField(default=0)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('marking_code', models.CharField(blank=True, max_length=256)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('box_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wave_allocations', to='wms_new.wmsnewboxitem')),
                ('picked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picked_wms_new_allocations', to=settings.AUTH_USER_MODEL)),
                ('pick_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='wms_new.wmsnewwavepickline')),
            ],
            options={
                'db_table': 'wms_new_wave_allocation',
                'ordering': ('sequence', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='wmsnewwavepickline',
            index=models.Index(fields=['wave', 'status', 'sequence'], name='wms_new_wav_wave_id_7b2d70_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsnewwavepickline',
            index=models.Index(fields=['order', 'status'], name='wms_new_wav_order_i_220e06_idx'),
        ),
        migrations.AddConstraint(
            model_name='wmsnewwavepickline',
            constraint=models.UniqueConstraint(fields=('wave', 'order_item'), name='uniq_wms_new_wave_pick_item'),
        ),
        migrations.AddIndex(
            model_name='wmsnewwaveallocation',
            index=models.Index(fields=['pick_line', 'status', 'sequence'], name='wms_new_wav_pick_li_335038_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsnewwaveallocation',
            index=models.Index(fields=['source_place_code', 'status'], name='wms_new_wav_source__c1647c_idx'),
        ),
        migrations.AddIndex(
            model_name='wmsnewwaveallocation',
            index=models.Index(fields=['box_item', 'status'], name='wms_new_wav_box_ite_749db2_idx'),
        ),
    ]
