# Generated by Django 6.0 on 2026-08-19 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0011_live_snapshot_query_indexes'),
        ('wms_new', '0018_alter_wmsnewwave_agency_wmsnewwavepickline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wmsnewreturn',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wms_new_returns', to='sklad.warehouselocation'),
        ),
        migrations.AddField(
            model_name='wmsnewreturn',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_wms_new_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wmsnewreturn',
            name='receiving_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wmsnewreturn',
            name='return_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_returns', to='wms_new.wmsnewbox'),
        ),
        migrations.AddField(
            model_name='wmsnewshipment',
            name='total_volume_l',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='wmsnewshipmentorder',
            name='in_supply',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wmsnewshipmentorder',
            name='marketplace_state',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='wmsnewshipmentorder',
            name='volume_l',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='WmsNewReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('article', models.CharField(blank=True, max_length=128)),
                ('barcode', models.CharField(blank=True, max_length=64)),
                ('planned_qty', models.PositiveIntegerField(default=1)),
                ('received_qty', models.PositiveIntegerField(default=0)),
                ('accepted_qty', models.PositiveIntegerField(default=0)),
                ('rejected_qty', models.PositiveIntegerField(default=0)),
                ('condition', models.CharField(choices=[('good', 'Годен к хранению'), ('damaged', 'Поврежден'), ('missing', 'Не поступил')], default='good', max_length=16)),
                ('marking_codes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='wms_new.wmsneworderitem')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='wms_new.wmsnewproduct')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='wms_new.wmsnewreturn')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_wms_new_return_lines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wms_new_return_line',
                'ordering': ('return_request_id', 'id'),
                'constraints': [models.UniqueConstraint(fields=('return_request', 'order_item'), name='uniq_wms_new_return_order_item')],
            },
        ),
    ]
