# Generated by Django 6.0 on 2026-08-19 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms_new', '0019_wmsnewreturn_destination_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wmsnewtask',
            name='client_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wmsnewtask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wmsnewtask',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='wmsnewtask',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='wmsnewtask',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wmsnewtask',
            name='driver_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='wmsnewtask',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='wmsnewtask',
            name='internal_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wmsnewtask',
            name='tariff_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wmsnewtask',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='wmsnewtask',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='wmsnewtask',
            name='warehouse_code',
            field=models.CharField(default='MSK', max_length=64),
        ),
        migrations.CreateModel(
            name='WmsNewTaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='wms_new/task_attachments/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='wms_new.wmsnewtask')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_wms_new_task_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wms_new_task_attachment',
                'ordering': ('task_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WmsNewTaskBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('closed', 'Закрыт')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wms_new_task_boxes', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='wms_new.wmsnewtask')),
            ],
            options={
                'db_table': 'wms_new_task_box',
                'ordering': ('task_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WmsNewTaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_qty', models.PositiveIntegerField(default=1)),
                ('processed_qty', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('technical_requirement', models.TextField(blank=True)),
                ('additional_source', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='wms_new.wmsnewtaskbox')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_items', to='wms_new.wmsnewproduct')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wms_new.wmsnewtask')),
            ],
            options={
                'db_table': 'wms_new_task_item',
                'ordering': ('task_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WmsNewTaskService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wms_new_task_services', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='wms_new.wmsnewtaskitem')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='wms_new.wmsnewtask')),
            ],
            options={
                'db_table': 'wms_new_task_service',
                'ordering': ('task_id', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='wmsnewtaskbox',
            constraint=models.UniqueConstraint(fields=('task', 'code'), name='uniq_wms_new_task_box_code'),
        ),
        migrations.AddConstraint(
            model_name='wmsnewtaskitem',
            constraint=models.UniqueConstraint(fields=('task', 'product'), name='uniq_wms_new_task_product'),
        ),
    ]
