# Generated by Django 6.0 on 2026-08-06 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sku', '0010_sku_weight_gross_kg_sku_weight_net_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='FbsIntegrationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('wb', 'Wildberries'), ('ozon', 'Ozon')], max_length=16, verbose_name='Маркетплейс')),
                ('name', models.CharField(max_length=128, verbose_name='Название профиля')),
                ('external_account_id', models.CharField(blank=True, max_length=128, verbose_name='Внешний кабинет')),
                ('external_warehouse_id', models.CharField(max_length=128, verbose_name='Внешний склад')),
                ('stock_mode', models.CharField(choices=[('disabled', 'Не передавать остатки'), ('managed', 'Передавать остатки из Fullbox')], default='disabled', max_length=16, verbose_name='Передача остатков')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('order_pull_enabled', models.BooleanField(default=False, verbose_name='Получать заказы')),
                ('status_pull_enabled', models.BooleanField(default=False, verbose_name='Получать статусы')),
                ('outbox_enabled', models.BooleanField(default=False, verbose_name='Отправлять команды')),
                ('marking_push_enabled', models.BooleanField(default=False, verbose_name='Передавать КИЗы')),
                ('stock_push_enabled', models.BooleanField(default=False, verbose_name='Передавать остатки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fbs_integration_profiles', to='sku.agency', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Профиль FBS',
                'verbose_name_plural': 'Профили FBS',
                'db_table': 'fbs_integration_profile',
                'ordering': ['agency_id', 'marketplace', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FbsMarketplaceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('external_id', models.CharField(blank=True, max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('payload_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('received', 'Получено'), ('processed', 'Обработано'), ('retry', 'Повтор'), ('failed', 'Ошибка'), ('dead', 'Остановлено')], default='received', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_events', to='fbs.fbsintegrationprofile')),
            ],
            options={
                'db_table': 'fbs_marketplace_event',
                'ordering': ['received_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FbsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_order_id', models.CharField(max_length=128)),
                ('internal_status', models.CharField(choices=[('received', 'Получен'), ('validation_failed', 'Ошибка проверки'), ('awaiting_stock', 'Ожидает товар'), ('reserved', 'Зарезервирован'), ('queued_for_pick', 'В очереди сборки'), ('picking', 'Собирается'), ('picked', 'Отобран'), ('packed', 'Упакован'), ('ready_for_handover', 'Готов к передаче'), ('handed_over', 'Передан'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен'), ('return_pending', 'Ожидается возврат'), ('returned', 'Возвращен'), ('exception', 'Исключение')], default='received', max_length=32)),
                ('marketplace_status', models.CharField(blank=True, max_length=64)),
                ('marketplace_substatus', models.CharField(blank=True, max_length=64)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('ordered_at', models.DateTimeField(blank=True, null=True)),
                ('cutoff_at', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='fbs.fbsintegrationprofile')),
            ],
            options={
                'db_table': 'fbs_order',
                'ordering': ['cutoff_at', 'imported_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FbsMarketplaceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(max_length=64)),
                ('endpoint', models.CharField(max_length=255)),
                ('endpoint_version', models.CharField(blank=True, max_length=32)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('payload_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('confirmed', 'Подтверждено'), ('retry', 'Повтор'), ('failed', 'Ошибка'), ('conflict', 'Конфликт'), ('cancelled', 'Отменено')], default='pending', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_commands', to='fbs.fbsintegrationprofile')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_commands', to='fbs.fbsorder')),
            ],
            options={
                'db_table': 'fbs_marketplace_command',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FbsOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_line_id', models.CharField(max_length=128)),
                ('external_sku', models.CharField(max_length=128)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('requirements', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fbs.fbsorder')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fbs_order_items', to='sku.sku')),
            ],
            options={
                'db_table': 'fbs_order_item',
                'ordering': ['order_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FbsSyncCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(choices=[('orders', 'Заказы'), ('statuses', 'Статусы'), ('stocks', 'Остатки'), ('marking', 'Маркировка')], max_length=32)),
                ('cursor_key', models.CharField(default='default', max_length=64)),
                ('cursor', models.JSONField(blank=True, default=dict)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_cursors', to='fbs.fbsintegrationprofile')),
            ],
            options={
                'db_table': 'fbs_sync_cursor',
            },
        ),
        migrations.AddIndex(
            model_name='fbsintegrationprofile',
            index=models.Index(fields=['agency', 'marketplace', 'is_active'], name='fbs_integra_agency__7cf0d4_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsintegrationprofile',
            index=models.Index(fields=['marketplace', 'external_warehouse_id'], name='fbs_integra_marketp_dc8f5e_idx'),
        ),
        migrations.AddConstraint(
            model_name='fbsintegrationprofile',
            constraint=models.UniqueConstraint(fields=('agency', 'marketplace', 'external_account_id', 'external_warehouse_id'), name='uniq_fbs_profile_account_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='fbsintegrationprofile',
            constraint=models.CheckConstraint(condition=models.Q(('stock_push_enabled', False), ('stock_mode', 'managed'), _connector='OR'), name='fbs_stock_push_requires_managed_mode'),
        ),
        migrations.AddIndex(
            model_name='fbsmarketplaceevent',
            index=models.Index(fields=['status', 'received_at'], name='fbs_marketp_status_3ecb5f_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsmarketplaceevent',
            index=models.Index(fields=['profile', 'event_type', 'external_id'], name='fbs_marketp_profile_a3e670_idx'),
        ),
        migrations.AddConstraint(
            model_name='fbsmarketplaceevent',
            constraint=models.UniqueConstraint(fields=('profile', 'event_type', 'external_id', 'payload_hash'), name='uniq_fbs_marketplace_event_payload'),
        ),
        migrations.AddIndex(
            model_name='fbsorder',
            index=models.Index(fields=['profile', 'internal_status', 'cutoff_at'], name='fbs_order_profile_ff2733_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsorder',
            index=models.Index(fields=['profile', 'marketplace_status'], name='fbs_order_profile_6ee61d_idx'),
        ),
        migrations.AddConstraint(
            model_name='fbsorder',
            constraint=models.UniqueConstraint(fields=('profile', 'external_order_id'), name='uniq_fbs_external_order'),
        ),
        migrations.AddIndex(
            model_name='fbsmarketplacecommand',
            index=models.Index(fields=['status', 'next_attempt_at'], name='fbs_marketp_status_b60631_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsmarketplacecommand',
            index=models.Index(fields=['profile', 'command_type', 'status'], name='fbs_marketp_profile_cd4839_idx'),
        ),
        migrations.AddConstraint(
            model_name='fbsmarketplacecommand',
            constraint=models.UniqueConstraint(fields=('profile', 'idempotency_key'), name='uniq_fbs_command_idempotency'),
        ),
        migrations.AddIndex(
            model_name='fbsorderitem',
            index=models.Index(fields=['order', 'external_sku'], name='fbs_order_i_order_i_4f3de3_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsorderitem',
            index=models.Index(fields=['sku'], name='fbs_order_i_sku_id_3972f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='fbsorderitem',
            constraint=models.UniqueConstraint(fields=('order', 'external_line_id'), name='uniq_fbs_order_line'),
        ),
        migrations.AddConstraint(
            model_name='fbsorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='fbs_order_item_qty_gt_zero'),
        ),
        migrations.AddIndex(
            model_name='fbssynccursor',
            index=models.Index(fields=['profile', 'stream'], name='fbs_sync_cu_profile_5a040b_idx'),
        ),
        migrations.AddConstraint(
            model_name='fbssynccursor',
            constraint=models.UniqueConstraint(fields=('profile', 'stream', 'cursor_key'), name='uniq_fbs_sync_cursor'),
        ),
    ]
