# Generated by Django 6.0 on 2026-08-06 20:18

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbs', '0001_initial'),
        ('sklad', '0010_warehousecontainer_dimensions_weight'),
        ('sku', '0010_sku_weight_gross_kg_sku_weight_net_kg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FbsPallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet_code', models.CharField(max_length=128)),
                ('max_boxes', models.PositiveSmallIntegerField(default=10)),
                ('status', models.CharField(choices=[('planned', 'Запланирована'), ('active', 'Активна'), ('archived', 'Архив')], default='planned', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fbs_pallets', to='sku.agency')),
                ('warehouse_container', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fbs_pallet', to='sklad.warehousecontainer')),
            ],
            options={
                'db_table': 'fbs_pallet',
                'ordering': ['cell__cell_code', 'pallet_code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FbsBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_code', models.CharField(max_length=128)),
                ('width_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('height_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('depth_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Запланирован'), ('active', 'Активен'), ('archived', 'Архив')], default='planned', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fbs_boxes', to='sku.agency')),
                ('source_container', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fbs_box', to='sklad.warehousecontainer')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boxes', to='fbs.fbspallet')),
            ],
            options={
                'db_table': 'fbs_box',
                'ordering': ['pallet_id', 'box_code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FbsReplenishmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(blank=True, max_length=64)),
                ('qty_requested', models.PositiveIntegerField()),
                ('qty_planned', models.PositiveIntegerField(default=0)),
                ('qty_moved', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('proposed', 'Предложена'), ('reserved', 'Зарезервирована'), ('in_progress', 'В работе'), ('done', 'Выполнена'), ('canceled', 'Отменена')], default='proposed', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fbs_replenishment_lines', to='sku.sku')),
                ('source_container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fbs_replenishment_lines', to='sklad.warehousecontainer')),
                ('target_box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_lines', to='fbs.fbsbox')),
            ],
            options={
                'db_table': 'fbs_replenishment_line',
                'ordering': ['plan_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FbsReplenishmentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_planned', models.PositiveIntegerField()),
                ('qty_moved', models.PositiveIntegerField(default=0)),
                ('source_snapshot_version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('reserved', 'Зарезервировано'), ('in_progress', 'В работе'), ('done', 'Перемещено'), ('canceled', 'Отменено')], default='reserved', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fbs_replenishment_allocations', to='sklad.warehousestocksnapshot')),
                ('target_box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_allocations', to='fbs.fbsbox')),
                ('warehouse_reserve', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fbs_replenishment_allocation', to='sklad.warehousereserve')),
                ('warehouse_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fbs_replenishment_allocations', to='sklad.warehouseoperationtask')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='fbs.fbsreplenishmentline')),
            ],
            options={
                'db_table': 'fbs_replenishment_allocation',
                'ordering': ['line_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FbsReplenishmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('box', 'Коробами'), ('item', 'Штучный подсорт')], max_length=16)),
                ('status', models.CharField(choices=[('proposed', 'Предложен программой'), ('confirmed', 'Подтвержден кладовщиком'), ('in_progress', 'В работе'), ('done', 'Выполнен'), ('blocked', 'Заблокирован'), ('canceled', 'Отменен')], default='proposed', max_length=16)),
                ('requested_by_role', models.CharField(blank=True, max_length=32)),
                ('comment', models.TextField(blank=True)),
                ('planned_qty', models.PositiveIntegerField(default=0)),
                ('moved_qty', models.PositiveIntegerField(default=0)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fbs_replenishment_plans', to='sku.agency')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_fbs_replenishments', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_fbs_replenishments', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_fbs_replenishments', to=settings.AUTH_USER_MODEL)),
                ('target_box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_plans', to='fbs.fbsbox')),
                ('target_pallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_plans', to='fbs.fbspallet')),
                ('warehouse_operation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fbs_replenishment_plan', to='sklad.warehouseoperation')),
            ],
            options={
                'db_table': 'fbs_replenishment_plan',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='fbsreplenishmentline',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='fbs.fbsreplenishmentplan'),
        ),
        migrations.CreateModel(
            name='FbsStockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_key', models.CharField(max_length=64)),
                ('sku_code', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('size', models.CharField(blank=True, max_length=64)),
                ('barcode', models.CharField(blank=True, max_length=64)),
                ('goods_type', models.CharField(blank=True, max_length=64)),
                ('marking_code', models.CharField(blank=True, max_length=128)),
                ('lot_code', models.CharField(blank=True, max_length=128)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('available_qty', models.PositiveIntegerField(default=0)),
                ('reserved_qty', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fbs_stock_balances', to='sku.agency')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='fbs.fbsbox')),
                ('sku_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fbs_stock_balances', to='sku.sku')),
            ],
            options={
                'db_table': 'fbs_stock_balance',
                'ordering': ['box_id', 'sku_code', 'size', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FbsStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movement', to='fbs.fbsreplenishmentallocation')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_fbs_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fbs_stock_movements', to='sklad.warehousestocksnapshot')),
                ('target_balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='fbs.fbsstockbalance')),
                ('warehouse_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fbs_stock_movement', to='sklad.warehouseevent')),
            ],
            options={
                'db_table': 'fbs_stock_movement',
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FbsStorageCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_code', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fbs_storage_cell', to='sklad.warehouselocation')),
            ],
            options={
                'db_table': 'fbs_storage_cell',
                'ordering': ['cell_code', 'id'],
            },
        ),
        migrations.AddField(
            model_name='fbsreplenishmentplan',
            name='target_cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_plans', to='fbs.fbsstoragecell'),
        ),
        migrations.AddField(
            model_name='fbspallet',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pallets', to='fbs.fbsstoragecell'),
        ),
        migrations.AddIndex(
            model_name='fbsbox',
            index=models.Index(fields=['pallet', 'status'], name='fbs_box_pallet__1b9494_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsbox',
            index=models.Index(fields=['agency', 'status'], name='fbs_box_agency__b8d07e_idx'),
        ),
        migrations.AddConstraint(
            model_name='fbsbox',
            constraint=models.UniqueConstraint(fields=('agency', 'box_code'), name='uniq_fbs_box_code_per_agency'),
        ),
        migrations.AddIndex(
            model_name='fbsreplenishmentallocation',
            index=models.Index(fields=['status', 'created_at'], name='fbs_repleni_status_66baf0_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsreplenishmentallocation',
            index=models.Index(fields=['source_snapshot'], name='fbs_repleni_source__e63b84_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsreplenishmentallocation',
            index=models.Index(fields=['target_box', 'status'], name='fbs_repleni_target__6a9e74_idx'),
        ),
        migrations.AddConstraint(
            model_name='fbsreplenishmentallocation',
            constraint=models.UniqueConstraint(fields=('line', 'source_snapshot', 'target_box'), name='uniq_fbs_replenishment_allocation'),
        ),
        migrations.AddConstraint(
            model_name='fbsreplenishmentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('qty_planned__gt', 0)), name='fbs_allocation_planned_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='fbsreplenishmentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('qty_planned__gte', models.F('qty_moved'))), name='fbs_allocation_moved_lte_planned'),
        ),
        migrations.AddIndex(
            model_name='fbsreplenishmentline',
            index=models.Index(fields=['plan', 'status'], name='fbs_repleni_plan_id_906c39_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsreplenishmentline',
            index=models.Index(fields=['sku_ref'], name='fbs_repleni_sku_ref_8cd33f_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsreplenishmentline',
            index=models.Index(fields=['source_container'], name='fbs_repleni_source__5cc3cd_idx'),
        ),
        migrations.AddConstraint(
            model_name='fbsreplenishmentline',
            constraint=models.CheckConstraint(condition=models.Q(('qty_requested__gt', 0)), name='fbs_line_requested_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='fbsreplenishmentline',
            constraint=models.CheckConstraint(condition=models.Q(('qty_planned__gte', models.F('qty_moved'))), name='fbs_line_moved_lte_planned'),
        ),
        migrations.AddIndex(
            model_name='fbsstockbalance',
            index=models.Index(fields=['agency', 'sku_code'], name='fbs_stock_b_agency__574526_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsstockbalance',
            index=models.Index(fields=['agency', 'barcode'], name='fbs_stock_b_agency__28a8e6_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsstockbalance',
            index=models.Index(fields=['expiry_date'], name='fbs_stock_b_expiry__6bec61_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsstockbalance',
            index=models.Index(fields=['box', 'available_qty'], name='fbs_stock_b_box_id_657c0c_idx'),
        ),
        migrations.AddConstraint(
            model_name='fbsstockbalance',
            constraint=models.UniqueConstraint(fields=('box', 'identity_key'), name='uniq_fbs_stock_identity_per_box'),
        ),
        migrations.AddConstraint(
            model_name='fbsstockbalance',
            constraint=models.UniqueConstraint(condition=models.Q(('marking_code', ''), _negated=True), fields=('agency', 'marking_code'), name='uniq_fbs_marking_code_per_agency'),
        ),
        migrations.AddConstraint(
            model_name='fbsstockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gte', 0)), name='fbs_stock_qty_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='fbsstockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('available_qty__gte', 0)), name='fbs_stock_available_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='fbsstockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_qty__gte', 0)), name='fbs_stock_reserved_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='fbsstockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gte', django.db.models.expressions.CombinedExpression(models.F('available_qty'), '+', models.F('reserved_qty')))), name='fbs_stock_qty_covers_available_reserved'),
        ),
        migrations.AddIndex(
            model_name='fbsstockmovement',
            index=models.Index(fields=['occurred_at'], name='fbs_stock_m_occurre_9a3f41_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsstockmovement',
            index=models.Index(fields=['source_snapshot'], name='fbs_stock_m_source__e95da8_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsstockmovement',
            index=models.Index(fields=['target_balance'], name='fbs_stock_m_target__77bb2c_idx'),
        ),
        migrations.AddConstraint(
            model_name='fbsstockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='fbs_stock_movement_qty_gt_zero'),
        ),
        migrations.AddIndex(
            model_name='fbsreplenishmentplan',
            index=models.Index(fields=['agency', 'status'], name='fbs_repleni_agency__59039f_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsreplenishmentplan',
            index=models.Index(fields=['status', 'created_at'], name='fbs_repleni_status_1bf10c_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsreplenishmentplan',
            index=models.Index(fields=['assigned_to', 'status'], name='fbs_repleni_assigne_502d9d_idx'),
        ),
        migrations.AddConstraint(
            model_name='fbsreplenishmentplan',
            constraint=models.CheckConstraint(condition=models.Q(('planned_qty__gte', models.F('moved_qty'))), name='fbs_plan_moved_lte_planned'),
        ),
        migrations.AddIndex(
            model_name='fbspallet',
            index=models.Index(fields=['agency', 'status'], name='fbs_pallet_agency__0f0f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='fbspallet',
            index=models.Index(fields=['cell', 'status'], name='fbs_pallet_cell_id_db30a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='fbspallet',
            constraint=models.UniqueConstraint(fields=('agency', 'pallet_code'), name='uniq_fbs_pallet_code_per_agency'),
        ),
        migrations.AddConstraint(
            model_name='fbspallet',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['planned', 'active'])), fields=('cell',), name='uniq_active_fbs_pallet_per_cell'),
        ),
        migrations.AddConstraint(
            model_name='fbspallet',
            constraint=models.CheckConstraint(condition=models.Q(('max_boxes__gt', 0)), name='fbs_pallet_max_boxes_gt_zero'),
        ),
    ]
