# Generated by Django 6.0 on 2026-08-06 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbs', '0002_fbspallet_fbsbox_fbsreplenishmentline_and_more'),
        ('sku', '0010_sku_weight_gross_kg_sku_weight_net_kg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FbsPickBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('in_progress', 'В работе'), ('done', 'Завершена'), ('canceled', 'Отменена')], default='queued', max_length=16)),
                ('planned_qty', models.PositiveIntegerField(default=0)),
                ('picked_qty', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fbs_pick_batches', to='sku.agency')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fbs_pick_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fbs_pick_batch',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FbsPickTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('in_progress', 'В работе'), ('picked', 'Отобран'), ('exception', 'Исключение'), ('canceled', 'Отменен')], default='queued', max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('planned_qty', models.PositiveIntegerField(default=0)),
                ('picked_qty', models.PositiveIntegerField(default=0)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_fbs_pick_tasks', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='fbs.fbspickbatch')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pick_tasks', to='fbs.fbsorder')),
            ],
            options={
                'db_table': 'fbs_pick_task',
                'ordering': ['batch_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FbsOrderStockAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_reserved', models.PositiveIntegerField()),
                ('qty_picked', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('reserved', 'Зарезервировано'), ('picking', 'Отбирается'), ('picked', 'Отобрано'), ('released', 'Освобождено'), ('canceled', 'Отменено')], default='reserved', max_length=16)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('picked_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_allocations', to='fbs.fbsstockbalance')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_allocations', to='fbs.fbsorderitem')),
                ('picked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picked_fbs_order_allocations', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_fbs_order_allocations', to=settings.AUTH_USER_MODEL)),
                ('reserved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_fbs_order_allocations', to=settings.AUTH_USER_MODEL)),
                ('pick_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='fbs.fbspicktask')),
            ],
            options={
                'db_table': 'fbs_order_stock_allocation',
                'ordering': ['order_item__order_id', 'order_item_id', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='fbspickbatch',
            index=models.Index(fields=['agency', 'status'], name='fbs_pick_ba_agency__5ecf41_idx'),
        ),
        migrations.AddIndex(
            model_name='fbspickbatch',
            index=models.Index(fields=['status', 'created_at'], name='fbs_pick_ba_status_955c97_idx'),
        ),
        migrations.AddConstraint(
            model_name='fbspickbatch',
            constraint=models.CheckConstraint(condition=models.Q(('planned_qty__gte', models.F('picked_qty'))), name='fbs_pick_batch_picked_lte_planned'),
        ),
        migrations.AddIndex(
            model_name='fbspicktask',
            index=models.Index(fields=['status', 'sort_order', 'created_at'], name='fbs_pick_ta_status_e52f05_idx'),
        ),
        migrations.AddIndex(
            model_name='fbspicktask',
            index=models.Index(fields=['assigned_to', 'status'], name='fbs_pick_ta_assigne_ab8220_idx'),
        ),
        migrations.AddIndex(
            model_name='fbspicktask',
            index=models.Index(fields=['order', 'status'], name='fbs_pick_ta_order_i_04ed5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='fbspicktask',
            constraint=models.UniqueConstraint(fields=('batch', 'order'), name='uniq_fbs_pick_task_batch_order'),
        ),
        migrations.AddConstraint(
            model_name='fbspicktask',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'in_progress'])), fields=('order',), name='uniq_active_fbs_pick_task_per_order'),
        ),
        migrations.AddConstraint(
            model_name='fbspicktask',
            constraint=models.CheckConstraint(condition=models.Q(('planned_qty__gt', 0)), name='fbs_pick_task_planned_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='fbspicktask',
            constraint=models.CheckConstraint(condition=models.Q(('planned_qty__gte', models.F('picked_qty'))), name='fbs_pick_task_picked_lte_planned'),
        ),
        migrations.AddIndex(
            model_name='fbsorderstockallocation',
            index=models.Index(fields=['status', 'reserved_at'], name='fbs_order_s_status_51ce52_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsorderstockallocation',
            index=models.Index(fields=['order_item', 'status'], name='fbs_order_s_order_i_5e74ae_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsorderstockallocation',
            index=models.Index(fields=['balance', 'status'], name='fbs_order_s_balance_368b25_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsorderstockallocation',
            index=models.Index(fields=['pick_task', 'status'], name='fbs_order_s_pick_ta_a07d55_idx'),
        ),
        migrations.AddConstraint(
            model_name='fbsorderstockallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['reserved', 'picking'])), fields=('order_item', 'balance'), name='uniq_active_fbs_order_balance_allocation'),
        ),
        migrations.AddConstraint(
            model_name='fbsorderstockallocation',
            constraint=models.CheckConstraint(condition=models.Q(('qty_reserved__gt', 0)), name='fbs_order_allocation_reserved_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='fbsorderstockallocation',
            constraint=models.CheckConstraint(condition=models.Q(('qty_reserved__gte', models.F('qty_picked'))), name='fbs_order_allocation_picked_lte_reserved'),
        ),
    ]
