# Generated by Django 6.0 on 2026-08-06 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbs', '0003_fbspickbatch_fbspicktask_fbsorderstockallocation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbsorder',
            name='internal_status',
            field=models.CharField(choices=[('received', 'Получен'), ('validation_failed', 'Ошибка проверки'), ('awaiting_stock', 'Ожидает товар'), ('reserved', 'Зарезервирован'), ('queued_for_pick', 'В очереди сборки'), ('picking', 'Собирается'), ('picked', 'Отобран'), ('ready_for_handover', 'Готов к передаче'), ('handed_over', 'Передан'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен'), ('return_pending', 'Ожидается возврат'), ('returned', 'Возвращен'), ('exception', 'Исключение')], default='received', max_length=32),
        ),
        migrations.CreateModel(
            name='FbsOrderLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('wb', 'Wildberries'), ('ozon', 'Ozon')], max_length=16)),
                ('external_label_id', models.CharField(blank=True, max_length=256)),
                ('barcode', models.CharField(blank=True, max_length=512)),
                ('label_format', models.CharField(choices=[('pdf', 'PDF'), ('png', 'PNG'), ('zpl', 'ZPL'), ('other', 'Другой')], default='pdf', max_length=16)),
                ('file_url', models.URLField(blank=True, max_length=1000)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('requested', 'Запрошена'), ('ready', 'Готова'), ('applied', 'Подтверждена'), ('error', 'Ошибка'), ('canceled', 'Отменена')], default='requested', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_fbs_order_labels', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_labels', to='fbs.fbsorder')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_fbs_order_labels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fbs_order_label',
                'ordering': ['requested_at', 'id'],
                'indexes': [models.Index(fields=['status', 'requested_at'], name='fbs_order_l_status_6ccb5a_idx'), models.Index(fields=['marketplace', 'status'], name='fbs_order_l_marketp_cde480_idx'), models.Index(fields=['order', 'status'], name='fbs_order_l_order_i_a5144e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['requested', 'ready'])), fields=('order',), name='uniq_active_fbs_label_per_order'), models.UniqueConstraint(condition=models.Q(('external_label_id', ''), _negated=True), fields=('order', 'external_label_id'), name='uniq_fbs_order_external_label')],
            },
        ),
    ]
