# Generated by Django 6.0 on 2026-08-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbs', '0004_alter_fbsorder_internal_status_fbsorderlabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbsmarketplacecommand',
            name='http_method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PATCH', 'PATCH'), ('PUT', 'PUT')], default='POST', max_length=8),
        ),
        migrations.AddField(
            model_name='fbsorderlabel',
            name='file',
            field=models.FileField(blank=True, upload_to='fbs/order-labels/%Y/%m/%d/'),
        ),
    ]
