# Generated by Django 6.0 on 2026-08-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbs', '0005_fbsmarketplacecommand_http_method_fbsorderlabel_file'),
        ('sklad', '0010_warehousecontainer_dimensions_weight'),
        ('sku', '0010_sku_weight_gross_kg_sku_weight_net_kg'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fbsreplenishmentline',
            constraint=models.UniqueConstraint(condition=models.Q(('source_container__isnull', False), ('status__in', ['proposed', 'reserved', 'in_progress'])), fields=('source_container',), name='uniq_open_fbs_line_per_source_container'),
        ),
    ]
