# Generated by Django 6.0 on 2026-08-07 04:45

import fbs.file_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbs', '0006_fbsreplenishmentline_uniq_open_fbs_line_per_source_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbsorderlabel',
            name='file',
            field=models.FileField(blank=True, storage=fbs.file_storage.FbsLabelFileSystemStorage(), upload_to='order-labels/%Y/%m/%d/'),
        ),
    ]
