# Generated by Django 6.0 on 2026-08-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbs', '0007_alter_fbsorderlabel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbssynccursor',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fbssynccursor',
            name='lease_token',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
