# Generated by Django 6.0 on 2026-08-07 05:21

import django.db.models.deletion
from django.db import migrations, models


def backfill_order_traceability(apps, schema_editor):
    allocation_model = apps.get_model("fbs", "FbsOrderStockAllocation")
    trace_model = apps.get_model("fbs", "FbsOrderTraceability")
    traces = []
    for allocation in allocation_model.objects.select_related("balance").iterator():
        balance = allocation.balance
        trace_status = {
            "picked": "picked",
            "released": "released",
            "canceled": "canceled",
        }.get(allocation.status, "reserved")
        traces.append(
            trace_model(
                allocation_id=allocation.id,
                marking_code=str(balance.marking_code or "").strip(),
                lot_code=str(balance.lot_code or "").strip(),
                expiry_date=balance.expiry_date,
                qty=allocation.qty_reserved,
                status=trace_status,
            )
        )
    trace_model.objects.bulk_create(traces, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('fbs', '0008_fbssynccursor_lease_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FbsOrderTraceability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marking_code', models.CharField(blank=True, max_length=128)),
                ('lot_code', models.CharField(blank=True, max_length=128)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('qty', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('reserved', 'Зарезервировано'), ('picked', 'Отобрано'), ('released', 'Освобождено'), ('canceled', 'Отменено')], default='reserved', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='traceability', to='fbs.fbsorderstockallocation')),
            ],
            options={
                'db_table': 'fbs_order_traceability',
                'ordering': ['allocation_id'],
            },
        ),
        migrations.CreateModel(
            name='FbsMarketplaceMetadataTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_type', models.CharField(choices=[('marking_code', 'КИЗ'), ('expiration', 'Срок годности')], max_length=32)),
                ('value', models.TextField()),
                ('is_required', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('prepared', 'Подготовлено'), ('queued', 'В очереди'), ('sent', 'Отправлено'), ('confirmed', 'Подтверждено'), ('retry', 'Повтор'), ('failed', 'Ошибка'), ('conflict', 'Конфликт'), ('canceled', 'Отменено')], default='prepared', max_length=16)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('external_status', models.CharField(blank=True, max_length=128)),
                ('last_error', models.TextField(blank=True)),
                ('prepared_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metadata_transfers', to='fbs.fbsorderitem')),
                ('traceability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metadata_transfers', to='fbs.fbsordertraceability')),
            ],
            options={
                'db_table': 'fbs_marketplace_metadata_transfer',
                'ordering': ['order_item__order_id', 'order_item_id', 'id'],
            },
        ),
        migrations.RunPython(backfill_order_traceability, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='fbsordertraceability',
            index=models.Index(fields=['status', 'created_at'], name='fbs_order_t_status_82fbac_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsordertraceability',
            index=models.Index(fields=['lot_code', 'expiry_date'], name='fbs_order_t_lot_cod_33c861_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsordertraceability',
            index=models.Index(fields=['marking_code'], name='fbs_order_t_marking_4c7c33_idx'),
        ),
        migrations.AddConstraint(
            model_name='fbsordertraceability',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='fbs_traceability_qty_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='fbsordertraceability',
            constraint=models.CheckConstraint(condition=models.Q(('marking_code', ''), ('qty', 1), _connector='OR'), name='fbs_traceability_marking_qty_one'),
        ),
        migrations.AddIndex(
            model_name='fbsmarketplacemetadatatransfer',
            index=models.Index(fields=['order_item', 'status'], name='fbs_marketp_order_i_a6964c_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsmarketplacemetadatatransfer',
            index=models.Index(fields=['metadata_type', 'status'], name='fbs_marketp_metadat_cb7ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsmarketplacemetadatatransfer',
            index=models.Index(fields=['status', 'prepared_at'], name='fbs_marketp_status_d6d029_idx'),
        ),
        migrations.AddConstraint(
            model_name='fbsmarketplacemetadatatransfer',
            constraint=models.UniqueConstraint(condition=models.Q(('traceability__isnull', False)), fields=('traceability', 'metadata_type'), name='uniq_fbs_traceability_metadata_type'),
        ),
    ]
