# Generated by Django 6.0 on 2026-08-08 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_agentcommand_agent_agent_status_f70c90_idx_and_more'),
        ('fbs', '0011_fbsmarketplacecommand_request_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FbsEquipmentCodeSequence',
            fields=[
                ('kind', models.CharField(choices=[('workstation', 'Рабочее место'), ('cart', 'Тележка')], max_length=16, primary_key=True, serialize=False)),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Счетчик оборудования FBS',
                'verbose_name_plural': 'Счетчики оборудования FBS',
                'db_table': 'fbs_equipment_code_sequence',
            },
        ),
        migrations.CreateModel(
            name='FbsPickingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=64, unique=True, verbose_name='Штрихкод')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fbs_picking_carts', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_fbs_picking_carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тележка FBS',
                'verbose_name_plural': 'Тележки FBS',
                'db_table': 'fbs_picking_cart',
                'ordering': ['name', 'id'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='fbs_picking_is_acti_360af5_idx')],
            },
        ),
        migrations.CreateModel(
            name='FbsWorkstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=64, unique=True, verbose_name='Штрихкод')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('printer_name', models.CharField(blank=True, max_length=255, verbose_name='Принтер этикеток')),
                ('max_parallel_waves', models.PositiveSmallIntegerField(default=2, verbose_name='Максимум параллельных волн')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fbs_workstations', to=settings.AUTH_USER_MODEL)),
                ('device_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fbs_workstations', to='agent.deviceagent', verbose_name='Агент рабочего места')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_fbs_workstations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рабочее место FBS',
                'verbose_name_plural': 'Рабочие места FBS',
                'db_table': 'fbs_workstation',
                'ordering': ['name', 'id'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='fbs_worksta_is_acti_3b9495_idx'), models.Index(fields=['device_agent', 'is_active'], name='fbs_worksta_device__6cc19b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('max_parallel_waves__gte', 1), ('max_parallel_waves__lte', 2)), name='fbs_workstation_parallel_waves_1_2')],
            },
        ),
    ]
