# Generated by Django 6.0 on 2026-08-08 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbs', '0012_fbsequipmentcodesequence_fbspickingcart_and_more'),
        ('sku', '0010_sku_weight_gross_kg_sku_weight_net_kg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FbsClientStoragePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_mode', models.CharField(choices=[('liters', 'Хранение в литрах'), ('pallets', 'Паллетное хранение')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fbs_client_storage_policy',
                'ordering': ['agency_id'],
            },
        ),
        migrations.CreateModel(
            name='FbsHandoverBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_supply_id', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('open', 'Сканирование'), ('ready', 'Готова к отгрузке'), ('dispatched', 'Передана водителю'), ('accepted', 'Принята маркетплейсом'), ('problem', 'Проблема')], default='open', max_length=16)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fbs_handover_batch',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FbsHandoverBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(max_length=256, unique=True)),
                ('external_box_id', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('closed', 'Закрыт'), ('scanned', 'Просканирован кладовщиком'), ('dispatched', 'Передан водителю'), ('accepted', 'Принят маркетплейсом'), ('problem', 'Проблема')], default='open', max_length=16)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('problem_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fbs_handover_box',
                'ordering': ['batch_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FbsHandoverOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fbs_handover_order',
                'ordering': ['box_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FbsInternalMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('box', 'Короб'), ('item', 'Штучно')], max_length=16)),
                ('status', models.CharField(choices=[('proposed', 'Предложено'), ('in_progress', 'В работе'), ('done', 'Выполнено'), ('blocked', 'Заблокировано'), ('canceled', 'Отменено')], default='proposed', max_length=16)),
                ('planned_qty', models.PositiveIntegerField(default=0)),
                ('moved_qty', models.PositiveIntegerField(default=0)),
                ('comment', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fbs_internal_movement',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FbsInventoryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_qty', models.PositiveIntegerField()),
                ('first_count_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('second_count_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('final_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('approved_delta', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fbs_inventory_line',
                'ordering': ['balance__box_id', 'balance_id'],
            },
        ),
        migrations.CreateModel(
            name='FbsInventoryScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_round', models.PositiveSmallIntegerField(choices=[(1, 'Первый'), (2, 'Повторный')])),
                ('scan_code', models.CharField(max_length=256)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fbs_inventory_scan',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FbsInventorySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('all', 'Весь FBS'), ('agency', 'Клиент'), ('cell', 'Ячейка'), ('pallet', 'Паллета'), ('box', 'Короб'), ('sku', 'SKU клиента')], max_length=16)),
                ('mode', models.CharField(choices=[('audit', 'Аудит без блокировки'), ('drain', 'После завершения активных операций'), ('immediate', 'Немедленная блокировка')], default='drain', max_length=16)),
                ('status', models.CharField(choices=[('planned', 'Запланирована'), ('draining', 'Ожидает завершения операций'), ('counting', 'Первый пересчет'), ('recount', 'Повторный пересчет'), ('approval', 'Ожидает утверждения'), ('done', 'Завершена'), ('canceled', 'Отменена')], default='planned', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fbs_inventory_session',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FbsPickException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_type', models.CharField(choices=[('not_found', 'Товар не найден'), ('damaged', 'Товар поврежден'), ('barcode', 'Штрихкод не читается'), ('other', 'Другая проблема')], max_length=32)),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('resolved', 'Решена'), ('canceled', 'Отменена')], default='open', max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fbs_pick_exception',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FbsReplenishmentPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_qty', models.PositiveIntegerField(default=0)),
                ('target_qty', models.PositiveIntegerField(default=0)),
                ('auto_suggest', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fbs_replenishment_policy',
                'ordering': ['agency_id', 'sku_id'],
            },
        ),
        migrations.CreateModel(
            name='FbsStorageLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('all', 'Весь FBS'), ('agency', 'Клиент'), ('cell', 'Ячейка'), ('pallet', 'Паллета'), ('box', 'Короб'), ('sku', 'SKU клиента')], max_length=16)),
                ('block_new_reservations', models.BooleanField(default=True)),
                ('block_execution', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fbs_storage_lock',
            },
        ),
        migrations.AddField(
            model_name='fbsorder',
            name='hold_reason',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fbsorder',
            name='problem_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fbspickbatch',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_fbs_pick_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fbspickbatch',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pick_batches', to='fbs.fbspickingcart'),
        ),
        migrations.AddField(
            model_name='fbspickbatch',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fbspickbatch',
            name='workstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pick_batches', to='fbs.fbsworkstation'),
        ),
        migrations.AddField(
            model_name='fbsstoragecell',
            name='client_cluster',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fbsstoragecell',
            name='purpose',
            field=models.CharField(choices=[('pick', 'Нижний ярус отбора'), ('reserve', 'Верхний ярус резерва'), ('flex', 'Универсальная')], default='flex', max_length=16),
        ),
        migrations.AddIndex(
            model_name='fbspickbatch',
            index=models.Index(fields=['assigned_to', 'status'], name='fbs_pick_ba_assigne_537c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='fbspickbatch',
            index=models.Index(fields=['workstation', 'status'], name='fbs_pick_ba_worksta_79425f_idx'),
        ),
        migrations.AddConstraint(
            model_name='fbspickbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('cart__isnull', False), ('status', 'in_progress')), fields=('cart',), name='uniq_active_fbs_wave_per_cart'),
        ),
        migrations.AddField(
            model_name='fbsclientstoragepolicy',
            name='agency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fbs_storage_policy', to='sku.agency'),
        ),
        migrations.AddField(
            model_name='fbshandoverbatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fbs_handover_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fbshandoverbatch',
            name='dispatched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_fbs_handover_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fbshandoverbatch',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handover_batches', to='fbs.fbsintegrationprofile'),
        ),
        migrations.AddField(
            model_name='fbshandoverbox',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boxes', to='fbs.fbshandoverbatch'),
        ),
        migrations.AddField(
            model_name='fbshandoverbox',
            name='scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_fbs_handover_boxes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fbshandoverorder',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_fbs_handover_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fbshandoverorder',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='fbs.fbshandoverbox'),
        ),
        migrations.AddField(
            model_name='fbshandoverorder',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='handover_order', to='fbs.fbsorder'),
        ),
        migrations.AddField(
            model_name='fbsinternalmovement',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fbs_movements', to='sku.agency'),
        ),
        migrations.AddField(
            model_name='fbsinternalmovement',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_fbs_internal_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fbsinternalmovement',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_fbs_internal_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fbsinternalmovement',
            name='source_balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='internal_movements', to='fbs.fbsstockbalance'),
        ),
        migrations.AddField(
            model_name='fbsinternalmovement',
            name='source_box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_fbs_movements', to='fbs.fbsbox'),
        ),
        migrations.AddField(
            model_name='fbsinternalmovement',
            name='target_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_item_fbs_movements', to='fbs.fbsbox'),
        ),
        migrations.AddField(
            model_name='fbsinternalmovement',
            name='target_pallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_fbs_movements', to='fbs.fbspallet'),
        ),
        migrations.AddField(
            model_name='fbsinventoryline',
            name='balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_lines', to='fbs.fbsstockbalance'),
        ),
        migrations.AddField(
            model_name='fbsinventoryscan',
            name='counted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fbs_inventory_scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fbsinventoryscan',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='fbs.fbsinventoryline'),
        ),
        migrations.AddField(
            model_name='fbsinventorysession',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fbs_inventory_sessions', to='sku.agency'),
        ),
        migrations.AddField(
            model_name='fbsinventorysession',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_fbs_inventory_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fbsinventorysession',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_sessions', to='fbs.fbsbox'),
        ),
        migrations.AddField(
            model_name='fbsinventorysession',
            name='cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_sessions', to='fbs.fbsstoragecell'),
        ),
        migrations.AddField(
            model_name='fbsinventorysession',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fbs_inventory_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fbsinventorysession',
            name='first_counter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_fbs_inventory_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fbsinventorysession',
            name='pallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_sessions', to='fbs.fbspallet'),
        ),
        migrations.AddField(
            model_name='fbsinventorysession',
            name='second_counter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_fbs_inventory_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fbsinventorysession',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fbs_inventory_sessions', to='sku.sku'),
        ),
        migrations.AddField(
            model_name='fbsinventoryline',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='fbs.fbsinventorysession'),
        ),
        migrations.AddField(
            model_name='fbspickexception',
            name='allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='fbs.fbsorderstockallocation'),
        ),
        migrations.AddField(
            model_name='fbspickexception',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fbs_pick_exceptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fbspickexception',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_fbs_pick_exceptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fbspickexception',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='fbs.fbspicktask'),
        ),
        migrations.AddField(
            model_name='fbsreplenishmentpolicy',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fbs_replenishment_policies', to='sku.agency'),
        ),
        migrations.AddField(
            model_name='fbsreplenishmentpolicy',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fbs_replenishment_policies', to='sku.sku'),
        ),
        migrations.AddField(
            model_name='fbsstoragelock',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sku.agency'),
        ),
        migrations.AddField(
            model_name='fbsstoragelock',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fbs.fbsbox'),
        ),
        migrations.AddField(
            model_name='fbsstoragelock',
            name='cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fbs.fbsstoragecell'),
        ),
        migrations.AddField(
            model_name='fbsstoragelock',
            name='pallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fbs.fbspallet'),
        ),
        migrations.AddField(
            model_name='fbsstoragelock',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_lock', to='fbs.fbsinventorysession'),
        ),
        migrations.AddField(
            model_name='fbsstoragelock',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sku.sku'),
        ),
        migrations.AddIndex(
            model_name='fbshandoverbatch',
            index=models.Index(fields=['profile', 'status'], name='fbs_handove_profile_9923d5_idx'),
        ),
        migrations.AddIndex(
            model_name='fbshandoverbatch',
            index=models.Index(fields=['status', 'created_at'], name='fbs_handove_status_806080_idx'),
        ),
        migrations.AddIndex(
            model_name='fbshandoverbox',
            index=models.Index(fields=['batch', 'status'], name='fbs_handove_batch_i_70e7f9_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsinternalmovement',
            index=models.Index(fields=['agency', 'status'], name='fbs_interna_agency__70217f_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsinternalmovement',
            index=models.Index(fields=['assigned_to', 'status'], name='fbs_interna_assigne_a765c1_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsinternalmovement',
            index=models.Index(fields=['source_box', 'status'], name='fbs_interna_source__7e6d7a_idx'),
        ),
        migrations.AddConstraint(
            model_name='fbsinternalmovement',
            constraint=models.CheckConstraint(condition=models.Q(('planned_qty__gte', models.F('moved_qty'))), name='fbs_internal_movement_moved_lte_planned'),
        ),
        migrations.AddIndex(
            model_name='fbsinventoryscan',
            index=models.Index(fields=['line', 'count_round'], name='fbs_invento_line_id_188166_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsinventoryscan',
            index=models.Index(fields=['scan_code'], name='fbs_invento_scan_co_1b9f96_idx'),
        ),
        migrations.AddConstraint(
            model_name='fbsinventoryscan',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='fbs_inventory_scan_qty_gt_zero'),
        ),
        migrations.AddIndex(
            model_name='fbsinventorysession',
            index=models.Index(fields=['status', 'created_at'], name='fbs_invento_status_d1e444_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsinventorysession',
            index=models.Index(fields=['agency', 'status'], name='fbs_invento_agency__41acdb_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsinventorysession',
            index=models.Index(fields=['cell', 'status'], name='fbs_invento_cell_id_3d872e_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsinventoryline',
            index=models.Index(fields=['session', 'balance'], name='fbs_invento_session_598c59_idx'),
        ),
        migrations.AddConstraint(
            model_name='fbsinventoryline',
            constraint=models.UniqueConstraint(fields=('session', 'balance'), name='uniq_fbs_inventory_session_balance'),
        ),
        migrations.AddIndex(
            model_name='fbspickexception',
            index=models.Index(fields=['status', 'created_at'], name='fbs_pick_ex_status_a10d0b_idx'),
        ),
        migrations.AddIndex(
            model_name='fbspickexception',
            index=models.Index(fields=['task', 'status'], name='fbs_pick_ex_task_id_3923e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='fbspickexception',
            constraint=models.UniqueConstraint(condition=models.Q(('allocation__isnull', False), ('status', 'open')), fields=('allocation',), name='uniq_open_fbs_exception_per_allocation'),
        ),
        migrations.AddIndex(
            model_name='fbsreplenishmentpolicy',
            index=models.Index(fields=['agency', 'is_active'], name='fbs_repleni_agency__3ae6e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='fbsreplenishmentpolicy',
            constraint=models.UniqueConstraint(fields=('agency', 'sku'), name='uniq_fbs_replenishment_policy'),
        ),
        migrations.AddConstraint(
            model_name='fbsreplenishmentpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('target_qty__gte', models.F('minimum_qty'))), name='fbs_replenishment_target_gte_minimum'),
        ),
        migrations.AddIndex(
            model_name='fbsstoragelock',
            index=models.Index(fields=['is_active', 'block_new_reservations'], name='fbs_storage_is_acti_c954d4_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsstoragelock',
            index=models.Index(fields=['is_active', 'block_execution'], name='fbs_storage_is_acti_d8b86c_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsstoragelock',
            index=models.Index(fields=['agency', 'is_active'], name='fbs_storage_agency__543262_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsstoragelock',
            index=models.Index(fields=['cell', 'is_active'], name='fbs_storage_cell_id_76ff69_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsstoragelock',
            index=models.Index(fields=['pallet', 'is_active'], name='fbs_storage_pallet__e0588a_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsstoragelock',
            index=models.Index(fields=['box', 'is_active'], name='fbs_storage_box_id_422a75_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsstoragelock',
            index=models.Index(fields=['sku', 'is_active'], name='fbs_storage_sku_id_03f2ab_idx'),
        ),
    ]
