# Generated by Django 6.0 on 2026-08-08 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbs', '0013_fbsclientstoragepolicy_fbshandoverbatch_and_more'),
        ('sku', '0010_sku_weight_gross_kg_sku_weight_net_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='FbsStorageDailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateField()),
                ('billing_mode', models.CharField(choices=[('liters', 'Хранение в литрах'), ('pallets', 'Паллетное хранение')], max_length=16)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('volume_liters', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('pallet_places', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('dimensions_complete', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fbs_storage_daily_usage', to='sku.agency')),
                ('pallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_usage', to='fbs.fbspallet')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fbs_storage_daily_usage', to='sku.sku')),
            ],
            options={
                'db_table': 'fbs_storage_daily_usage',
                'ordering': ['-usage_date', 'agency_id', 'sku_id', 'pallet_id'],
                'indexes': [models.Index(fields=['usage_date', 'agency'], name='fbs_storage_usage_d_0682e8_idx'), models.Index(fields=['agency', 'billing_mode', 'usage_date'], name='fbs_storage_agency__6dffa7_idx')],
                'constraints': [models.UniqueConstraint(fields=('usage_date', 'agency', 'billing_mode', 'sku', 'pallet'), name='uniq_fbs_daily_storage_usage')],
            },
        ),
    ]
