# Generated by Django 6.0 on 2026-08-08 06:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbs', '0014_fbsstoragedailyusage'),
        ('sku', '0010_sku_weight_gross_kg_sku_weight_net_kg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fbspickbatch',
            name='uniq_active_fbs_wave_per_cart',
        ),
        migrations.AlterField(
            model_name='fbspickbatch',
            name='status',
            field=models.CharField(choices=[('queued', 'В очереди'), ('in_progress', 'В работе'), ('verification', 'Проверка'), ('done', 'Завершена'), ('canceled', 'Отменена')], default='queued', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='fbspickbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('cart__isnull', False), ('status__in', ['in_progress', 'verification'])), fields=('cart',), name='uniq_active_fbs_wave_per_cart'),
        ),
    ]
