# Generated by Django 6.0 on 2026-08-08 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbs', '0015_remove_fbspickbatch_uniq_active_fbs_wave_per_cart_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FbsComplianceOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_type', models.CharField(choices=[('marking_code', 'КИЗ'), ('expiration', 'Срок годности')], max_length=32)),
                ('reason', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_fbs_compliance_overrides', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_overrides', to='fbs.fbsorder')),
            ],
            options={
                'db_table': 'fbs_compliance_override',
                'ordering': ['-approved_at', '-id'],
                'indexes': [models.Index(fields=['order', 'is_active'], name='fbs_complia_order_i_598b6d_idx'), models.Index(fields=['metadata_type', 'is_active'], name='fbs_complia_metadat_4440cb_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('order', 'metadata_type'), name='uniq_active_fbs_compliance_override')],
            },
        ),
    ]
