# Generated by Django 6.0 on 2026-08-09 05:17

from django.db import migrations, models


def backfill_order_item_barcodes(apps, schema_editor):
    order_item_model = apps.get_model("fbs", "FbsOrderItem")
    for item in order_item_model.objects.filter(barcode="").iterator(chunk_size=1000):
        payload = item.raw_payload if isinstance(item.raw_payload, dict) else {}
        raw_barcodes = payload.get("skus")
        if not isinstance(raw_barcodes, list):
            raw_barcodes = payload.get("barcodes")
        if not isinstance(raw_barcodes, list):
            continue
        barcodes = tuple(
            dict.fromkeys(
                str(value or "").strip()
                for value in raw_barcodes
                if str(value or "").strip()
            )
        )
        if len(barcodes) == 1:
            order_item_model.objects.filter(pk=item.pk).update(barcode=barcodes[0])


class Migration(migrations.Migration):

    dependencies = [
        ('fbs', '0017_remove_fbspickbatch_uniq_active_fbs_wave_per_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbsorderitem',
            name='barcode',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fbsreplenishmentline',
            name='barcode',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RunPython(backfill_order_item_barcodes, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='fbsorderitem',
            index=models.Index(fields=['order', 'barcode'], name='fbs_order_i_order_i_1bbf24_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsreplenishmentline',
            index=models.Index(fields=['plan', 'barcode'], name='fbs_repleni_plan_id_8074a5_idx'),
        ),
    ]
