# Generated by Django 6.0 on 2026-08-09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fbs", "0018_fbsorderitem_barcode_fbsreplenishmentline_barcode_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FbsClientMovementRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mode", models.CharField(choices=[("box", "Коробами"), ("item", "Поштучно")], max_length=16)),
                ("status", models.CharField(choices=[("submitted", "Подана"), ("approved", "Подтверждена складом"), ("in_progress", "В работе"), ("completed", "Выполнена"), ("rejected", "Отклонена"), ("canceled", "Отменена")], default="submitted", max_length=16)),
                ("source_file_name", models.CharField(blank=True, max_length=255)),
                ("comment", models.TextField(blank=True)),
                ("requested_qty", models.PositiveIntegerField(default=0)),
                ("requested_box_count", models.PositiveIntegerField(default=0)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("agency", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="fbs_client_movement_requests", to="sku.agency")),
                ("requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_fbs_client_movement_requests", to=settings.AUTH_USER_MODEL)),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_fbs_client_movement_requests", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "fbs_client_movement_request",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="FbsClientMovementRequestLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("barcode", models.CharField(max_length=64)),
                ("sku_code", models.CharField(max_length=64)),
                ("product_name", models.CharField(blank=True, max_length=255)),
                ("requested_qty", models.PositiveIntegerField()),
                ("units_per_box", models.PositiveIntegerField(default=1)),
                ("requested_box_count", models.PositiveIntegerField(default=0)),
                ("general_available_qty_snapshot", models.PositiveIntegerField(default=0)),
                ("fbs_available_qty_snapshot", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("request", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="fbs.fbsclientmovementrequest")),
                ("sku", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="fbs_client_movement_request_lines", to="sku.sku")),
            ],
            options={
                "db_table": "fbs_client_movement_request_line",
                "ordering": ["request_id", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="fbsclientmovementrequest",
            index=models.Index(fields=["agency", "status", "created_at"], name="fbs_client__agency__9702ad_idx"),
        ),
        migrations.AddIndex(
            model_name="fbsclientmovementrequest",
            index=models.Index(fields=["status", "created_at"], name="fbs_client__status_7d1aff_idx"),
        ),
        migrations.AddConstraint(
            model_name="fbsclientmovementrequestline",
            constraint=models.UniqueConstraint(fields=("request", "barcode"), name="uniq_fbs_client_movement_request_barcode"),
        ),
        migrations.AddConstraint(
            model_name="fbsclientmovementrequestline",
            constraint=models.CheckConstraint(condition=models.Q(("requested_qty__gt", 0)), name="fbs_client_movement_requested_qty_gt_zero"),
        ),
        migrations.AddConstraint(
            model_name="fbsclientmovementrequestline",
            constraint=models.CheckConstraint(condition=models.Q(("units_per_box__gt", 0)), name="fbs_client_movement_units_per_box_gt_zero"),
        ),
        migrations.AddIndex(
            model_name="fbsclientmovementrequestline",
            index=models.Index(fields=["request", "barcode"], name="fbs_client__request_d1ef4b_idx"),
        ),
        migrations.AddIndex(
            model_name="fbsclientmovementrequestline",
            index=models.Index(fields=["sku", "created_at"], name="fbs_client__sku_id_4c4ffc_idx"),
        ),
    ]
