# Generated by Django 6.0 on 2026-08-10 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbs', '0022_staged_item_replenishment'),
        ('sklad', '0010_warehousecontainer_dimensions_weight'),
        ('sku', '0010_sku_weight_gross_kg_sku_weight_net_kg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FbsReplenishmentPreparedBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_no', models.PositiveSmallIntegerField()),
                ('box_code', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('printed', 'Напечатан'), ('filling', 'Заполняется'), ('closed', 'Закрыт'), ('placed', 'Размещен'), ('unused', 'Не использован')], default='printed', max_length=16)),
                ('scanned_qty', models.PositiveIntegerField(default=0)),
                ('placed_qty', models.PositiveIntegerField(default=0)),
                ('printed_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('placed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fbs_replenishment_prepared_boxes', to='sku.agency')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_fbs_replenishment_boxes', to=settings.AUTH_USER_MODEL)),
                ('fbs_box', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_prepared_box', to='fbs.fbsbox')),
                ('physical_container', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fbs_replenishment_prepared_box', to='sklad.warehousecontainer')),
                ('placed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placed_fbs_replenishment_boxes', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_boxes', to='fbs.fbsreplenishmentplan')),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_fbs_replenishment_boxes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fbs_replenishment_prepared_box',
                'ordering': ['plan_id', 'sequence_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FbsReplenishmentPreparedBoxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_scanned', models.PositiveIntegerField(default=0)),
                ('qty_placed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_box_items', to='fbs.fbsreplenishmentallocation')),
                ('prepared_box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='fbs.fbsreplenishmentpreparedbox')),
                ('target_balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prepared_box_items', to='fbs.fbsstockbalance')),
                ('warehouse_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fbs_prepared_box_item', to='sklad.warehouseevent')),
            ],
            options={
                'db_table': 'fbs_replenishment_prepared_box_item',
                'ordering': ['prepared_box_id', 'allocation_id', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='fbsreplenishmentpreparedbox',
            index=models.Index(fields=['plan', 'status'], name='fbs_repleni_plan_id_a293cb_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsreplenishmentpreparedbox',
            index=models.Index(fields=['agency', 'status'], name='fbs_repleni_agency__94653e_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsreplenishmentpreparedbox',
            index=models.Index(fields=['box_code'], name='fbs_repleni_box_cod_9688e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='fbsreplenishmentpreparedbox',
            constraint=models.UniqueConstraint(fields=('plan', 'sequence_no'), name='uniq_fbs_prepared_box_sequence'),
        ),
        migrations.AddConstraint(
            model_name='fbsreplenishmentpreparedbox',
            constraint=models.UniqueConstraint(fields=('agency', 'box_code'), name='uniq_fbs_prepared_box_code_per_agency'),
        ),
        migrations.AddConstraint(
            model_name='fbsreplenishmentpreparedbox',
            constraint=models.CheckConstraint(condition=models.Q(('sequence_no__gt', 0)), name='fbs_prepared_box_sequence_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='fbsreplenishmentpreparedbox',
            constraint=models.CheckConstraint(condition=models.Q(('scanned_qty__gte', models.F('placed_qty'))), name='fbs_prepared_box_scanned_covers_placed'),
        ),
        migrations.AddIndex(
            model_name='fbsreplenishmentpreparedboxitem',
            index=models.Index(fields=['allocation', 'prepared_box'], name='fbs_repleni_allocat_eb3374_idx'),
        ),
        migrations.AddIndex(
            model_name='fbsreplenishmentpreparedboxitem',
            index=models.Index(fields=['prepared_box', 'qty_placed'], name='fbs_repleni_prepare_ce85f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='fbsreplenishmentpreparedboxitem',
            constraint=models.UniqueConstraint(fields=('prepared_box', 'allocation'), name='uniq_fbs_prepared_box_allocation'),
        ),
        migrations.AddConstraint(
            model_name='fbsreplenishmentpreparedboxitem',
            constraint=models.CheckConstraint(condition=models.Q(('qty_scanned__gt', 0)), name='fbs_prepared_box_item_scanned_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='fbsreplenishmentpreparedboxitem',
            constraint=models.CheckConstraint(condition=models.Q(('qty_scanned__gte', models.F('qty_placed'))), name='fbs_prepared_item_scanned_covers_placed'),
        ),
    ]
