# Generated by Django 6.0 on 2026-08-10 17:46

import django.db.models.deletion
from django.db import migrations, models


def enable_status_pull_for_active_wb_profiles(apps, schema_editor):
    profile_model = apps.get_model("fbs", "FbsIntegrationProfile")
    profile_model.objects.using(schema_editor.connection.alias).filter(
        marketplace="wb",
        is_active=True,
        order_pull_enabled=True,
    ).update(status_pull_enabled=True)


class Migration(migrations.Migration):

    dependencies = [
        ("fbs", "0023_fbsreplenishmentpreparedbox_and_more"),
        ("sku", "0010_sku_weight_gross_kg_sku_weight_net_kg"),
    ]

    operations = [
        migrations.CreateModel(
            name="FbsStockExportState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.CharField(blank=True, max_length=64)),
                ("external_item_id", models.CharField(max_length=128)),
                ("external_product_id", models.CharField(blank=True, max_length=128)),
                ("desired_qty", models.PositiveIntegerField(default=0)),
                ("last_sent_qty", models.PositiveIntegerField(blank=True, null=True)),
                ("generation", models.PositiveBigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает выгрузки"),
                            ("sending", "Отправляется"),
                            ("synced", "Выгружено"),
                            ("retry", "Ожидает повтора"),
                            ("blocked", "Ошибка данных"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_http_status", models.PositiveIntegerField(blank=True, null=True)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_export_states",
                        to="fbs.fbsintegrationprofile",
                    ),
                ),
                (
                    "sku_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fbs_stock_export_states",
                        to="sku.sku",
                    ),
                ),
            ],
            options={
                "db_table": "fbs_stock_export_state",
                "ordering": ["profile_id", "external_item_id", "id"],
                "indexes": [
                    models.Index(
                        fields=["profile", "status", "next_attempt_at"],
                        name="fbs_stock_e_profile_0fa89d_idx",
                    ),
                    models.Index(
                        fields=["profile", "sku_ref"],
                        name="fbs_stock_e_profile_455457_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "external_item_id"),
                        name="uniq_fbs_stock_export_item_per_profile",
                    )
                ],
            },
        ),
        migrations.RunPython(
            enable_status_pull_for_active_wb_profiles,
            migrations.RunPython.noop,
        ),
    ]
