# Generated by Django 6.0 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fbs", "0024_fbsstockexportstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="fbsclientmovementrequest",
            name="requested_mixed_box_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="fbsclientmovementrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    requested_mixed_box_count__lte=models.F("requested_box_count")
                ),
                name="fbs_mov_mix_lte_boxes",
            ),
        ),
        migrations.AddConstraint(
            model_name="fbsclientmovementrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(mode="item")
                | models.Q(requested_mixed_box_count=0),
                name="fbs_mov_box_mode_no_mix",
            ),
        ),
    ]
