# Generated by Django 6.0 on 2026-08-12

import django.db.models.deletion
import fbs.file_storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fbs", "0025_fbsclientmovementrequest_requested_mixed_box_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FbsReturn",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_return_id", models.CharField(blank=True, max_length=128)),
                ("expected_qty", models.PositiveIntegerField()),
                ("status", models.CharField(choices=[("expected", "Ожидается"), ("receiving", "Принимается"), ("inspection", "На осмотре"), ("completed", "Завершен")], default="expected", max_length=16)),
                ("reason", models.TextField(blank=True)),
                ("order_scan_value", models.CharField(blank=True, max_length=512)),
                ("order_scan_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="completed_fbs_returns", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_fbs_returns", to=settings.AUTH_USER_MODEL)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="returns", to="fbs.fbsorder")),
                ("received_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="received_fbs_returns", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "fbs_return", "ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="FbsReturnUnit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sequence", models.PositiveIntegerField()),
                ("barcode", models.CharField(max_length=64)),
                ("marking_code", models.CharField(blank=True, max_length=128)),
                ("lot_code", models.CharField(blank=True, max_length=128)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("scan_value", models.CharField(max_length=512)),
                ("condition", models.CharField(choices=[("pending", "Не осмотрен"), ("good", "Годен"), ("damaged", "Поврежден"), ("quarantine", "Карантин")], default="pending", max_length=16)),
                ("condition_reason", models.TextField(blank=True)),
                ("scanned_at", models.DateTimeField(auto_now_add=True)),
                ("inspected_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("inspected_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inspected_fbs_return_units", to=settings.AUTH_USER_MODEL)),
                ("order_item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="return_units", to="fbs.fbsorderitem")),
                ("released_balance", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="released_return_units", to="fbs.fbsstockbalance")),
                ("return_record", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="units", to="fbs.fbsreturn")),
                ("scanned_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="scanned_fbs_return_units", to=settings.AUTH_USER_MODEL)),
                ("source_allocation", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="return_units", to="fbs.fbsorderstockallocation")),
                ("target_box", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="return_units", to="fbs.fbsbox")),
            ],
            options={"db_table": "fbs_return_unit", "ordering": ["return_record_id", "scanned_at", "id"]},
        ),
        migrations.CreateModel(
            name="FbsReturnPhoto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("product", "Товар"), ("package", "Упаковка"), ("other", "Другое")], default="product", max_length=16)),
                ("file", models.FileField(storage=fbs.file_storage.FbsReturnFileSystemStorage(), upload_to="photos/%Y/%m/%d/")),
                ("content_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("uploaded_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="uploaded_fbs_return_photos", to=settings.AUTH_USER_MODEL)),
                ("unit", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="photos", to="fbs.fbsreturnunit")),
            ],
            options={"db_table": "fbs_return_photo", "ordering": ["created_at", "id"]},
        ),
        migrations.AddIndex(model_name="fbsreturn", index=models.Index(fields=["status", "created_at"], name="fbs_return_status_4dba08_idx")),
        migrations.AddIndex(model_name="fbsreturn", index=models.Index(fields=["order", "status"], name="fbs_return_order_i_3cafc2_idx")),
        migrations.AddConstraint(model_name="fbsreturn", constraint=models.CheckConstraint(condition=models.Q(expected_qty__gt=0), name="fbs_return_expected_qty_gt_zero")),
        migrations.AddConstraint(model_name="fbsreturn", constraint=models.UniqueConstraint(condition=~models.Q(external_return_id=""), fields=("order", "external_return_id"), name="uniq_fbs_external_return_per_order")),
        migrations.AddConstraint(model_name="fbsreturn", constraint=models.UniqueConstraint(condition=models.Q(status__in=["expected", "receiving", "inspection"]), fields=("order",), name="uniq_active_fbs_return_per_order")),
        migrations.AddIndex(model_name="fbsreturnunit", index=models.Index(fields=["return_record", "condition"], name="fbs_return__return__96a81f_idx")),
        migrations.AddIndex(model_name="fbsreturnunit", index=models.Index(fields=["marking_code"], name="fbs_return__marking_9301e8_idx")),
        migrations.AddIndex(model_name="fbsreturnunit", index=models.Index(fields=["barcode"], name="fbs_return__barcode_24deb5_idx")),
        migrations.AddConstraint(model_name="fbsreturnunit", constraint=models.UniqueConstraint(fields=("source_allocation", "sequence"), name="uniq_fbs_returned_allocation_unit")),
        migrations.AddConstraint(model_name="fbsreturnunit", constraint=models.CheckConstraint(condition=models.Q(sequence__gt=0), name="fbs_return_unit_sequence_gt_zero")),
        migrations.AddConstraint(model_name="fbsreturnunit", constraint=models.CheckConstraint(condition=~models.Q(condition="good") | models.Q(target_box__isnull=False), name="fbs_good_return_unit_requires_box")),
        migrations.AddIndex(model_name="fbsreturnphoto", index=models.Index(fields=["unit", "created_at"], name="fbs_return__unit_id_e1f028_idx")),
        migrations.AddIndex(model_name="fbsreturnphoto", index=models.Index(fields=["content_hash"], name="fbs_return__content_f9a8b4_idx")),
    ]
