# Generated by Django 6.0 on 2026-08-12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fbs", "0025_fbsclientmovementrequest_requested_mixed_box_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FbsPickVerificationProgress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("qty_verified", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("allocation", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="verification_progress", to="fbs.fbsorderstockallocation")),
                ("verified_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="verified_fbs_pick_allocations", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "fbs_pick_verification_progress",
                "ordering": ["allocation_id"],
            },
        ),
        migrations.CreateModel(
            name="FbsPickScanEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("stage", models.CharField(choices=[("workstation", "Рабочее место"), ("cart", "Тележка"), ("cell", "Ячейка"), ("box", "Короб FBS"), ("pick_item", "Отбор товара"), ("verify_item", "Проверка товара"), ("order_label", "Этикетка заказа")], max_length=24)),
                ("result", models.CharField(choices=[("success", "Успешно"), ("error", "Ошибка")], max_length=16)),
                ("scan_value", models.CharField(blank=True, max_length=512)),
                ("expected_value", models.CharField(blank=True, max_length=512)),
                ("quantity_after", models.PositiveIntegerField(blank=True, null=True)),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("allocation", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="scan_events", to="fbs.fbsorderstockallocation")),
                ("batch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="scan_events", to="fbs.fbspickbatch")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="fbs_pick_scan_events", to=settings.AUTH_USER_MODEL)),
                ("task", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="scan_events", to="fbs.fbspicktask")),
            ],
            options={
                "db_table": "fbs_pick_scan_event",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="fbspickverificationprogress",
            index=models.Index(fields=["completed_at", "allocation"], name="fbs_verify_completed_idx"),
        ),
        migrations.AddIndex(
            model_name="fbspickscanevent",
            index=models.Index(fields=["batch", "created_at"], name="fbs_scan_batch_created_idx"),
        ),
        migrations.AddIndex(
            model_name="fbspickscanevent",
            index=models.Index(fields=["allocation", "stage", "result"], name="fbs_scan_alloc_stage_idx"),
        ),
    ]
