# Generated by Django 6.0 on 2026-08-12 20:51

import django.db.models.deletion
import fbs.file_storage
from django.conf import settings
from django.db import migrations, models


def preserve_existing_handover_state(apps, schema_editor):
    handover_batch = apps.get_model('fbs', 'FbsHandoverBatch')
    handover_batch.objects.exclude(external_supply_id='').update(
        marketplace_state='open',
    )


def reverse_existing_handover_state(apps, schema_editor):
    handover_batch = apps.get_model('fbs', 'FbsHandoverBatch')
    handover_batch.objects.exclude(external_supply_id='').update(
        marketplace_state='draft',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('fbs', '0027_fbs_pick_scanning_and_verification'),
        ('sku', '0010_sku_weight_gross_kg_sku_weight_net_kg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FbsHandoverOrderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Добавляется в поставку'), ('confirmed', 'Добавлен в поставку'), ('error', 'Ошибка добавления')], default='pending', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fbs_handover_order_assignment',
                'ordering': ['batch_id', 'id'],
            },
        ),
        migrations.AddField(
            model_name='fbshandoverbatch',
            name='compatibility_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='fbshandoverbatch',
            name='external_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='fbshandoverbatch',
            name='marketplace_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='fbshandoverbatch',
            name='marketplace_state',
            field=models.CharField(choices=[('draft', 'Черновик Fullbox'), ('creating', 'Создается на маркетплейсе'), ('open', 'Открыта на маркетплейсе'), ('delivery_pending', 'Передается в доставку'), ('complete', 'Передана в доставку'), ('error', 'Ошибка маркетплейса')], default='draft', max_length=24),
        ),
        migrations.AddField(
            model_name='fbshandoverbatch',
            name='supply_label_file',
            field=models.FileField(blank=True, storage=fbs.file_storage.FbsLabelFileSystemStorage(), upload_to='handover-labels/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='fbshandoverbatch',
            name='supply_label_format',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='fbshandoverbatch',
            name='supply_label_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fbshandoverbatch',
            name='supply_qr_code',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.RunPython(
            preserve_existing_handover_state,
            reverse_existing_handover_state,
        ),
        migrations.AddField(
            model_name='fbshandoverbox',
            name='label_file',
            field=models.FileField(blank=True, storage=fbs.file_storage.FbsLabelFileSystemStorage(), upload_to='handover-box-labels/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='fbshandoverbox',
            name='label_format',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='fbshandoverbox',
            name='label_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fbshandoverbox',
            name='label_ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fbsmarketplacecommand',
            name='handover_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_commands', to='fbs.fbshandoverbatch'),
        ),
        migrations.AddField(
            model_name='fbsmarketplacecommand',
            name='handover_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_commands', to='fbs.fbshandoverbox'),
        ),
        migrations.AddField(
            model_name='fbspickbatch',
            name='picking_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fbspickbatch',
            name='verification_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controlled_fbs_pick_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fbspickbatch',
            name='verification_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fbspickscanevent',
            name='stage',
            field=models.CharField(choices=[('workstation', 'Рабочее место'), ('cart', 'Тележка'), ('cell', 'Ячейка'), ('box', 'Короб FBS'), ('pick_item', 'Отбор товара'), ('verify_item', 'Проверка товара'), ('verify_marking', 'Проверка КИЗ'), ('verify_expiry', 'Срок годности'), ('order_label', 'Этикетка заказа'), ('wave_handover', 'Сдача волны на проверку')], max_length=24),
        ),
        migrations.AddIndex(
            model_name='fbshandoverbatch',
            index=models.Index(fields=['profile', 'marketplace_state'], name='fbs_handove_profile_04e432_idx'),
        ),
        migrations.AddIndex(
            model_name='fbspickbatch',
            index=models.Index(fields=['verification_assigned_to', 'status'], name='fbs_pick_ba_verific_a1d2f4_idx'),
        ),
        migrations.AddField(
            model_name='fbshandoverorderassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_fbs_handover_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fbshandoverorderassignment',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_assignments', to='fbs.fbshandoverbatch'),
        ),
        migrations.AddField(
            model_name='fbshandoverorderassignment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='handover_assignment', to='fbs.fbsorder'),
        ),
        migrations.AddIndex(
            model_name='fbshandoverorderassignment',
            index=models.Index(fields=['batch', 'status'], name='fbs_handove_batch_i_320f95_idx'),
        ),
    ]
