# Generated by Django 6.0 on 2026-08-19 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


FREE_TOTE_ZONE_BARCODE = "FBS-TOTE-ZONE-FREE"
READY_TOTE_ZONE_BARCODE = "FBS-TOTE-ZONE-READY"


def seed_tote_zones_and_bindings(apps, schema_editor):
    ToteZone = apps.get_model("fbs", "FbsToteZone")
    ToteBinding = apps.get_model("fbs", "FbsToteBinding")
    PickingCart = apps.get_model("fbs", "FbsPickingCart")
    PickBatch = apps.get_model("fbs", "FbsPickBatch")

    free_zone, _ = ToteZone.objects.get_or_create(
        barcode=FREE_TOTE_ZONE_BARCODE,
        defaults={
            "name": "Зона свободной тары",
            "kind": "free",
            "is_active": True,
        },
    )
    ToteZone.objects.get_or_create(
        barcode=READY_TOTE_ZONE_BARCODE,
        defaults={
            "name": "Зона готового товара",
            "kind": "ready",
            "is_active": True,
        },
    )

    active_batches = {
        batch.cart_id: batch
        for batch in PickBatch.objects.filter(
            cart_id__isnull=False,
            cart_released_at__isnull=True,
            status__in=("in_progress", "verification"),
        ).order_by("cart_id", "-updated_at", "-id")
    }
    for tote in PickingCart.objects.all().iterator():
        batch = active_batches.get(tote.id)
        values = {
            "state": "free",
            "zone_id": free_zone.id,
            "workstation_id": None,
            "employee_id": None,
            "pick_batch_id": None,
        }
        if batch is not None and batch.status == "verification" and batch.workstation_id:
            values.update(
                state="waiting_control",
                zone_id=None,
                workstation_id=batch.workstation_id,
                pick_batch_id=batch.id,
            )
        elif batch is not None and batch.assigned_to_id:
            values.update(
                state="picking",
                zone_id=None,
                employee_id=batch.assigned_to_id,
                pick_batch_id=batch.id,
            )
        ToteBinding.objects.update_or_create(tote_id=tote.id, defaults=values)


def unseed_tote_bindings(apps, schema_editor):
    ToteBinding = apps.get_model("fbs", "FbsToteBinding")
    ToteZone = apps.get_model("fbs", "FbsToteZone")
    ToteBinding.objects.all().delete()
    ToteZone.objects.filter(
        barcode__in=(FREE_TOTE_ZONE_BARCODE, READY_TOTE_ZONE_BARCODE)
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('fbs', '0039_handover_archive'),
        ('sku', '0010_sku_weight_gross_kg_sku_weight_net_kg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fbspickingcart',
            options={'ordering': ['name', 'id'], 'verbose_name': 'Тара FBS', 'verbose_name_plural': 'Тара FBS'},
        ),
        migrations.AlterField(
            model_name='fbspickbatch',
            name='status',
            field=models.CharField(choices=[('queued', 'В очереди'), ('in_progress', 'В работе'), ('verification', 'Проверка'), ('done', 'Завершена'), ('canceled', 'Отменена')], default='queued', max_length=24),
        ),
        migrations.AlterField(
            model_name='fbspicktask',
            name='status',
            field=models.CharField(choices=[('queued', 'В очереди'), ('in_progress', 'В работе'), ('picked', 'Отобран'), ('exception', 'Исключение'), ('canceled', 'Отменен')], default='queued', max_length=24),
        ),
        migrations.CreateModel(
            name='FbsControllerCheckTote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Наполняется'), ('waiting_kiz', 'Ожидает КИЗ'), ('ready', 'Готова к проверке состава'), ('composition', 'Проверка состава'), ('closed', 'Закрыта'), ('problem', 'Проблема')], default='open', max_length=24)),
                ('item_qty', models.PositiveIntegerField(default=0)),
                ('labeled_qty', models.PositiveIntegerField(default=0)),
                ('composition_qty', models.PositiveIntegerField(default=0)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fbs_controller_check_totes', to='sku.agency')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_fbs_check_totes', to=settings.AUTH_USER_MODEL)),
                ('handover_batch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controller_check_tote', to='fbs.fbshandoverbatch')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_fbs_check_totes', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controller_check_totes', to='fbs.fbsintegrationprofile')),
                ('tote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controller_check_uses', to='fbs.fbspickingcart')),
            ],
            options={
                'db_table': 'fbs_controller_check_tote',
                'ordering': ['opened_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FbsControllerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('closed', 'Закрыта')], default='active', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fbs_controller_tote_sessions', to=settings.AUTH_USER_MODEL)),
                ('unknown_tote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unknown_controller_sessions', to='fbs.fbspickingcart')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controller_tote_sessions', to='fbs.fbsworkstation')),
            ],
            options={
                'db_table': 'fbs_controller_session',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FbsControllerPickTote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('processing', 'Обрабатывается'), ('awaiting_empty', 'Подтвердите пустоту'), ('closed', 'Освобождена'), ('problem', 'Проблема')], default='processing', max_length=24)),
                ('planned_qty', models.PositiveIntegerField(default=0)),
                ('processed_qty', models.PositiveIntegerField(default=0)),
                ('unknown_qty', models.PositiveIntegerField(default=0)),
                ('attached_at', models.DateTimeField(auto_now_add=True)),
                ('empty_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_tote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pick_totes', to='fbs.fbscontrollerchecktote')),
                ('pick_batch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='controller_pick_tote', to='fbs.fbspickbatch')),
                ('tote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controller_pick_uses', to='fbs.fbspickingcart')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pick_totes', to='fbs.fbscontrollersession')),
            ],
            options={
                'db_table': 'fbs_controller_pick_tote',
                'ordering': ['attached_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='fbscontrollerchecktote',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='check_totes', to='fbs.fbscontrollersession'),
        ),
        migrations.CreateModel(
            name='FbsControllerToteOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('labeled', 'В таре проверки'), ('composition', 'Состав подтвержден'), ('packed', 'В транспортном коробе'), ('removed', 'Исключен')], default='labeled', max_length=24)),
                ('units', models.PositiveIntegerField(default=1)),
                ('label_confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('composition_checked_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_tote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='fbs.fbscontrollerchecktote')),
                ('composition_checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checked_fbs_tote_order_compositions', to=settings.AUTH_USER_MODEL)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controller_tote_orders', to='fbs.fbsorderlabel')),
                ('label_confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_fbs_tote_order_labels', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controller_tote_orders', to='fbs.fbsorder')),
                ('pick_tote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='fbs.fbscontrollerpicktote')),
                ('transport_box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controller_tote_orders', to='fbs.fbshandoverbox')),
            ],
            options={
                'db_table': 'fbs_controller_tote_order',
                'ordering': ['label_confirmed_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FbsToteMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('assign', 'Привязка'), ('take', 'Взята'), ('place', 'Оставлена'), ('handover', 'Передана'), ('check', 'Проверка'), ('release', 'Освобождена'), ('unknown', 'Неизвестный товар'), ('close', 'Закрытие')], max_length=16)),
                ('source_kind', models.CharField(blank=True, max_length=16)),
                ('source_code', models.CharField(blank=True, max_length=128)),
                ('target_kind', models.CharField(blank=True, max_length=16)),
                ('target_code', models.CharField(blank=True, max_length=128)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('controller_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='fbs.fbscontrollersession')),
                ('handover_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tote_movements', to='fbs.fbshandoverbatch')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_fbs_tote_movements', to=settings.AUTH_USER_MODEL)),
                ('pick_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tote_movements', to='fbs.fbspickbatch')),
                ('tote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_events', to='fbs.fbspickingcart')),
            ],
            options={
                'db_table': 'fbs_tote_movement',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FbsToteZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=64, unique=True, verbose_name='QR зоны')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('kind', models.CharField(choices=[('free', 'Зона свободной тары'), ('controller', 'Зона контролера'), ('ready', 'Зона готового товара'), ('transit', 'Транзитная зона')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fbs_tote_zone',
                'ordering': ['kind', 'name', 'id'],
                'indexes': [models.Index(fields=['kind', 'is_active'], name='fbs_tote_zo_kind_56fe79_idx')],
            },
        ),
        migrations.CreateModel(
            name='FbsToteBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('unbound', 'Не привязана'), ('free', 'Свободна'), ('picking', 'У сборщика'), ('waiting_control', 'Ожидает контролера'), ('at_control', 'У контролера'), ('checking', 'Тара на проверку'), ('unknown', 'Неизвестный товар'), ('ready', 'Готовый товар'), ('transit', 'В перемещении')], default='unbound', max_length=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('controller_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tote_bindings', to='fbs.fbscontrollersession')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bound_fbs_totes', to=settings.AUTH_USER_MODEL)),
                ('pick_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tote_bindings', to='fbs.fbspickbatch')),
                ('tote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='binding', to='fbs.fbspickingcart')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_fbs_tote_bindings', to=settings.AUTH_USER_MODEL)),
                ('workstation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bound_totes', to='fbs.fbsworkstation')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bound_totes', to='fbs.fbstotezone')),
            ],
            options={
                'db_table': 'fbs_tote_binding',
            },
        ),
        migrations.AddField(
            model_name='fbscontrollersession',
            name='free_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controller_sessions', to='fbs.fbstotezone'),
        ),
        migrations.CreateModel(
            name='FbsUnknownToteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_value', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('waiting', 'Ожидает размещения'), ('placed', 'Размещен')], default='waiting', max_length=16)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('placed_at', models.DateTimeField(blank=True, null=True)),
                ('placed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='placed_fbs_unknown_tote_items', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_fbs_unknown_tote_items', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unknown_items', to='fbs.fbscontrollersession')),
                ('source_pick_tote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unknown_items', to='fbs.fbscontrollerpicktote')),
                ('unknown_tote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unknown_items', to='fbs.fbspickingcart')),
            ],
            options={
                'db_table': 'fbs_unknown_tote_item',
                'ordering': ['reported_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='fbscontrollerpicktote',
            index=models.Index(fields=['session', 'status'], name='fbs_control_session_e24aed_idx'),
        ),
        migrations.AddIndex(
            model_name='fbscontrollerpicktote',
            index=models.Index(fields=['check_tote', 'status'], name='fbs_control_check_t_796289_idx'),
        ),
        migrations.AddConstraint(
            model_name='fbscontrollerpicktote',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('processing', 'awaiting_empty'))), fields=('tote',), name='uniq_active_fbs_controller_pick_tote'),
        ),
        migrations.AddIndex(
            model_name='fbscontrollerchecktote',
            index=models.Index(fields=['session', 'status'], name='fbs_control_session_577548_idx'),
        ),
        migrations.AddIndex(
            model_name='fbscontrollerchecktote',
            index=models.Index(fields=['agency', 'status'], name='fbs_control_agency__efdea0_idx'),
        ),
        migrations.AddConstraint(
            model_name='fbscontrollerchecktote',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('open', 'waiting_kiz', 'ready', 'composition'))), fields=('tote',), name='uniq_active_fbs_controller_check_tote'),
        ),
        migrations.AddIndex(
            model_name='fbscontrollertoteorder',
            index=models.Index(fields=['check_tote', 'status'], name='fbs_control_check_t_c812fb_idx'),
        ),
        migrations.AddIndex(
            model_name='fbscontrollertoteorder',
            index=models.Index(fields=['pick_tote', 'status'], name='fbs_control_pick_to_0e1b63_idx'),
        ),
        migrations.AddConstraint(
            model_name='fbscontrollertoteorder',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('labeled', 'composition', 'packed'))), fields=('order',), name='uniq_active_fbs_controller_tote_order'),
        ),
        migrations.AddIndex(
            model_name='fbstotemovement',
            index=models.Index(fields=['tote', 'created_at'], name='fbs_tote_mo_tote_id_97f963_idx'),
        ),
        migrations.AddIndex(
            model_name='fbstotemovement',
            index=models.Index(fields=['action', 'created_at'], name='fbs_tote_mo_action_de1111_idx'),
        ),
        migrations.AddIndex(
            model_name='fbstotebinding',
            index=models.Index(fields=['state', 'updated_at'], name='fbs_tote_bi_state_6f5c1f_idx'),
        ),
        migrations.AddIndex(
            model_name='fbstotebinding',
            index=models.Index(fields=['zone', 'state'], name='fbs_tote_bi_zone_id_fb2a0c_idx'),
        ),
        migrations.AddIndex(
            model_name='fbstotebinding',
            index=models.Index(fields=['workstation', 'state'], name='fbs_tote_bi_worksta_93f019_idx'),
        ),
        migrations.AddIndex(
            model_name='fbstotebinding',
            index=models.Index(fields=['employee', 'state'], name='fbs_tote_bi_employe_ba81a5_idx'),
        ),
        migrations.AddConstraint(
            model_name='fbscontrollersession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('workstation',), name='uniq_active_fbs_tote_session_workstation'),
        ),
        migrations.AddConstraint(
            model_name='fbscontrollersession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('controller',), name='uniq_active_fbs_tote_session_controller'),
        ),
        migrations.AddIndex(
            model_name='fbsunknowntoteitem',
            index=models.Index(fields=['status', 'reported_at'], name='fbs_unknown_status_e840aa_idx'),
        ),
        migrations.RunPython(
            seed_tote_zones_and_bindings,
            unseed_tote_bindings,
        ),
    ]
