# Generated by Django 6.0 on 2026-09-08 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbs', '0054_unify_warehouse_fbs_cells'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fbsinventoryline', name='protected_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fbsinventorysession',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_fbs_inventories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fbsinventorysession',
            name='count_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fbsinventorysession',
            name='managed_workflow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fbsinventorysession',
            name='recount_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_fbs_inventory_recounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fbsinventorysession',
            name='recount_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fbspickexception',
            name='inventory_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pick_issues', to='fbs.fbsinventorysession'),
        ),
        migrations.CreateModel(
            name='FbsInventoryWorkEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_events', to='fbs.fbsinventorysession')),
            ],
            options={
                'db_table': 'fbs_inventory_work_event',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
