# Generated by Django 6.0 on 2026-09-12 15:54

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbs', '0058_fbs_wave_queue_priority'),
        ('sku', '0011_skubarcode_agency_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FbsExternalIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=128)),
                ('recipient', models.CharField(max_length=255)),
                ('purpose', models.CharField(choices=[('owner', 'Возврат владельцу'), ('external', 'Сторонняя отгрузка')], max_length=20)),
                ('basis', models.TextField()),
                ('status', models.CharField(choices=[('reserved', 'К отбору'), ('picking', 'В отборе'), ('completed', 'Выдано'), ('canceled', 'Отменено')], default='reserved', max_length=16)),
                ('request_key', models.UUIDField(unique=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('historical', models.BooleanField(default=False)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FbsExternalIssueEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_key', models.UUIDField(unique=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=24)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FbsExternalIssueLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_snapshot', models.JSONField(default=dict)),
                ('requested_qty', models.PositiveIntegerField()),
                ('picked_qty', models.PositiveIntegerField(default=0)),
                ('returned_qty', models.PositiveIntegerField(default=0)),
                ('shipped_qty', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='fbsstockbalance',
            name='external_reserved_qty',
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
        migrations.AddConstraint(
            model_name='fbsstockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('available_qty'), '+', models.F('reserved_qty')), '+', models.F('external_reserved_qty')))), name='fbs_stock_covers_external_hold'),
        ),
        migrations.AddField(
            model_name='fbsexternalissue',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sku.agency'),
        ),
        migrations.AddField(
            model_name='fbsexternalissue',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fbs_external_issues_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fbsexternalissue',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fbs_external_issues_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fbsexternalissueevent',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='fbs.fbsexternalissue'),
        ),
        migrations.AddField(
            model_name='fbsexternalissueevent',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fbsexternalissueline',
            name='balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_issue_lines', to='fbs.fbsstockbalance'),
        ),
        migrations.AddField(
            model_name='fbsexternalissueline',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='fbs.fbsexternalissue'),
        ),
        migrations.AddConstraint(
            model_name='fbsexternalissue',
            constraint=models.UniqueConstraint(fields=('agency', 'reference'), name='fbs_external_issue_reference'),
        ),
        migrations.AddConstraint(
            model_name='fbsexternalissueline',
            constraint=models.UniqueConstraint(fields=('issue', 'balance'), name='fbs_external_line_balance'),
        ),
        migrations.AddConstraint(
            model_name='fbsexternalissueline',
            constraint=models.CheckConstraint(condition=models.Q(('requested_qty__gt', 0), ('requested_qty__gte', models.F('picked_qty')), ('picked_qty__gte', models.F('returned_qty')), ('shipped_qty__lte', django.db.models.expressions.CombinedExpression(models.F('picked_qty'), '-', models.F('returned_qty')))), name='fbs_external_line_quantities'),
        ),
    ]
