from django.urls import include, path

from .views import (
    ProcessingDetailView,
    ProcessingHomeView,
    ProcessingDirectionsView,
    ProcessingStockPickerView,
    ProcessingWorkView,
    ProcessingPlacementActView,
    ProcessingFlowView,
    ProcessingCardView,
    ProcessingTechnicalCardView,
    ProcessingLabelPrintView,
    processing_flow_box_action,
    processing_flow_cancel_box,
    processing_flow_close_box,
    processing_flow_container_code,
    processing_flow_label_render,
    processing_flow_marking_scan,
    processing_flow_pallet_shipping_release,
    processing_flow_session,
    processing_flow_shared,
    processing_assign_card,
    processing_assign_packaging,
    enqueue_processing_print_job,
    download_processing_marking_template,
    processing_marking_availability,
    processing_marking_import,
    processing_print_jobs_next,
    processing_print_jobs_complete,
    processing_print_jobs_renew,
    processing_print_jobs_desktop_complete,
    processing_print_jobs_status,
    processing_print_agent_verify,
    processing_card_print_progress,
    processing_print_jobs_pause,
    processing_print_jobs_resume,
    processing_print_jobs_clear,
    processing_print_jobs_reset,
    processing_print_jobs_recover,
    download_processing_print_agent_cmd,
    download_processing_print_agent_install_cmd,
    download_processing_fullbox_agent_setup,
    download_processing_fullbox_agent_enroll_script,
    processing_print_agent_guide,
    download_processing_printer_sync_package,
    download_processing_print_agent_script,
    delete_processing_draft,
    processing_attachment_download,
    processing_excel_preview,
)
from .reporting import processing_report_xlsx

app_name = "processing_app"

urlpatterns = [
    path("", ProcessingHomeView.as_view(), name="processing-home"),
    path("directions/", ProcessingDirectionsView.as_view(), name="processing-directions"),
    path("stock/", ProcessingStockPickerView.as_view(), name="processing-stock-picker"),
    path("excel-preview/", processing_excel_preview, name="processing-excel-preview"),
    path("draft/<str:order_id>/delete/", delete_processing_draft, name="processing-draft-delete"),
    path("<str:order_id>/attachments/<int:attachment_id>/", processing_attachment_download, name="processing-attachment-download"),
    path("print-jobs/", enqueue_processing_print_job, name="processing-print-job"),
    path(
        "print-jobs/desktop-record/",
        enqueue_processing_print_job,
        name="processing-print-job-desktop-record",
    ),
    path("marking-template.xlsx", download_processing_marking_template, name="processing-marking-template"),
    path("marking-availability/", processing_marking_availability, name="processing-marking-availability"),
    path("marking-import/", processing_marking_import, name="processing-marking-import"),
    path("print-jobs/status/", processing_print_jobs_status, name="processing-print-jobs-status"),
    path("print-agent/verify/", processing_print_agent_verify, name="processing-print-agent-verify"),
    path("print-jobs/next/", processing_print_jobs_next, name="processing-print-jobs-next"),
    path("print-jobs/complete/", processing_print_jobs_complete, name="processing-print-jobs-complete"),
    path("print-jobs/renew/", processing_print_jobs_renew, name="processing-print-jobs-renew"),
    path("print-jobs/desktop-complete/", processing_print_jobs_desktop_complete, name="processing-print-jobs-desktop-complete"),
    path("print-jobs/pause/", processing_print_jobs_pause, name="processing-print-jobs-pause"),
    path("print-jobs/resume/", processing_print_jobs_resume, name="processing-print-jobs-resume"),
    path("print-jobs/clear/", processing_print_jobs_clear, name="processing-print-jobs-clear"),
    path("print-jobs/reset/", processing_print_jobs_reset, name="processing-print-jobs-reset"),
    path("print-jobs/recover/", processing_print_jobs_recover, name="processing-print-jobs-recover"),
    path("print-agent/download/", download_processing_print_agent_cmd, name="processing-print-agent-download"),
    path("print-agent/install/", download_processing_print_agent_install_cmd, name="processing-print-agent-install"),
    path("print-agent/setup/", download_processing_fullbox_agent_setup, name="processing-print-agent-setup"),
    path("print-agent/register/", download_processing_fullbox_agent_enroll_script, name="processing-print-agent-register"),
    path("print-agent/guide/", processing_print_agent_guide, name="processing-print-agent-guide"),
    path("print-agent/sync-printers/", download_processing_printer_sync_package, name="processing-printers-sync"),
    path("print-agent/script/", download_processing_print_agent_script, name="processing-print-agent-script"),
    path("<str:order_id>/flow/box-action/", processing_flow_box_action, name="processing-flow-box-action"),
    path("<str:order_id>/flow/cancel-box/", processing_flow_cancel_box, name="processing-flow-cancel-box"),
    path("<str:order_id>/flow/close-box/", processing_flow_close_box, name="processing-flow-close-box"),
    path("<str:order_id>/flow/container-code/", processing_flow_container_code, name="processing-flow-container-code"),
    path("<str:order_id>/flow/label-render/", processing_flow_label_render, name="processing-flow-label-render"),
    path("<str:order_id>/flow/scan/", processing_flow_marking_scan, name="processing-flow-scan"),
    path(
        "<str:order_id>/flow/pallet-shipping-release/",
        processing_flow_pallet_shipping_release,
        name="processing-flow-pallet-shipping-release",
    ),
    path("<str:order_id>/flow/session/", processing_flow_session, name="processing-flow-session"),
    path("<str:order_id>/flow/shared/", processing_flow_shared, name="processing-flow-shared"),
    path("<str:order_id>/cz-flow/", include("processing_cz.urls")),
    path("<str:order_id>/flow/", ProcessingFlowView.as_view(), name="processing-flow"),
    path("<str:order_id>/assign-card/", processing_assign_card, name="processing-assign-card"),
    path("<str:order_id>/assign-packaging/", processing_assign_packaging, name="processing-assign-packaging"),
    path("<str:order_id>/placement/", ProcessingPlacementActView.as_view(), name="processing-placement"),
    path("<str:order_id>/work/", ProcessingWorkView.as_view(), name="processing-work"),
    path("<str:order_id>/card/<str:card_id>/print-progress/", processing_card_print_progress, name="processing-card-print-progress"),
    path("<str:order_id>/card/<str:card_id>/", ProcessingCardView.as_view(), name="processing-card"),
    path("<str:order_id>/card/<str:card_id>/technical/", ProcessingTechnicalCardView.as_view(), name="processing-card-technical"),
    path("<str:order_id>/card/<str:card_id>/labels/", ProcessingLabelPrintView.as_view(), name="processing-card-labels"),
    path("<str:order_id>/report.xlsx", processing_report_xlsx, name="processing-report-xlsx"),
    path("<str:order_id>/", ProcessingDetailView.as_view(), name="processing-detail"),
]
