from django.urls import path

from billing.client_api_views import client_billing_acts, client_confirm_act, client_dispute_act
from .portal_access import SECTION_FINANCE
from .portal_members import portal_section_required

from .views import (
    ClientListView,
    ClientCreateView,
    ClientUpdateView,
    export_client_logins,
    archive_toggle,
    dashboard,
    dashboard_new,
    dashboard_lk,
    fetch_by_inn,
    ClientSKUListView,
    ClientSKUCreateView,
    ClientSKUUpdateView,
    ClientSKUDuplicateView,
    ClientOrderFormView,
    ClientReceivingCreateView,
    ClientPackingCreateView,
    receiving_redirect,
    packing_redirect,
    shipping_redirect,
    marking_tools,
    marking_import,
)
from .telegram_views import telegram_chat_webhook
from .web_ui import staff_client_preview, staff_client_preview_return
from .fbs_lk import (
    api_fbs_marking_report_export,
    api_fbs_movement_detail,
    api_fbs_movement_import,
    api_fbs_movement_stock,
    api_fbs_movements,
    api_fbs_outbound,
    api_fbs_outbound_import,
    api_fbs_order_detail,
    api_fbs_orders,
    api_fbs_overview,
    api_fbs_ozon_warehouses,
    api_fbs_reports,
    api_fbs_stock,
    api_fbs_stock_detail,
    fbs_movement_template,
    fbs_outbound_template,
)
from .api_views import (
    api_billing,
    api_billing_storage,
    api_billing_tariffs,
    api_client_my_tariffs,
    api_client_requisites,
    api_requisites_change_request,
    api_tariff_version_current,
    api_tariff_version_detail,
    api_tariff_version_download,
    api_tariff_version_history,
    api_chat_attachment,
    api_chat_mention_candidates,
    api_chat_message_delete,
    api_chat_message_edit,
    api_chat_messages,
    api_chat_mark_all_read,
    api_chat_prefs,
    api_chat_reaction,
    api_chat_threads,
    api_dashboard,
    api_dashboard_live,
    api_dashboard_live_history,
    api_finance,
    api_finance_document_file,
    api_marking,
    api_marketplace_sync,
    api_marketplaces,
    api_me,
    api_nomenclature,
    api_nomenclature_commit,
    api_nomenclature_delete,
    api_nomenclature_export,
    api_nomenclature_upload,
    api_notifications,
    api_other_attachment,
    api_other_request_create,
    api_requests,
    api_receiving_act_excel,
    api_request_detail,
    api_request_detail_export,
    api_shipping_marking_export,
    api_shipping_return_act_doc,
    api_stock_journal,
    api_stock_journal_export,
)

urlpatterns = [
    path('api/v1/dashboard/', api_dashboard, name='client-api-dashboard'),
    path('api/v1/dashboard/live/', api_dashboard_live, name='client-api-dashboard-live'),
    path('api/v1/dashboard/live-history/', api_dashboard_live_history, name='client-api-dashboard-live-history'),
    path('api/v1/me/', api_me, name='client-api-me'),
    path('api/v1/stock-journal/', api_stock_journal, name='client-api-stock-journal'),
    path('api/v1/stock-journal/export/', api_stock_journal_export, name='client-api-stock-journal-export'),
    path('api/v1/other-requests/', api_other_request_create, name='client-api-other-request-create'),
    path('api/v1/other-requests/attachments/<int:attachment_id>/', api_other_attachment, name='client-api-other-attachment'),
    path('api/v1/requests/', api_requests, name='client-api-requests'),
    path('api/v1/requests/<str:order_type>/<str:order_id>/', api_request_detail, name='client-api-request-detail'),
    path('api/v1/requests/<str:order_type>/<str:order_id>/export/', api_request_detail_export, name='client-api-request-detail-export'),
    path('api/v1/requests/receiving/<str:order_id>/act.xlsx', api_receiving_act_excel, name='client-api-receiving-act-excel'),
    path('api/v1/requests/shipping/<str:order_id>/marking/export/', api_shipping_marking_export, name='client-api-shipping-marking-export'),
    path('api/v1/requests/shipping/<str:order_id>/return-act/docx/', api_shipping_return_act_doc, name='client-api-shipping-return-act-doc'),
    path('api/v1/nomenclature/', api_nomenclature, name='client-api-nomenclature'),
    path('api/v1/nomenclature/export/', api_nomenclature_export, name='client-api-nomenclature-export'),
    path('api/v1/nomenclature/upload/', api_nomenclature_upload, name='client-api-nomenclature-upload'),
    path('api/v1/nomenclature/commit/', api_nomenclature_commit, name='client-api-nomenclature-commit'),
    path('api/v1/nomenclature/<int:sku_id>/delete/', api_nomenclature_delete, name='client-api-nomenclature-delete'),
    path('api/v1/marketplaces/', api_marketplaces, name='client-api-marketplaces'),
    path('api/v1/marketplace-sync/', api_marketplace_sync, name='client-api-marketplace-sync'),
    path('api/v1/marking/', api_marking, name='client-api-marking'),
    path('api/v1/fbs/', api_fbs_overview, name='client-api-fbs-overview'),
    path('api/v1/fbs/ozon-warehouses/', api_fbs_ozon_warehouses, name='client-api-fbs-ozon-warehouses'),
    path('api/v1/fbs/orders/', api_fbs_orders, name='client-api-fbs-orders'),
    path('api/v1/fbs/orders/<int:order_id>/', api_fbs_order_detail, name='client-api-fbs-order-detail'),
    path('api/v1/fbs/stock/', api_fbs_stock, name='client-api-fbs-stock'),
    path('api/v1/fbs/stock/<str:barcode>/', api_fbs_stock_detail, name='client-api-fbs-stock-detail'),
    path('api/v1/fbs/outbound/', api_fbs_outbound, name='client-api-fbs-outbound'),
    path('api/v1/fbs/outbound/import/', api_fbs_outbound_import, name='client-api-fbs-outbound-import'),
    path('fbs/outbound-template.xlsx', fbs_outbound_template, name='client-fbs-outbound-template'),
    path('api/v1/fbs/reports/', api_fbs_reports, name='client-api-fbs-reports'),
    path('api/v1/fbs/reports/marking/export/', api_fbs_marking_report_export, name='client-api-fbs-marking-report-export'),
    path('api/v1/fbs/movements/', api_fbs_movements, name='client-api-fbs-movements'),
    path('api/v1/fbs/movement-stock/', api_fbs_movement_stock, name='client-api-fbs-movement-stock'),
    path('api/v1/fbs/movements/import/', api_fbs_movement_import, name='client-api-fbs-movement-import'),
    path('api/v1/fbs/movements/<int:request_id>/', api_fbs_movement_detail, name='client-api-fbs-movement-detail'),
    path('fbs/movement-template.xlsx', fbs_movement_template, name='client-fbs-movement-template'),
    path('api/v1/finance/', api_finance, name='client-api-finance'),
    path('api/v1/finance/documents/<int:document_id>/file/', api_finance_document_file, name='client-api-finance-document-file'),
    path('api/v1/billing/', api_billing, name='client-api-billing'),
    path('api/v1/billing/storage/', api_billing_storage, name='client-api-billing-storage'),
    path('api/v1/billing/tariffs/', api_billing_tariffs, name='client-api-billing-tariffs'),
    path('api/v1/billing/tariff-versions/current/', api_tariff_version_current, name='client-api-tariff-version-current'),
    path('api/v1/billing/tariff-versions/history/', api_tariff_version_history, name='client-api-tariff-version-history'),
    path('api/v1/billing/tariff-versions/<int:version_id>/', api_tariff_version_detail, name='client-api-tariff-version-detail'),
    path('api/v1/billing/tariff-versions/<int:version_id>/download/', api_tariff_version_download, name='client-api-tariff-version-download'),
    path('api/v1/billing/acts/', portal_section_required(SECTION_FINANCE)(client_billing_acts), name='client-api-billing-acts'),
    path('api/v1/billing/acts/<int:pk>/confirm/', portal_section_required(SECTION_FINANCE)(client_confirm_act), name='client-api-billing-act-confirm'),
    path('api/v1/billing/acts/<int:pk>/dispute/', portal_section_required(SECTION_FINANCE)(client_dispute_act), name='client-api-billing-act-dispute'),
    path('api/tariffs/', api_client_my_tariffs, name='client-api-my-tariffs'),
    path('api/requisites/', api_client_requisites, name='client-api-requisites'),
    path('api/requisites/change-request/', api_requisites_change_request, name='client-api-requisites-change-request'),
    path('api/v1/requisites/', api_client_requisites, name='client-api-v1-requisites'),
    path('api/v1/requisites/change-request/', api_requisites_change_request, name='client-api-v1-requisites-change-request'),
    path('api/v1/notifications/', api_notifications, name='client-api-notifications'),
    path('api/v1/chat/threads/', api_chat_threads, name='client-api-chat-threads'),
    path('api/v1/chat/messages/', api_chat_messages, name='client-api-chat-messages'),
    path('api/v1/chat/messages/<int:message_id>/reaction/', api_chat_reaction, name='client-api-chat-reaction'),
    path('api/v1/chat/messages/<int:message_id>/edit/', api_chat_message_edit, name='client-api-chat-message-edit'),
    path('api/v1/chat/messages/<int:message_id>/delete/', api_chat_message_delete, name='client-api-chat-message-delete'),
    path('api/v1/chat/mention-candidates/', api_chat_mention_candidates, name='client-api-chat-mention-candidates'),
    path('api/v1/chat/prefs/', api_chat_prefs, name='client-api-chat-prefs'),
    path('api/v1/chat/mark-all-read/', api_chat_mark_all_read, name='client-api-chat-mark-all-read'),
    path('api/v1/chat/attachments/<int:attachment_id>/', api_chat_attachment, name='client-api-chat-attachment'),
    path('api/v1/chat/telegram/webhook/', telegram_chat_webhook, name='client-api-chat-telegram-webhook'),
    path('', ClientListView.as_view(), name='client-list'),
    path('export-logins/', export_client_logins, name='client-export-logins'),
    path('dashboard/', dashboard, name='client-cabinet'),
    path('dashboard/new/', dashboard_new, name='client-cabinet-new'),
    path('dashboard/preview/<int:client_id>/', staff_client_preview, name='client-cabinet-preview'),
    path('dashboard/return-to-manager/', staff_client_preview_return, name='client-cabinet-preview-return'),
    path('dashboard/lk/', dashboard_lk, name='client-cabinet-lk'),
    path('new/', ClientCreateView.as_view(), name='client-create'),
    path('<int:pk>/edit/', ClientUpdateView.as_view(), name='client-edit'),
    path('<int:pk>/archive/', archive_toggle, name='client-archive'),
    path('<int:pk>/sku/', ClientSKUListView.as_view(), name='client-sku-list'),
    path('<int:pk>/sku/new/', ClientSKUCreateView.as_view(), name='client-sku-create'),
    path('<int:pk>/sku/<int:sku_id>/edit/', ClientSKUUpdateView.as_view(), name='client-sku-edit'),
    path('<int:pk>/sku/<int:sku_id>/duplicate/', ClientSKUDuplicateView.as_view(), name='client-sku-duplicate'),
    path('<int:pk>/orders/new/', ClientOrderFormView.as_view(), name='client-order-new'),
    path('<int:pk>/receiving/new/', receiving_redirect, name='client-receiving-new'),
    path('<int:pk>/packing/new/', packing_redirect, name='client-packing-new'),
    path('<int:pk>/shipping/new/', shipping_redirect, name='client-shipping-new'),
    path('marking/', marking_tools, name='client-marking-tools'),
    path('marking/import/', marking_import, name='client-marking-import'),
    path('fetch-by-inn/', fetch_by_inn, name='client-fetch-inn'),
]
