# Generated by Django 6.0 on 2026-07-18 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0009_super_car_role_and_user'),
        ('todo', '0008_taskpanelsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(verbose_name='Начало замещения')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Окончание замещения')),
                ('task_types', models.CharField(blank=True, help_text='receiving,processing,shipping,logistics', max_length=255, verbose_name='Типы задач (через запятую, пусто = все)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employee_coverages', to=settings.AUTH_USER_MODEL)),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages_as_principal', to='employees.employee', verbose_name='Основной сотрудник')),
                ('substitute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages_as_substitute', to='employees.employee', verbose_name='Замещающий')),
            ],
            options={
                'verbose_name': 'Замещение сотрудника',
                'verbose_name_plural': 'Замещения сотрудников',
                'ordering': ('-valid_from', '-id'),
                'indexes': [models.Index(fields=['principal', 'is_active', 'valid_from'], name='teammanager_princip_1f4db8_idx'), models.Index(fields=['substitute', 'is_active'], name='teammanager_substit_2df5e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskHandoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('claim', 'Взята в работу'), ('transfer', 'Передана'), ('return_queue', 'Возвращена в очередь'), ('assign_dept', 'Назначена подразделению')], db_index=True, max_length=32)),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Причина')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('task_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Состояние на момент передачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_handoffs_authored', to='employees.employee', verbose_name='Автор передачи')),
                ('from_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_handoffs_from', to='employees.employee', verbose_name='Предыдущий ответственный')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoffs', to='todo.task', verbose_name='Задача')),
                ('to_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_handoffs_to', to='employees.employee', verbose_name='Новый ответственный')),
            ],
            options={
                'verbose_name': 'Передача задачи',
                'verbose_name_plural': 'Передачи задач',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['task', '-created_at'], name='teammanager_task_id_8c2f58_idx')],
            },
        ),
    ]
