# Generated by Codex on 2026-07-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teammanager", "0001_task_handoff_and_coverage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamReportExportJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("section", models.CharField(db_index=True, max_length=48, verbose_name="Раздел")),
                ("report_code", models.CharField(db_index=True, max_length=96, verbose_name="Код отчёта")),
                ("report_title", models.CharField(max_length=160, verbose_name="Название отчёта")),
                ("filters", models.JSONField(blank=True, default=dict, verbose_name="Фильтры")),
                ("export_format", models.CharField(default="xlsx", max_length=16, verbose_name="Формат")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "В очереди"),
                            ("building", "Формируется"),
                            ("ready", "Готов"),
                            ("error", "Ошибка"),
                            ("expired", "Срок хранения истёк"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=24,
                        verbose_name="Статус",
                    ),
                ),
                ("row_count", models.PositiveIntegerField(blank=True, null=True, verbose_name="Строк")),
                ("file", models.FileField(blank=True, null=True, upload_to="team_reports/", verbose_name="Файл")),
                ("error_text", models.TextField(blank=True, verbose_name="Техническая ошибка")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="Старт")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="Финиш")),
                ("expires_at", models.DateTimeField(blank=True, null=True, verbose_name="Хранить до")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_report_export_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выгрузка отчёта менеджера",
                "verbose_name_plural": "Выгрузки отчётов менеджеров",
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(fields=["user", "-created_at"], name="teammanager_user_id_489e55_idx"),
                    models.Index(fields=["status", "created_at"], name="teammanager_status_2e66f2_idx"),
                    models.Index(fields=["section", "report_code"], name="teammanager_section_209718_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TeamReportFavorite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("section", models.CharField(db_index=True, max_length=48, verbose_name="Раздел")),
                ("report_code", models.CharField(db_index=True, max_length=96, verbose_name="Код отчёта")),
                ("last_filters", models.JSONField(blank=True, default=dict, verbose_name="Последние фильтры")),
                ("last_generated_at", models.DateTimeField(blank=True, null=True, verbose_name="Последнее формирование")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_report_favorites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Избранный отчёт менеджера",
                "verbose_name_plural": "Избранные отчёты менеджеров",
                "ordering": ("section", "report_code"),
                "indexes": [
                    models.Index(fields=["user", "section"], name="teammanager_user_id_2f3bd1_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "section", "report_code"), name="uniq_team_report_favorite"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TeamSavedReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=160, verbose_name="Название")),
                ("section", models.CharField(db_index=True, max_length=48, verbose_name="Раздел")),
                ("report_code", models.CharField(db_index=True, max_length=96, verbose_name="Код отчёта")),
                ("filters", models.JSONField(blank=True, default=dict, verbose_name="Фильтры")),
                ("sorting", models.JSONField(blank=True, default=dict, verbose_name="Сортировка")),
                ("visible_columns", models.JSONField(blank=True, default=list, verbose_name="Видимые столбцы")),
                ("export_format", models.CharField(default="xlsx", max_length=16, verbose_name="Формат экспорта")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_saved_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сохранённый отчёт менеджера",
                "verbose_name_plural": "Сохранённые отчёты менеджеров",
                "ordering": ("-updated_at", "-id"),
                "indexes": [
                    models.Index(fields=["user", "-updated_at"], name="teammanager_user_id_92d852_idx"),
                    models.Index(fields=["section", "report_code"], name="teammanager_section_48823b_idx"),
                ],
            },
        ),
    ]
