# Generated by Codex for OTG reachtruck planning.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reachtruck", "0002_boxclaim_palletlock"),
        ("shipping", "0010_alter_shippingorderitem_comment"),
        ("sku", "0010_sku_weight_gross_kg_sku_weight_net_kg"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtgDeliveryRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "requested_by_name",
                    models.CharField(blank=True, max_length=255),
                ),
                ("requested_by_role", models.CharField(blank=True, max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("planning", "Planning"),
                            ("planned", "Planned"),
                            ("dispatched", "Dispatched"),
                            ("in_progress", "In progress"),
                            ("partial", "Partial"),
                            ("done", "Done"),
                            ("blocked", "Blocked"),
                            ("canceled", "Canceled"),
                        ],
                        default="requested",
                        max_length=16,
                    ),
                ),
                ("requested_boxes", models.PositiveIntegerField(default=0)),
                ("planned_boxes", models.PositiveIntegerField(default=0)),
                ("shortage_boxes", models.PositiveIntegerField(default=0)),
                ("planning_error", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="otg_delivery_requests",
                        to="sku.agency",
                    ),
                ),
                (
                    "move_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="otg_delivery_requests",
                        to="reachtruck.moverequest",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="otg_delivery_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shipping_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otg_delivery_requests",
                        to="shipping.shippingorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="OtgDeliveryDemand",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("demand_key", models.CharField(max_length=64)),
                (
                    "demand_type",
                    models.CharField(
                        choices=[
                            ("full_box", "Full box"),
                            ("mixed_box", "Mixed box"),
                            ("partial_box_split", "Partial box split"),
                        ],
                        max_length=32,
                    ),
                ),
                ("boxes_required", models.PositiveIntegerField(default=0)),
                ("boxes_planned", models.PositiveIntegerField(default=0)),
                ("box_qty", models.PositiveIntegerField(default=0)),
                ("composition", models.JSONField(blank=True, default=list)),
                ("pick_composition", models.JSONField(blank=True, default=list)),
                ("item_quantities_per_box", models.JSONField(blank=True, default=dict)),
                ("source_box_codes", models.JSONField(blank=True, default=list)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demands",
                        to="otg_reachtruck.otgdeliveryrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="OtgPalletPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("full_pallet", "Full pallet"),
                            ("pick_boxes", "Pick boxes"),
                            ("partial_box_split", "Partial box split"),
                        ],
                        max_length=32,
                    ),
                ),
                ("pallet_code", models.CharField(db_index=True, max_length=128)),
                ("boxes_planned", models.PositiveIntegerField(default=0)),
                ("qty_planned", models.PositiveIntegerField(default=0)),
                ("from_location", models.JSONField(blank=True, default=dict)),
                ("selection_mode", models.CharField(blank=True, max_length=32)),
                ("planned_box_codes", models.JSONField(blank=True, default=list)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "demand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pallet_plans",
                        to="otg_reachtruck.otgdeliverydemand",
                    ),
                ),
                (
                    "move_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="otg_pallet_plans",
                        to="reachtruck.movetask",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pallet_plans",
                        to="otg_reachtruck.otgdeliveryrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="OtgPlanningEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(max_length=64)),
                ("message", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="otg_reachtruck.otgdeliveryrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="otgdeliveryrequest",
            index=models.Index(fields=["shipping_order", "status"], name="otg_reachtr_shippin_9ad287_idx"),
        ),
        migrations.AddIndex(
            model_name="otgdeliveryrequest",
            index=models.Index(fields=["agency", "status"], name="otg_reachtr_agency__e27399_idx"),
        ),
        migrations.AddIndex(
            model_name="otgdeliveryrequest",
            index=models.Index(fields=["created_at"], name="otg_reachtr_created_e69e02_idx"),
        ),
        migrations.AddIndex(
            model_name="otgdeliverydemand",
            index=models.Index(fields=["request", "demand_type"], name="otg_reachtr_request_268c74_idx"),
        ),
        migrations.AddIndex(
            model_name="otgdeliverydemand",
            index=models.Index(fields=["demand_key"], name="otg_reachtr_demand__1bb263_idx"),
        ),
        migrations.AddConstraint(
            model_name="otgdeliverydemand",
            constraint=models.UniqueConstraint(fields=("request", "demand_key"), name="uniq_otg_delivery_demand_key"),
        ),
        migrations.AddIndex(
            model_name="otgpalletplan",
            index=models.Index(fields=["request", "plan_type"], name="otg_reachtr_request_ce3986_idx"),
        ),
        migrations.AddIndex(
            model_name="otgpalletplan",
            index=models.Index(fields=["pallet_code", "plan_type"], name="otg_reachtr_pallet__979853_idx"),
        ),
        migrations.AddIndex(
            model_name="otgplanningevent",
            index=models.Index(fields=["request", "event_type"], name="otg_reachtr_request_8dfc29_idx"),
        ),
        migrations.AddIndex(
            model_name="otgplanningevent",
            index=models.Index(fields=["created_at"], name="otg_reachtr_created_3bfad3_idx"),
        ),
    ]
